"""Blender 4.5 LTS. Run from repo root with blender -b --python this-file.
Original reusable details; placement/footprints stay in the source metre frame.
"""
import bpy, math, json
from pathlib import Path
ROOT=Path.cwd(); OUT=ROOT/'assets-source/tirana-regional-detail'; OUT.mkdir(parents=True,exist_ok=True)
bpy.ops.object.select_all(action='SELECT'); bpy.ops.object.delete(use_global=False)
bpy.context.scene.unit_settings.system='METRIC'
models={}
colors={'stone':(.55,.51,.44),'trim':(.8,.79,.73),'glass':(.12,.23,.28),'steel':(.13,.16,.17),'tank':(.31,.34,.32),'roof':(.64,.3,.18)}
materials={}
for key,color in colors.items():
 m=bpy.data.materials.new(key);m.diffuse_color=(*color,1);materials[key]=m
class Part:
 def __init__(self,name):self.name=name;self.vertices=[];self.faces=[];self.colors=[]
 def mesh(self,verts,faces,color):
  off=len(self.vertices);self.vertices.extend((x,-z,y) for x,y,z in verts);self.faces.extend(tuple(off+i for i in f) for f in faces);self.colors.extend([color]*len(faces))
 def box(self,color,x,y,z,w,h,d):
  self.mesh([(x+i*w/2,y+j*h/2,z+k*d/2) for i,j,k in [(-1,-1,-1),(1,-1,-1),(1,1,-1),(-1,1,-1),(-1,-1,1),(1,-1,1),(1,1,1),(-1,1,1)]],[(0,3,2,1),(4,5,6,7),(0,4,7,3),(1,2,6,5),(0,1,5,4),(3,7,6,2)],color)
 def cylinder(self,color,x,y,z,r,h,n=12):
  v=[(x+math.cos(i*2*math.pi/n)*r,y+dy,z+math.sin(i*2*math.pi/n)*r) for dy in [-h/2,h/2] for i in range(n)]
  self.mesh(v,[(i,(i+1)%n,(i+1)%n+n,i+n) for i in range(n)]+[tuple(range(n-1,-1,-1)),tuple(range(n,n*2))],color)
 def finish(self):
  mesh=bpy.data.meshes.new(self.name);mesh.from_pydata(self.vertices,[],self.faces);mesh.update();mesh.calc_loop_triangles()
  obj=bpy.data.objects.new(self.name,mesh);bpy.context.collection.objects.link(obj)
  keys=list(materials)
  for mat in materials.values():mesh.materials.append(mat)
  for polygon,key in zip(mesh.polygons,self.colors):polygon.material_index=keys.index(key)
  positions=[];normals=[];rgb=[]
  for tri in mesh.loop_triangles:
   normal=tri.normal
   for vi in tri.vertices:
    p=mesh.vertices[vi].co;positions.extend(round(x,5) for x in (p.x,p.z,-p.y));normals.extend(round(x,5) for x in (normal.x,normal.z,-normal.y));rgb.extend(colors[self.colors[tri.polygon_index]])
  models[self.name]={'positions':positions,'normals':normals,'colors':rgb,'triangles':len(mesh.loop_triangles)}
p=Part('window');p.box('glass',0,0,.08,1.4,1.5,.08)
for x in [-.77,.77]:p.box('trim',x,0,.13,.14,1.8,.25)
for y in [-.83,.83]:p.box('trim',0,y,.13,1.68,.14,.25)
p.box('trim',0,0,.18,.05,1.5,.06);p.box('stone',0,-.88,.22,1.8,.1,.48);p.finish()
p=Part('balcony');p.box('stone',0,0,.45,2.1,.13,1)
p.box('steel',0,.94,.92,2.1,.06,.06)
for x in [-1,-.75,-.5,-.25,0,.25,.5,.75,1]:p.box('steel',x,.5,.92,.03,.9,.03)
for x in [-1,1]:p.box('steel',x,.94,.48,.05,.05,.9)
p.finish()
p=Part('ac');p.box('trim',0,0,.24,.72,.48,.4)
for y in [-.15,-.075,0,.075,.15]:p.box('steel',0,y,.45,.57,.025,.025)
for x in [-.25,.25]:p.box('steel',x,-.3,.22,.04,.2,.44)
p.finish()
p=Part('plinth');p.box('stone',0,.22,.08,1,.44,.18);p.box('trim',0,.47,.11,1,.06,.25);p.finish()
p=Part('gutter');p.box('steel',0,0,0,1,.05,.17);p.box('steel',0,.07,.085,1,.14,.03);p.finish()
p=Part('downpipe');p.cylinder('steel',0,.5,.13,.045,1,8);p.box('steel',0,.2,.08,.14,.04,.2);p.box('steel',0,.8,.08,.14,.04,.2);p.finish()
p=Part('tank');p.cylinder('tank',0,.65,0,.55,1.15);p.cylinder('steel',0,1.26,0,.2,.08);p.box('steel',0,.04,0,1.3,.08,1.3);p.finish()
p=Part('porch');p.box('roof',0,2.6,.6,2.8,.12,1.45)
for x in [-1.2,1.2]:p.box('trim',x,1.3,1.16,.13,2.6,.13)
p.box('stone',0,.08,.7,2.8,.16,1.5);p.finish()
p=Part('coping');p.box('stone',0,.25,0,1,.5,.23);p.box('trim',0,.52,0,1,.07,.35);p.finish()
bpy.ops.wm.save_as_mainfile(filepath=str(OUT/'regional-detail-kit.blend'),compress=True)
target=ROOT/'webapp/src/games/tirana-regional-detail/kitData.ts'
target.write_text('// Generated by Blender; do not edit by hand. Original mesh details CC0-1.0.\nexport const KIT = '+json.dumps(models,separators=(',',':'))+';\n')
(OUT/'manifest.json').write_text(json.dumps({'blender':bpy.app.version_string,'license':'CC0-1.0','models':{k:{'triangles':v['triangles']} for k,v in models.items()}},indent=2)+'\n')
print('KIT',len(models),'MODELS',sum(v['triangles'] for v in models.values()),'TRIANGLES')
