import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const root=process.env.UPGRADE_ROOT||path.resolve(import.meta.dirname,'..');
const {sampleCircuitDistance,circuitDistance,pointAhead,cornerSpeedLimit}=await import(pathToFileURL(path.join(root,'webapp/src/games/kartroyale/circuitMetrics.mjs')));
const track={points:[{x:0,z:0},{x:10,z:0},{x:10,z:30},{x:0,z:30}],length:80};
const near=(index,x,z)=>({index,x,z});
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} vs ${b}`);
test('nonuniform edge lengths interpolate in metres',()=>{const p=sampleCircuitDistance(track,25);close(p.x,10);close(p.z,15);});
test('projection includes distance already travelled within the current segment',()=>close(circuitDistance(track,near(1,10,15)),25));
test('lookahead begins at the projection, not the segment start',()=>{const p=pointAhead(track,near(1,10,15),20);close(p.x,5);close(p.z,30);});
test('forward wrap crosses the finish seam continuously',()=>{const p=pointAhead(track,near(3,0,2),5);close(p.x,3);close(p.z,0);});
test('negative distance wraps backwards',()=>{const p=sampleCircuitDistance(track,-5);close(p.x,0);close(p.z,5);});
test('whole laps preserve the sampled position',()=>{const a=sampleCircuitDistance(track,13),b=sampleCircuitDistance(track,813);close(a.x,b.x);close(a.z,b.z);});
test('corner approach slows the target speed',()=>{assert.ok(cornerSpeedLimit(track,near(1,10,29))<cornerSpeedLimit(track,near(1,10,3)));});
test('projection clamps numerical overshoot at segment ends',()=>{close(circuitDistance(track,near(0,12,0)),10);close(circuitDistance(track,near(0,-2,0)),0);});
test('invalid and degenerate geometry fails before caching',()=>{for(const points of [[],[{x:0,z:0},{x:0,z:0},{x:1,z:1}],[{x:NaN,z:0},{x:2,z:0},{x:3,z:1}]])assert.throws(()=>sampleCircuitDistance({points},0));});
test('invalid positions and distances are rejected',()=>{for(const n of [NaN,Infinity,-Infinity])assert.throws(()=>sampleCircuitDistance(track,n));assert.throws(()=>circuitDistance(track,near(-1,0,0)));assert.throws(()=>circuitDistance(track,near(0,Infinity,0)));});
