import test from 'node:test';
import assert from 'node:assert/strict';
import {createBowlingMatch,openTurn,beginShot,startReplay,completeRoll,nextTurn,activePlayer} from '../webapp/src/games/royallanes/shared/match.mjs';
import {newGame,recordRoll,totalScore,pinsAvailable,rollSymbols} from '../webapp/src/games/royallanes/shared/scoring.mjs';
import {ALL_PINS,sanitizeShot,chooseAiShot,simulateRoll} from '../webapp/src/games/royallanes/shared/replay.mjs';
import {validateSeatTableRequest} from '../bot/config/onlineGamePolicy.js';
import {createBowlingSimulationPool} from '../bot/services/bowlingSimulationPool.mjs';
const from=rolls=>rolls.reduce(recordRoll,newGame());
const match=()=>{const m=createBowlingMatch([{id:'A',name:'Alice'},{id:'B',name:'Bob'}]);openTurn(m,1000);return m;};
function apply(m,knocked){const p=activePlayer(m);const accepted=beginShot(m,p.id,{turnId:m.turnId,shot:{aim:.06,hook:0,power:78}});assert.equal(accepted.ok,true);const replay={knocked,standing:accepted.standing.slice(knocked),gutter:knocked===0,durationMs:100,ids:accepted.standing,frames:[],hz:24};startReplay(m,replay,2000);completeRoll(m,4000);nextTurn(m,7000);}
test('ten-pin score handles perfect games, spares and every tenth-frame rack',()=>{assert.equal(totalScore(from(Array(12).fill(10))),300);assert.equal(totalScore(from([...Array(10).fill([5,5]).flat(),5])),150);assert.equal(totalScore(from(Array(10).fill([9,0]).flat())),90);let g=from([...Array(18).fill(0),10,7]);assert.equal(pinsAvailable(g),3);assert.throws(()=>recordRoll(g,4));g=recordRoll(g,3);assert.deepEqual(rollSymbols(g.frames[9],9),['X','7','/']);assert.equal(totalScore(g),20);assert.throws(()=>recordRoll(g,0));});
test('bowler keeps the lane for a spare; turn changes only when their frame ends',()=>{const m=match();apply(m,7);assert.equal(activePlayer(m).id,'A');assert.equal(activePlayer(m).standing.length,3);apply(m,3);assert.equal(activePlayer(m).id,'B');assert.equal(activePlayer(m).standing.length,10);apply(m,10);assert.equal(activePlayer(m).id,'A');assert.equal(activePlayer(m).score.frames.length,2);});
test('two complete perfect scorecards earn all bonus rolls and finish as a draw',()=>{const m=match();let count=0;while(m.phase!=='finished'&&count<30){apply(m,10);count++;}assert.equal(count,24);assert.equal(m.phase,'finished');assert.equal(m.reason,'tie_refund');assert.ok(m.players.every(p=>totalScore(p.score)===300));});
test('strict shot and matchmaking contracts reject forged data and incompatible queues',()=>{for(const shot of [{aim:NaN,hook:0,power:75},{aim:0,hook:Infinity,power:75},{aim:0,hook:0,power:999},{aim:'0',hook:0,power:75}])assert.equal(sanitizeShot(shot),null);const m=match();assert.equal(beginShot(m,'B',{turnId:1,shot:{aim:0,hook:0,power:75}}).error,'not_your_turn');assert.equal(beginShot(m,'A',{turnId:0,shot:{aim:0,hook:0,power:75}}).error,'stale_turn');const request={gameType:'royallanes',stake:100,maxPlayers:2,matchMeta:{format:'tenpin',mode:'online',token:'TPG'}};assert.equal(validateSeatTableRequest(request).ok,true);assert.equal(validateSeatTableRequest({...request,maxPlayers:3}).ok,false);assert.equal(validateSeatTableRequest({...request,matchMeta:{...request.matchMeta,format:'client-wins'}}).ok,false);assert.equal(validateSeatTableRequest({...request,matchMeta:{...request.matchMeta,token:'BTC'}}).ok,false);});
test('worker solves real collisions off the socket thread and returns finite replay poses',async()=>{const pool=createBowlingSimulationPool();try{const [hit,gutter]=await Promise.all([pool.simulate({shot:{aim:.055,hook:0,power:75},standing:ALL_PINS}),pool.simulate({shot:{aim:1.2,hook:0,power:75},standing:ALL_PINS})]);assert.ok(hit.knocked>=6);assert.equal(gutter.knocked,0);assert.equal(gutter.gutter,true);assert.ok(hit.frames.length>70);assert.ok(hit.frames.every(f=>f.length===77&&f.every(Number.isFinite)));assert.equal(hit.knocked+hit.standing.length,10);}finally{await pool.close();}});
test('AI aims at real remaining pins and uses the same pin physics',()=>{const corner=chooseAiShot([6],'pro',()=>.5);assert.ok(corner.aim<-.4);const result=simulateRoll({shot:corner,standing:[6]});assert.equal(result.knocked,1);assert.equal(result.gutter,false);});
