import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {Server} from 'socket.io';
import {io as client} from 'socket.io-client';
import {attachRoyalLanes} from '../bot/services/royalLanes.js';
const table=id=>({id,stake:100,maxPlayers:2,players:['A','B'].map(id=>({id,tpcAccountNumber:id,name:id}))});
async function fixture(t,{simulate,settleMatch}={}){
  const http=createServer(),io=new Server(http,{transports:['websocket']});io.use((s,next)=>{s.data.playerId=s.handshake.auth.accountId;next();});let now=100000;const calls=[],jobs=[];
  const service=attachRoyalLanes(io,{clock:()=>now,autoTick:false,simulate:simulate||((payload)=>{jobs.push(payload);return Promise.resolve({ids:payload.standing,input:payload.shot,standing:[],knocked:payload.standing.length,gutter:false,durationMs:100,hz:24,frames:[[0,0,0,0,0,0,1]],stride:7});}),settleMatch:settleMatch||(async(id,outcome)=>{calls.push({id,...outcome});return {status:outcome.winnerAccountId?'paid':'refunded',amount:outcome.winnerAccountId?200:100,...outcome};})});
  await new Promise(r=>http.listen(0,'127.0.0.1',r));const clients=[];
  const connect=async accountId=>{const c=client(`http://127.0.0.1:${http.address().port}`,{auth:{accountId},transports:['websocket'],forceNew:true,reconnection:false});clients.push(c);await new Promise((r,j)=>{c.once('connect',r);c.once('connect_error',j);});return c;};
  const emit=(c,event,data={})=>new Promise((r,j)=>c.timeout(3000).emit(`bowling:${event}`,data,(e,v)=>e?j(e):r(v)));
  const advance=async ms=>{now+=ms;service.tick();await new Promise(r=>setImmediate(r));};
  const start=async()=>{service.createMatch(table('lane'));const a=await connect('A'),b=await connect('B');await emit(a,'join',{tableId:'lane'});await emit(b,'join',{tableId:'lane'});await advance(3100);return {a,b};};
  t.after(async()=>{clients.forEach(c=>c.disconnect());await service.close();await new Promise(r=>io.close(r));});return {service,connect,emit,advance,start,calls,jobs};
}
const shot=(turnId,requestId='request')=>({turnId,requestId,shot:{aim:.055,hook:0,power:75}});
test('only the registered current bowler can submit; replacements revoke the old device',async t=>{const f=await fixture(t),{a,b}=await f.start(),x=await f.connect('outsider');assert.equal((await f.emit(x,'join',{tableId:'lane',accountId:'A'})).ok,false);assert.equal((await f.emit(b,'roll',shot(1))).error,'not_your_turn');assert.equal((await f.emit(a,'roll',{...shot(1),shot:{aim:NaN,hook:0,power:75}})).ok,false);await f.advance(300);const r=await f.emit(a,'roll',{...shot(1),pins:999,winnerAccountId:'B'});assert.equal(r.ok,true);await f.advance(1);assert.equal(f.jobs.length,1);assert.equal((await f.emit(a,'roll',shot(1))).duplicate,true);const state=(await f.emit(a,'sync')).state;assert.equal(state.roll.replay.knocked,10);assert.equal(state.players[0].score.frames[0].length,0);assert.equal(state.players[0].socketId,undefined);const replacement=await f.connect('A');await f.emit(replacement,'join',{tableId:'lane'});assert.equal((await f.emit(a,'roll',shot(1))).error,'not_in_match');a.disconnect();await f.advance(31);assert.equal(f.service.rooms.get('lane').seats[0].connected,true);await f.advance(5000);assert.equal(f.service.rooms.get('lane').match.players[0].score.frames[0][0],10);});
test('twenty-four legal strikes finish two scorecards and refund the tie exactly once',async t=>{const f=await fixture(t),{a,b}=await f.start();let n=0;const room=f.service.rooms.get('lane');while(room.match.phase!=='finished'&&n<30){const m=room.match;const c=m.players[m.activeIndex].id==='A'?a:b;assert.equal((await f.emit(c,'roll',shot(m.turnId,`r-${n}`))).ok,true);await f.advance(1);await f.advance(1600);assert.equal(room.match.phase,'result');await f.advance(2500);n++;}assert.equal(n,24);assert.equal(room.match.reason,'tie_refund');assert.equal(f.calls.length,1);assert.equal(f.calls[0].winnerAccountId,'');await f.emit(a,'leave');await f.advance(6000);assert.equal(f.calls.length,1);});
test('disconnect grace allows rejoining; expiry forfeits once and does not release the wrong seat',async t=>{const f=await fixture(t),{a,b}=await f.start();a.disconnect();await f.advance(1);await f.advance(10000);const restored=await f.connect('A');assert.equal((await f.emit(restored,'join',{tableId:'lane'})).ok,true);await f.advance(20000);assert.equal(f.calls.length,0);restored.disconnect();await f.advance(1);await f.advance(31000);assert.equal(f.calls.length,1);assert.equal(f.calls[0].winnerAccountId,'B');await f.emit(b,'leave');assert.equal(f.calls.length,1);});
test('an incomplete start refunds both stakes; worker failure also refunds without a client winner',async t=>{const f=await fixture(t);f.service.createMatch(table('unloaded'));await f.advance(91000);assert.equal(f.calls[0].reason,'loading_timeout_refund');assert.equal(f.calls[0].winnerAccountId,'');const g=await fixture(t,{simulate:async()=>{throw Error('failed_worker');}});const {a}=await g.start();await g.emit(a,'roll',shot(1));await g.advance(1);assert.equal(g.calls[0].reason,'simulation_failed_refund');assert.equal(g.calls[0].winnerAccountId,'');});
test('two missed turns forfeit; failed settlements retry without reopening play',async t=>{let attempts=0;const f=await fixture(t,{simulate:async p=>({ids:p.standing,input:p.shot,standing:p.standing,knocked:0,gutter:true,durationMs:100,hz:24,frames:[],stride:7}),settleMatch:async(id,outcome)=>{attempts++;if(attempts===1)throw Error('temporary_db_failure');return {status:'paid',amount:200,...outcome};}});await f.start();const room=f.service.rooms.get('lane');for(let i=0;i<2;i++){await f.advance(36000);await f.advance(1600);await f.advance(2500);}assert.equal(room.match.phase,'finished');assert.equal(room.match.winnerAccountId,'B');assert.equal(room.settlement.status,'pending');await f.advance(6000);assert.equal(attempts,2);assert.equal(room.settlement.status,'paid');});
