import test from 'node:test';import assert from 'node:assert/strict';
import {stitchRings,importLakeSource,LAKE_WAY,PARK_RELATION} from '../webapp/scripts/tirana/lakeSource.mjs';
// Synthetic topology fixture inside Tirana's latitude range, NOT the real shoreline.
function fixture(){const coords=[[19.815,41.307],[19.824,41.307],[19.824,41.313],[19.815,41.313],[19.814,41.306],[19.825,41.306],[19.825,41.314],[19.814,41.314]];return {elements:[...coords.map(([lon,lat],i)=>({type:'node',id:i+1,lat,lon})),{type:'way',id:LAKE_WAY,nodes:[1,2,3,4,1],tags:{natural:'water'}},{type:'way',id:9,nodes:[5,6,7,8,5],tags:{}},{type:'way',id:10,nodes:[5,6],tags:{highway:'footway'}},{type:'relation',id:PARK_RELATION,tags:{type:'multipolygon'},members:[{type:'way',role:'outer',ref:9},{type:'way',role:'inner',ref:LAKE_WAY}]}]};}
test('review preserves all shoreline nodes and park water holes without smoothing',()=>{const f=fixture(),r=importLakeSource(f);assert.deepEqual(r.lake.nodeIds,[1,2,3,4,1]);assert.equal(r.lake.p.length,4);assert.equal(r.park.holes.length,1);assert.deepEqual(r.park.holes[0],r.lake.p);assert.equal(r.readyForRuntime,false);assert.equal(r.stage,'review-only');assert.equal(r.roads[0].nodeA,'5');});
test('missing source nodes fail instead of joining across missing shoreline',()=>{const f=fixture();f.elements=f.elements.filter(e=>!(e.type==='node'&&e.id===3));assert.throws(()=>importLakeSource(f),/Missing\/invalid node/);});
test('unclosed source lake fails instead of adding a guessed closing segment',()=>{const f=fixture();f.elements.find(e=>e.id===LAKE_WAY).nodes.pop();assert.throws(()=>importLakeSource(f),/Unclosed/);});
test('lake alone and incomplete Grand Park relations cannot pass review',()=>{const f=fixture();f.elements=f.elements.filter(e=>e.id!==PARK_RELATION);assert.throws(()=>importLakeSource(f),/Grand Park/);const g=fixture();g.elements=g.elements.filter(e=>e.id!==10);assert.throws(()=>importLakeSource(g),/Roads\/paths/);});
test('lake cannot be converted into park land by dropping the inner member',()=>{const f=fixture();f.elements.find(e=>e.id===PARK_RELATION).members.pop();assert.throws(()=>importLakeSource(f),/inner water hole/);});
test('multipolygon chains join by source node identity and reverse segments correctly',()=>{assert.deepEqual(stitchRings([[1,2],[3,2],[3,4],[4,1]]),[[1,2,3,4,1]]);assert.throws(()=>stitchRings([[1,2],[3,4]]),/Open/);assert.throws(()=>stitchRings([[1,2],[2,3],[2,4],[3,1],[4,1]]),/ambiguous/);});
test('partial Overpass responses and duplicate source IDs are rejected',()=>{assert.throws(()=>importLakeSource({elements:[],remark:'timeout'}),/incomplete/);const f=fixture();f.elements.push(f.elements[0]);assert.throws(()=>importLakeSource(f),/Duplicate/);});
test('unknown building heights stay unknown and explicit street furniture retains provenance',()=>{const f=fixture();f.elements.push({type:'way',id:100,nodes:[5,6,7,8,5],tags:{building:'yes'}},{type:'node',id:101,lat:41.314,lon:19.815,tags:{amenity:'bench'}});const r=importLakeSource(f);assert.equal(r.buildings[0].h,null);assert.equal(r.furniture[0].asset,'park-bench');assert.equal(r.furniture[0].yaw,null);assert.match(r.furniture[0].source,/node\/101$/);});
