import test from 'node:test';import assert from 'node:assert/strict';
import {facadeSites,createSiteIndex,AD_BRANDS} from '../webapp/src/games/tirana-region/facadeCore.mjs';
import {buildFacadeGltf} from '../webapp/src/games/tirana-region/facadeAssets.mjs';
import {advertSVG,signSVG} from '../webapp/src/games/tirana-region/advertArt.mjs';
import {regionalBounds,regionalReferences,projectRegion,sampleHeight,buildRegionQuery} from '../webapp/src/games/tirana-region/regionCore.mjs';
const origin=[41.3275,19.8188],bounds=[-805,-380,660,1150];
const square=[[0,0],[12,0],[12,12],[0,12]];
const world=()=>({buildings:[{id:1,p:square.map(p=>[...p]),h:12}],roads:[{a:[-10,-6],b:[22,-6],w:6}]});
test('all requested regional references are covered without editing original bounds',()=>{const copy=[...bounds],b=regionalBounds(origin,bounds);assert.deepEqual(bounds,copy);assert.ok(Object.isFrozen(b));assert.ok(b[2]-b[0]>17000);assert.ok(b[3]-b[1]>15000);for(const p of regionalReferences(origin)){assert.ok(p.x>=b[0]&&p.x<=b[2]&&p.z>=b[1]&&p.z<=b[3]);assert.equal(p.available,false);}});
test('Kamza bend is not silently replaced by Kamza town; TEG stays south of centre',()=>{const p=regionalReferences(origin);assert.equal(p.find(p=>p.id==='kamza-turn').osm,'node/10909820605');assert.ok(p.find(p=>p.id==='teg').z>4500);assert.ok(p.find(p=>p.id==='dajti-upper').x>7000);});
test('projection preserves geographic quadrants in the existing source frame',()=>{assert.ok(projectRegion(origin,41.34,19.84).x>0);assert.ok(projectRegion(origin,41.34,19.84).z<0);assert.ok(projectRegion(origin,41.30,19.79).z>0);assert.throws(()=>projectRegion([91,19],41,19));assert.throws(()=>projectRegion([41,181],41,19));assert.throws(()=>projectRegion(origin,NaN,19));});
test('facades face a real stored road and preserve the footprint exactly',()=>{const w=world(),before=JSON.stringify(w),sites=facadeSites(w);assert.equal(sites.length,1);assert.ok(sites[0].z<0);assert.ok(Math.abs(Math.abs(sites[0].yaw)-Math.PI)<1e-8);assert.equal(JSON.stringify(w),before);});
test('reversed footprint winding produces the same outward placement',()=>{const a=facadeSites(world())[0],w=world();w.buildings[0].p.reverse();const b=facadeSites(w)[0];assert.deepEqual(b,a);});
test('named landmarks, excluded buildings, low buildings and absent frontage are not decorated',()=>{for(const mutate of [w=>w.buildings[0].name='Historic site',w=>w.buildings[0].h=3,w=>w.roads=[]]){const w=world();mutate(w);assert.deepEqual(facadeSites(w),[]);}assert.deepEqual(facadeSites(world(),new Set(['1'])),[]);});
test('unknown heights stay undecorated rather than extending a kit through the roof',()=>{const w=world();delete w.buildings[0].h;assert.deepEqual(facadeSites(w),[]);});
test('streaming has a deterministic nearest-first cap and radius',()=>{const sites=Array.from({length:300},(_,i)=>({id:String(i).padStart(3,'0'),x:i,z:0})),select=createSiteIndex(sites);assert.equal(select({x:0,z:0},240,48).length,48);assert.equal(select({x:0,z:0},135,16).length,16);assert.equal(select({x:0,z:0},2,48).length,3);assert.deepEqual(select({x:NaN,z:0}),[]);assert.equal(select({x:0,z:0},1000,1000).length,96);});
test('advertising is four original variants, 2K posters and undistorted 4:1 signs',()=>{assert.equal(AD_BRANDS.length,4);for(let i=0;i<4;i++){assert.match(advertSVG(i),/width="2048" height="1024"/);assert.match(signSVG(i),/width="2048" height="512"/);assert.ok(signSVG(i).includes(AD_BRANDS[i].title));assert.doesNotMatch(signSVG(i),/<script|<foreignObject|https:\/\//);}assert.throws(()=>advertSVG(4));assert.throws(()=>signSVG(0,8192));});
test('all facade variants export valid, self-contained, finite glTF geometry',()=>{
 for(let variant=0;variant<4;variant++){
  const g=buildFacadeGltf(variant);assert.equal(g.asset.version,'2.0');const data=Buffer.from(g.buffers[0].uri.split(',')[1],'base64');assert.equal(data.length,g.buffers[0].byteLength);assert.equal(g.materials.length,6);
  for(const a of g.accessors){const v=g.bufferViews[a.bufferView],bytes=a.componentType===5123?2:4,n=a.type==='SCALAR'?1:Number(a.type.slice(-1));assert.equal(v.byteOffset%4,0);assert.equal(v.byteLength,a.count*n*bytes);assert.ok(v.byteOffset+v.byteLength<=data.length);}
  for(const mesh of g.meshes)for(const p of mesh.primitives){const a=g.accessors[p.attributes.POSITION],v=g.bufferViews[a.bufferView],n=g.accessors[p.attributes.NORMAL],nv=g.bufferViews[n.bufferView],ia=g.accessors[p.indices],iv=g.bufferViews[ia.bufferView];assert.ok(a.min[1]>2.6);assert.ok(a.max[1]<6);for(let i=0;i<ia.count;i+=3){const ids=[0,1,2].map(k=>data.readUInt16LE(iv.byteOffset+(i+k)*2));assert.ok(ids.every(id=>id<a.count));const pts=ids.map(id=>[0,1,2].map(k=>data.readFloatLE(v.byteOffset+id*12+k*4)));const u=pts[1].map((x,k)=>x-pts[0][k]),w=pts[2].map((x,k)=>x-pts[0][k]),cross=[u[1]*w[2]-u[2]*w[1],u[2]*w[0]-u[0]*w[2],u[0]*w[1]-u[1]*w[0]],normal=[0,1,2].map(k=>data.readFloatLE(nv.byteOffset+ids[0]*12+k*4));assert.ok(Math.hypot(...cross)>1e-7);assert.ok(cross.reduce((s,x,k)=>s+x*normal[k],0)>0);}}
 }
});
test('glTF rejects unsupported image types rather than shipping SVG as core glTF texture',()=>{assert.throws(()=>buildFacadeGltf(0,'data:image/svg+xml,<svg/>'));const g=buildFacadeGltf(0,'data:image/png;base64,AAAA');assert.equal(g.materials[3].pbrMetallicRoughness.baseColorTexture.index,0);assert.equal(g.samplers[0].wrapS,33071);});
test('DEM sampler preserves slopes, borders and no-data holes',()=>{const g={width:2,height:2,bounds:[0,0,100,100],values:[100,200,300,400],noData:-9999};assert.equal(sampleHeight(g,50,50),250);assert.equal(sampleHeight(g,100,100),400);assert.equal(sampleHeight(g,-1,20),null);assert.equal(sampleHeight({...g,values:[100,-9999,300,400]},50,50),null);assert.equal(sampleHeight({...g,values:[100,null,300,400]},50,50),null);});
test('acquisition query requests original OSM node topology, water relations and ring relation',()=>{const q=buildRegionQuery();assert.match(q,/relation\(20772795\)/);assert.match(q,/way\[highway\]/);assert.match(q,/>>/);assert.doesNotMatch(q,/google|earth|streetview/i);});
