import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createClipIndex} from '../webapp/src/games/tirana-environment/clipIndex.mjs';
const rect=(x,z,w=10)=>[[[x,z],[x+w,z],[x+w,z+w],[x,z+w],[x,z]]];
test('indexed park exclusions preserve original geometry references and stable order',()=>{const p=[rect(0,0),rect(200,0),rect(5,5),rect(0,200)],q=createClipIndex(p);assert.deepEqual(q([0,0,15,15]),[p[0],p[2]]);assert.equal(q([0,0,15,15])[0],p[0]);});
test('clipping includes touching boundaries and handles negative coordinates',()=>{const a=rect(-20,-20),b=rect(0,0),q=createClipIndex([a,b]);assert.deepEqual(q([-10,-10,0,0]),[a,b]);});
test('invalid index/query dimensions are rejected instead of creating unbounded loops',()=>{assert.throws(()=>createClipIndex([],0));assert.throws(()=>createClipIndex([[[[NaN,0]]]]));assert.throws(()=>createClipIndex([])([0,0,Infinity,1]));});
test('very wide polygons and queries remain bounded and preserve overlap behavior',()=>{const p=rect(-1e6,-1e6,2e6),q=createClipIndex([p,rect(0,0)]);assert.equal(q([-1e7,-1e7,1e7,1e7]).length,2);assert.equal(q([1e5,1e5,1e5+1,1e5+1]).length,1);});
test('battlefield factory retains original equipment and uses the existing shared glTF layer',()=>{const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');const factory=read('webapp/src/games/blackwater/world.ts'),city=read('webapp/src/games/blackwater/cityWorld.ts'),layer=read('webapp/src/games/tiranastreets/street-career/BattleHumanLayer.ts');assert.match(factory,/makeOriginalEnemy\(\)/);assert.match(factory,/tiranaKeepEquipment/);assert.match(city,/battleHumans\?\.update/);assert.match(city,/battleHumans\?\.dispose/);assert.match(layer,/SharedHumans/);assert.doesNotMatch(layer,/requestAnimationFrame|setInterval|createState/);});
test('shared human loading prioritizes the bundled Chess model and allows explicit failed-asset retry',()=>{const source=readFileSync(new URL('../webapp/src/games/tiranastreets/street-career/SharedHumans.ts',import.meta.url),'utf8');assert.match(source,/if\(local\)this.request\(local\)/);assert.match(source,/retryFailed\(\)/);assert.match(source,/priority:readonly string\[\]/);});
