import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createCampaign,CHAPTER_IDS,STREET_SAVE_KEY} from '../webapp/src/games/tiranastreets/street-career/campaignCore.mjs';
import {HUMAN_ROSTER,humanFor,actorRole,nearbyHumans,screenStick} from '../webapp/src/games/tiranastreets/street-career/humanRoster.mjs';
// Synthetic domain fixtures; actual engine integration is in the separate suite.
const missions=CHAPTER_IDS.map((id,i)=>({id,reward:(i+1)*100}));
const weapons=[{id:'starter',magazine:12},{id:'rifle',magazine:30}];
const api=createCampaign(missions,weapons,'starter');
const clone=o=>JSON.parse(JSON.stringify(o));
function result(profile,extra={}) {return {mode:'solo',phase:'finished',missionId:profile.active.id,difficulty:profile.active.difficulty,players:{local:{...clone(profile.loadout),finished:true,failed:false,health:100,finishTime:20}},...extra};}
function complete(profile,id=CHAPTER_IDS[profile.completed.length],difficulty='normal'){const p=api.begin(profile,id,difficulty);return api.resolve(p,result(p),'local');}

test('campaign requires every real mission ID and a known starter',()=>{assert.throws(()=>createCampaign([],weapons,'starter'));assert.throws(()=>createCampaign(missions,weapons,'missing'));assert.equal(api.chapters.length,9);});
test('first chapter unlocks, future chapters and invalid difficulty do not',()=>{const p=api.fresh();assert.ok(api.begin(p,CHAPTER_IDS[0]));assert.equal(api.begin(p,CHAPTER_IDS[1]),null);assert.equal(api.begin(p,'unknown'),null);assert.equal(api.begin(p,CHAPTER_IDS[0],'impossible'),null);});
test('all nine original jobs progress in sequence',()=>{let p=api.fresh();for(const id of CHAPTER_IDS)p=complete(p,id);assert.deepEqual(p.completed,CHAPTER_IDS);assert.equal(p.loadout.cash,750+4500);});
test('completion pays once and replays cannot duplicate rewards',()=>{let p=complete(api.fresh());const cash=p.loadout.cash;p=complete(p,CHAPTER_IDS[0]);assert.equal(p.loadout.cash,cash);assert.equal(p.completed.length,1);assert.equal(api.resolve(p,{mode:'solo'},'local'),null);});
test('rewards use the chosen engine difficulty',()=>{for(const [level,reward] of [['easy',80],['normal',100],['hard',125]])assert.equal(complete(api.fresh(),CHAPTER_IDS[0],level).loadout.cash,750+reward);});
test('failed, downed, unfinished and non-finite results receive no payout',()=>{const p=api.begin(api.fresh(),CHAPTER_IDS[0]);for(const changes of [{failed:true},{health:0},{finished:false},{finishTime:NaN},{finishTime:-1}]){const s=result(p);Object.assign(s.players.local,changes);assert.equal(api.resolve(p,s,'local'),null);}});
test('online, wrong chapter, wrong difficulty and active-state results are rejected',()=>{const p=api.begin(api.fresh(),CHAPTER_IDS[0]);for(const extra of [{mode:'career'},{mode:'rivals'},{missionId:CHAPTER_IDS[1]},{difficulty:'hard'},{phase:'active'}])assert.equal(api.resolve(p,result(p,extra),'local'),null);assert.equal(api.resolve(p,result(p),'other'),null);});
test('best time improves without a duplicate payout',()=>{let p=complete(api.fresh());p=api.begin(p,CHAPTER_IDS[0]);const s=result(p);s.players.local.finishTime=7;p=api.resolve(p,s,'local');assert.equal(p.best[CHAPTER_IDS[0]],7);assert.equal(p.loadout.cash,850);});
test('profile normalization is independent and enforces a completed prefix',()=>{const raw={...api.fresh(),completed:[CHAPTER_IDS[0],CHAPTER_IDS[0],CHAPTER_IDS[2]],best:{[CHAPTER_IDS[0]]:5,[CHAPTER_IDS[2]]:1}};const before=clone(raw),p=api.normalize(raw);assert.deepEqual(p.completed,[CHAPTER_IDS[0]]);assert.equal(p.best[CHAPTER_IDS[2]],undefined);assert.deepEqual(clone(raw),before);});
test('unsupported and corrupt profile versions reset safely',()=>{for(const raw of [null,[],false,{},'broken',{version:2}])assert.deepEqual(api.normalize(raw),api.fresh());});
test('invalid active chapter is discarded',()=>{for(const id of ['missing',CHAPTER_IDS[5]])assert.equal(api.normalize({...api.fresh(),active:{id,checkpoint:{}}}).active,null);});
test('retry checkpoint stores a deep, sanitized starting loadout',()=>{const p=api.fresh();p.loadout.cash=900;const run=api.begin(p,CHAPTER_IDS[0]);p.loadout.cash=1;p.loadout.inventory.starter.ammo=0;assert.equal(run.active.checkpoint.cash,900);assert.equal(run.active.checkpoint.inventory.starter.ammo,12);});
test('abandon restores starting inventory rather than keeping mission pickups',()=>{let p=api.begin(api.fresh(),CHAPTER_IDS[0]);p.loadout.cash=9999;p.loadout.inventory.rifle={ammo:30,reserve:30};p=api.abandon(p);assert.equal(p.loadout.cash,750);assert.equal(p.loadout.inventory.rifle,undefined);assert.equal(p.active,null);});
test('free-roam loadout persists but an active mission cannot overwrite its checkpoint',()=>{const p=api.fresh(),player={cash:123,weapon:'rifle',inventory:{rifle:{ammo:7,reserve:30}}};assert.equal(api.saveExplore(p,player).loadout.cash,123);const active=api.begin(p,CHAPTER_IDS[0]);assert.equal(api.saveExplore(active,player).active.checkpoint.cash,750);});
test('successful missions keep resulting weapon inventory and street cash',()=>{const p=api.begin(api.fresh(),CHAPTER_IDS[0]),s=result(p);s.players.local.cash=300;s.players.local.weapon='rifle';s.players.local.inventory.rifle={ammo:4,reserve:22};const done=api.resolve(p,s,'local');assert.equal(done.loadout.cash,400);assert.deepEqual(done.loadout.inventory.rifle,{ammo:4,reserve:22});});
test('unknown inventory and prototype keys cannot become weapons',()=>{const raw=clone(api.fresh());raw.loadout.inventory=JSON.parse('{"__proto__":{"ammo":9},"missing":{"ammo":9},"rifle":{"ammo":999,"reserve":99999}}');raw.loadout.weapon='__proto__';const p=api.normalize(raw);assert.deepEqual(Object.keys(p.loadout.inventory),['rifle']);assert.equal(p.loadout.weapon,'rifle');assert.deepEqual(p.loadout.inventory.rifle,{ammo:30,reserve:240});});
test('holstered state survives saves and malformed numbers are bounded',()=>{const p=api.fresh();p.loadout.weapon='';p.loadout.cash=Infinity;p.loadout.inventory.starter={ammo:NaN,reserve:-9};const n=api.normalize(p);assert.equal(n.loadout.weapon,'');assert.equal(n.loadout.cash,750);assert.equal(n.loadout.inventory.starter.ammo,0);assert.equal(n.loadout.inventory.starter.reserve,0);});
test('apply copies only loadout fields, not health, positions or paid-account fields',()=>{const player={x:9,health:55,accountBalance:888},p=api.fresh();api.apply(player,p.loadout);assert.equal(player.health,55);assert.equal(player.x,9);assert.equal(player.accountBalance,888);player.inventory.starter.ammo=0;assert.equal(p.loadout.inventory.starter.ammo,12);});
test('save/reload roundtrip retains the retry point',()=>{let raw;const storage={getItem:k=>{assert.equal(k,STREET_SAVE_KEY);return raw;},setItem:(k,v)=>{assert.equal(k,STREET_SAVE_KEY);raw=v;}};const p=api.begin(complete(api.fresh()),CHAPTER_IDS[1],'hard');assert.equal(api.save(storage,p),true);assert.deepEqual(api.load(storage),p);});
test('storage failure and broken JSON do not crash play',()=>{assert.equal(api.save(undefined,api.fresh()),false);assert.equal(api.save({setItem(){throw Error('full');}},api.fresh()),false);assert.deepEqual(api.load({getItem:()=>'{broken'}),api.fresh());assert.deepEqual(api.load({getItem(){throw Error('blocked');}}),api.fresh());});
test('six existing appearances reference only four local GLB files',()=>{assert.equal(HUMAN_ROSTER.length,6);assert.equal(new Set(HUMAN_ROSTER.map(h=>h.url)).size,4);assert.ok(HUMAN_ROSTER.every(h=>h.url.startsWith('/assets/')&&h.url.endsWith('.glb')));assert.ok(HUMAN_ROSTER.every(h=>Object.isFrozen(h.roles)));});
test('all police are existing athlete humans; military stays soldier',()=>{for(let i=0;i<100;i++){assert.match(humanFor({id:String(i),kind:'police'}).url,/athlete-(male|female)\.glb$/);assert.equal(humanFor({id:String(i),kind:'soldier'}).sourceId,'mixamo-soldier');assert.equal(actorRole('military'),'soldier');}});
test('civilian selection varies without changing for the same identity',()=>{const ids=new Set();for(let i=0;i<100;i++){const n={id:`citizen-${i}`,kind:'civilian'};ids.add(humanFor(n).id);assert.equal(humanFor(n),humanFor({...n}));}assert.equal(ids.size,5);});
test('nearby selection has exact caps and does not mutate NPC order or data',()=>{const npcs=Array.from({length:70},(_,i)=>({id:`n-${i}`,x:70-i,z:0,motion:'walk'})),before=clone(npcs);assert.equal(nearbyHumans(npcs,{x:0,z:0}).length,24);assert.equal(nearbyHumans(npcs,{x:0,z:0},true).length,12);assert.deepEqual(npcs,before);});
test('drivers and invalid/distant positions are excluded',()=>{const npcs=[{id:'drive',x:0,z:0,motion:'drive'},{id:'bad',x:NaN,z:0},{id:'far',x:500,z:0}];assert.deepEqual(nearbyHumans(npcs,{x:0,z:0}),[]);assert.deepEqual(nearbyHumans([], {x:NaN,z:0}),[]);});
test('portrait stick respects visible left/right/up/down and clamps diagonals',()=>{assert.ok(screenStick(20,0).x>0);assert.ok(screenStick(-20,0).x<0);assert.ok(screenStick(0,-20).y>0);assert.ok(screenStick(0,20).y<0);assert.ok(Math.abs(Math.hypot(...Object.values(screenStick(100,-100)))-1)<1e-12);assert.deepEqual(screenStick(NaN,0),{x:0,y:0});});
test('online guard runs before either local career branch',()=>{const s=readFileSync(new URL('../webapp/src/games/blackwater/ui.tsx',import.meta.url),'utf8');assert.match(s,/props.mode\s*===\s*'online'/);assert.match(s,/activity\s*===\s*'street-career'/);assert.ok(s.search(/if\s*\(\s*props.mode\s*===\s*'online'\s*\)/)<s.search(/if\s*\(\s*activity\s*===\s*'street-career'\s*\)/));assert.match(s,/lazy\(/);assert.match(s,/activity=career/);});
test('runtime uses the existing simulation but never an account/room transport',()=>{const s=readFileSync(new URL('../webapp/src/games/tiranastreets/street-career/StreetCareerRuntime.ts',import.meta.url),'utf8');assert.match(s,/this.simulation.step\(dt\)/);const adapter=readFileSync(new URL('../webapp/src/games/tiranastreets/street-career/StreetSimulation.mjs',import.meta.url),'utf8');assert.match(adapter,/advanceState\(this\.state,\s*dt,\s*this\.hooks\)/);assert.match(s,/campaign.resolve/);assert.match(s,/visibilitychange/);assert.doesNotMatch(s,/httpTransport|CityConnection|fetch\(|\/api\//);});
