import test from 'node:test';import assert from 'node:assert/strict';
import {importRegionSource,stitchRegionRings} from '../webapp/scripts/tirana/regionImport.mjs';
const options={origin:[41.3275,19.8188],sourceURL:'https://www.openstreetmap.org/',acquiredAt:'2026-09-08T00:00:00Z',sha256:'a'.repeat(64)};
function fixture(){return {elements:[{type:'node',id:1,lat:41.33,lon:19.81},{type:'node',id:2,lat:41.33,lon:19.82},{type:'node',id:3,lat:41.32,lon:19.82},{type:'node',id:4,lat:41.32,lon:19.81},{type:'way',id:10,nodes:[1,2,3],tags:{highway:'primary',name:'Synthetic test only',oneway:'-1',bridge:'yes',layer:'1','cycleway:right':'lane'}},{type:'way',id:11,nodes:[1,2,3,4,1],tags:{building:'yes'}}]};}
test('source import preserves every original road segment and node identity',()=>{const f=fixture(),before=JSON.stringify(f),r=importRegionSource(f,options);assert.equal(r.roads.length,2);assert.deepEqual(r.roads.map(p=>[p.nodeA,p.nodeB]),[['1','2'],['2','3']]);assert.equal(JSON.stringify(f),before);assert.equal(r.runtimeReady,false);assert.equal(r.stage,'source-review');});
test('bridge, direction, width uncertainty and tagged cycle lanes survive import',()=>{const r=importRegionSource(fixture(),options),road=r.roads[0];assert.equal(road.oneway,-1);assert.equal(road.bridge,true);assert.equal(road.layer,1);assert.equal(road.cyclewayRight,'lane');assert.equal(road.cyclewayLeft,null);assert.equal(road.width,null);assert.equal(r.buildings[0].h,null);});
test('coincident coordinates never merge distinct source IDs',()=>{const f=fixture();f.elements.push({type:'node',id:5,lat:41.33,lon:19.82},{type:'way',id:12,nodes:[5,4],tags:{highway:'secondary'}});const r=importRegionSource(f,options);assert.equal(r.roads[0].nodeB,'2');assert.equal(r.roads[2].nodeA,'5');assert.deepEqual(r.roads[0].b,r.roads[2].a);});
test('roundabout explicit oneway=no takes priority over the implicit direction',()=>{const f=fixture();f.elements.find(e=>e.id===10).tags={highway:'primary',junction:'roundabout',oneway:'no'};assert.equal(importRegionSource(f,options).roads[0].oneway,false);});
test('partial responses, duplicate IDs, missing nodes and absent provenance fail',()=>{const f=fixture();assert.throws(()=>importRegionSource({...f,remark:'timeout'},options),/Incomplete/);f.elements.push(f.elements[0]);assert.throws(()=>importRegionSource(f,options),/Duplicate/);const g=fixture();g.elements=g.elements.filter(e=>e.id!==2);assert.throws(()=>importRegionSource(g,options),/Missing/);assert.throws(()=>importRegionSource(fixture(),{}),/Provenance/);});
test('unclosed polygons fail; measured heights are not invented',()=>{const f=fixture(),b=f.elements.find(e=>e.id===11);b.nodes.pop();assert.throws(()=>importRegionSource(f,options),/Unclosed/);b.nodes.push(1);b.tags.height='12 m';assert.equal(importRegionSource(f,options).buildings[0].h,12);b.tags.height='approx 12';assert.equal(importRegionSource(f,options).buildings[0].h,null);});
test('construction roads do not silently become playable roads',()=>{const f=fixture();f.elements.push({type:'way',id:12,nodes:[1,4],tags:{highway:'construction',construction:'motorway'}});const r=importRegionSource(f,options);assert.equal(r.roads.length,2);assert.ok(r.warnings.some(s=>s.includes('unbuilt')));});
test('multipolygon stitching supports reversed ways but rejects open or ambiguous chains',()=>{assert.deepEqual(stitchRegionRings([[1,2],[3,2],[3,4],[4,1]]),[[1,2,3,4,1]]);assert.throws(()=>stitchRegionRings([[1,2],[2,3]]),/Open/);assert.throws(()=>stitchRegionRings([[1,2],[2,3],[2,4],[3,1],[4,1]]),/ambiguous/);});
test('water multipolygon islands remain holes and member ways are not duplicated',()=>{const f=fixture();f.elements.push(...[[5,41.329,19.812],[6,41.329,19.815],[7,41.324,19.815],[8,41.324,19.812]].map(([id,lat,lon])=>({type:'node',id,lat,lon})),{type:'way',id:12,nodes:[5,6,7,8,5],tags:{natural:'water'}},{type:'relation',id:20,tags:{type:'multipolygon',natural:'water'},members:[{type:'way',ref:11,role:'outer'},{type:'way',ref:12,role:'inner'}]});const r=importRegionSource(f,options);assert.equal(r.water.length,1);assert.equal(r.water[0].polygons[0].holes.length,1);assert.equal(r.water[0].polygons[0].holes[0].length,4);});
