// Generated by scripts/buildTennisEngine.mjs; edit the TypeScript source.
export const TOUR = [
    {
        name: 'Coastal Club',
        place: 'Split',
        surface: 'hard',
        opponents: ['Mika Vale', 'Luca Marin', 'Sofia Reyes'],
        difficulty: 0,
        prize: 3
    },
    {
        name: 'Clay Challenger',
        place: 'Barcelona',
        surface: 'clay',
        opponents: ['Enzo Costa', 'Nadia Silva', 'Rafael Sol'],
        difficulty: 1,
        prize: 4
    },
    {
        name: 'Garden Open',
        place: 'London',
        surface: 'grass',
        opponents: ['Alex Reed', 'Freya Lane', 'Oliver West'],
        difficulty: 1,
        prize: 5
    },
    {
        name: 'Night Masters',
        place: 'Tokyo',
        surface: 'hard',
        opponents: ['Ren Sato', 'Yuna Mori', 'Kai Tanaka'],
        difficulty: 2,
        prize: 6
    },
    {
        name: 'Royal Finals',
        place: 'Melbourne',
        surface: 'hard',
        opponents: ['Ava Brooks', 'Noah Ellis', 'The Champion'],
        difficulty: 2,
        prize: 8
    }
];
export const freshCareer = () => ({
    tour: 0,
    round: 0,
    wins: 0,
    losses: 0,
    credits: 0,
    upgrades: [0, 0, 0],
    bestRally: 0,
    completed: false
});
export function normalizeCareer(value) {
    const base = freshCareer();
    const number = (candidate, fallback = 0) => Number.isFinite(Number(candidate))
        ? Math.max(0, Math.floor(Number(candidate)))
        : fallback;
    const completed = Boolean(value?.completed);
    const tour = Math.min(number(value?.tour), TOUR.length - 1);
    const round = completed ? 3 : Math.min(number(value?.round), 2);
    const upgrades = Array.from({ length: 3 }, (_, index) => Math.min(3, number(value?.upgrades?.[index])));
    return {
        ...base,
        ...value,
        tour,
        round,
        wins: number(value?.wins),
        losses: number(value?.losses),
        credits: number(value?.credits),
        upgrades,
        bestRally: number(value?.bestRally),
        completed
    };
}
export function careerResult(c, won, rally) {
    const current = normalizeCareer(c);
    const n = {
        ...current,
        upgrades: [...current.upgrades],
        bestRally: Math.max(current.bestRally, rally)
    };
    if (n.completed)
        return n;
    if (won) {
        n.wins++;
        n.credits += 2;
        n.round++;
        if (n.round === 3) {
            n.credits += TOUR[n.tour].prize;
            n.round = 0;
            n.tour++;
            if (n.tour === TOUR.length) {
                n.tour = TOUR.length - 1;
                n.completed = true;
                n.round = 3;
            }
        }
    }
    else
        n.losses++;
    return n;
}
export function previewServices() {
    let c = freshCareer(), active = '';
    const offline = async () => {
        throw Error('Open the full game to play online.');
    };
    return {
        online: false,
        career: async () => c,
        startCareer: async () => {
            active = 'preview-' + Date.now();
            return { id: active, career: c };
        },
        finishCareer: async (id, won, rally) => {
            if (id === active) {
                c = careerResult(c, won, rally);
                active = '';
            }
            return c;
        },
        upgrade: async (stat) => {
            if (c.credits < 2 || c.upgrades[stat] >= 3)
                throw Error('Earn two skill points from a match first.');
            c = {
                ...c,
                credits: c.credits - 2,
                upgrades: c.upgrades.map((v, i) => (i === stat ? v + 1 : v))
            };
            return c;
        },
        createRoom: offline,
        joinRoom: offline,
        syncRoom: offline,
        leaveRoom: async () => { }
    };
}
export const matchConfig = (mode, c, difficulty, surface) => {
    const career = normalizeCareer(c);
    return mode === 'career'
        ? {
            ai: true,
            difficulty: TOUR[career.tour].difficulty,
            surface: TOUR[career.tour].surface,
            gamesToWin: 3,
            setsToWin: 1,
            upgrades: career.upgrades,
            seed: Date.now() >>> 0
        }
        : {
            ai: true,
            difficulty,
            surface,
            gamesToWin: mode === 'full' ? 6 : mode === 'set' ? 3 : 1,
            setsToWin: mode === 'full' ? 2 : 1,
            upgrades: [0, 0, 0],
            seed: Date.now() >>> 0
        };
};
