/** Generated by build-tirana-identity-models.mjs. */
export const RELIEF_BRANDS = new Set(["intesa","otp","union","abi","tirana-bank","fibank","procredit","uba","eco-market","sophie","kfc","burger-king","tirana-international","teg","qtu","rossmann-lala","neranxi","pizzahut","marriott"]);
