import * as T from 'three';
import {BLENDER} from './blenderData.mjs';
import VILLA_BAY from '../tirana-landmark-rebuild/villa-bay.mjs';
import VILLA_BALCONY from '../tirana-landmark-rebuild/villa-balcony.mjs';
import {coloredGeometry} from '../tirana-landmark-rebuild/geometry';
/** Generated by evaluated Blender meshes. No loading flash or remote model URL. */
export function modelGeometry(name:string){
 if(name==='villa-bay')return coloredGeometry(VILLA_BAY).translate(0,-1.1,0);
 if(name==='villa-balcony')return coloredGeometry(VILLA_BALCONY);
 const p=BLENDER.models[name];if(!p)throw Error(`Missing Blender model ${name}`);
 const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p.p,3));g.setAttribute('normal',new T.Float32BufferAttribute(p.n,3));g.setAttribute('color',new T.Float32BufferAttribute(p.c,3));g.computeBoundingSphere();return g;
}
export function modelMesh(name:string,material?:T.Material){return new T.Mesh(modelGeometry(name),material||new T.MeshStandardMaterial({vertexColors:true,roughness:.78}));}
export const ROOFS=BLENDER.roofs as Record<string,{x:number;z:number;height:number}>;
