import * as T from 'three';
import {BLENDER} from './blenderData.mjs';
/** Generated by evaluated Blender meshes. No loading flash or remote model URL. */
export function modelGeometry(name:string){
 const p=BLENDER.models[name];if(!p)throw Error(`Missing Blender model ${name}`);
 const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p.p,3));g.setAttribute('normal',new T.Float32BufferAttribute(p.n,3));g.setAttribute('color',new T.Float32BufferAttribute(p.c,3));g.computeBoundingSphere();return g;
}
export function modelMesh(name:string,material?:T.Material){return new T.Mesh(modelGeometry(name),material||new T.MeshStandardMaterial({vertexColors:true,roughness:.78}));}
export const ROOFS=BLENDER.roofs as Record<string,{x:number;z:number;height:number}>;
