import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { creatorReturnPath } from '../../../../shared/socialApp.js';
import { ArrowLeft, ArrowUpRight, CalendarClock, Check, CheckCircle2, ChevronRight, CircleHelp, Clock3, FileText, ImagePlus, Link2, Loader2, LogOut, Plus, Radio, Send, Settings2, ShieldCheck, Trash2, X } from 'lucide-react';
import { FaFacebookF, FaInstagram, FaYoutube } from 'react-icons/fa';
import { SiTiktok } from 'react-icons/si';
import { Account, creatorApi, Media, Platform, uploadMedia, openCreatorAuthorization } from './api';
import LiveStudio from './LiveStudio';
import GoogleStudioSignIn from './GoogleStudioSignIn';
import ConnectAccountButton from './ConnectAccountButton';
import './creator.css';
const icons: Record<string, any> = { youtube: FaYoutube, facebook: FaFacebookF, instagram: FaInstagram, tiktok: SiTiktok };
function PlatformIcon({ platform, color }: { platform: string; color?: string }) { const Icon = icons[platform]; return <span className="cs-platform-icon" style={{ color: color || 'inherit' }}>{Icon ? <Icon size={20} /> : '?'}</span>; }
const emptySettings = () => ({ youtubePrivacy: 'private', madeForKids: undefined as boolean | undefined, tiktok: { privacy: '', consent: false, comments: false, duet: false, stitch: false, disclosure: false, ownBrand: false, branded: false, aiGenerated: false } });
const labels: Record<string, string> = { draft: 'Draft', scheduled: 'Scheduled', queued: 'In queue', sending: 'Sending', processing: 'Processing', published: 'Published', partial: 'Partly published', failed: 'Needs attention', attention: 'Check platform', cancelled: 'Cancelled' };
export default function CreatorStudio({ active = true, onBroadcastStateChange }: { active?: boolean; onBroadcastStateChange?: (state: 'idle' | 'preparing' | 'active') => void }) {
  const [tab, setTab] = useState(() => new URLSearchParams(location.search).get('tab') === 'accounts' ? 'accounts' : 'compose'), [catalog, setCatalog] = useState<any>({ platforms: [] }), [user, setUser] = useState<any>(null);
  const [accounts, setAccounts] = useState<Account[]>([]), [posts, setPosts] = useState<any[]>([]), [mediaLibrary, setMediaLibrary] = useState<Media[]>([]);
  const [returningSignIn, setReturningSignIn] = useState(false);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [title, setTitle] = useState(''), [caption, setCaption] = useState(''), [targets, setTargets] = useState<string[]>([]), [media, setMedia] = useState<Media | null>(null);
  const [overrides, setOverrides] = useState<Record<string, string>>({}), [settings, setSettings] = useState(emptySettings), [customize, setCustomize] = useState(false);
  const [schedule, setSchedule] = useState(false), [scheduledAt, setScheduledAt] = useState(''), [draftId, setDraftId] = useState(''), [uploadProgress, setUploadProgress] = useState(0);
  const [libraryOpen, setLibraryOpen] = useState(false), [helpOpen, setHelpOpen] = useState(false), [tiktokInfo, setTiktokInfo] = useState<any>(null);
  const [confirm, setConfirm] = useState<{ title: string; text: string; action: () => Promise<void> } | null>(null);
  const [broadcastState, setBroadcastState] = useState<'idle' | 'preparing' | 'active'>('idle');
  useEffect(() => { onBroadcastStateChange?.(broadcastState); }, [broadcastState, onBroadcastStateChange]);
  useEffect(() => { if (!active) { setConfirm(null); setLibraryOpen(false); } }, [active]);
  const sessionEpoch = useRef(0);
  const requestId = useRef(crypto.randomUUID()), fileInput = useRef<HTMLInputElement>(null), dialog = useRef<HTMLDialogElement>(null), libraryDialog = useRef<HTMLDialogElement>(null);
  const signedIn = Boolean(user?.signedIn), platforms: Platform[] = catalog.platforms;
  const selectedAccounts = accounts.filter(a => targets.includes(a.id));
  const selectedPlatforms = platforms.filter(p => selectedAccounts.some(a => a.platform === p.id));
  const youtubeSelected = selectedPlatforms.some(p => p.id === 'youtube'), tiktokSelected = selectedPlatforms.some(p => p.id === 'tiktok');
  const refresh = useCallback(async () => {
    const epoch = sessionEpoch.current;
    const [accountResult, postResult, mediaResult] = await Promise.all([creatorApi('/accounts'), creatorApi('/posts'), creatorApi('/media')]);
    if (epoch !== sessionEpoch.current) return;
    setAccounts(accountResult.accounts); setPosts(postResult.posts); setMediaLibrary(mediaResult.media);
  }, []);
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const [c, s] = await Promise.all([creatorApi('/catalog'), creatorApi('/session')]);
        if (cancelled) return; setCatalog(c); setUser(s);
        if (s.signedIn) await refresh(); else setTab('accounts');
        const result = new URLSearchParams(location.search).get('connection');
        if (result) { setTab('accounts'); if (result === 'connected') setNotice('Connection complete. Choose where you want to post.'); else setError(result === 'cancelled' ? 'Connection cancelled. You can try again whenever you’re ready.' : 'The account could not be connected. Check its account type and permissions, then try again.'); history.replaceState(null, '', location.pathname); }
      } catch (e: any) { if (!cancelled) setError(e.message); }
      finally { if (!cancelled) setLoading(false); }
    })();
    return () => { cancelled = true; };
  }, [refresh]);
  useEffect(() => {
    if (!signedIn) return;
    const timer = setInterval(() => { if (!document.hidden) refresh().catch(() => {}); }, 15000);
    return () => clearInterval(timer);
  }, [signedIn, refresh]);
  useEffect(() => {
    if (confirm && !dialog.current?.open) dialog.current?.showModal();
    else if (!confirm) dialog.current?.close();
  }, [confirm]);
  useEffect(() => { if (libraryOpen) libraryDialog.current?.showModal(); else libraryDialog.current?.close(); }, [libraryOpen]);
  const tiktokId = selectedAccounts.find(a => a.platform === 'tiktok')?.id;
  useEffect(() => {
    setTiktokInfo(null); let cancelled = false;
    setSettings(s => ({ ...s, tiktok: { ...s.tiktok, privacy: '', comments: false, duet: false, stitch: false, consent: false } }));
    if (tiktokId) creatorApi(`/accounts/${tiktokId}/tiktok-options`).then(info => { if (!cancelled) setTiktokInfo(info); }).catch(e => { if (!cancelled) setError(e.message); });
    return () => { cancelled = true; };
  }, [tiktokId]);
  async function perform(name: string, action: () => Promise<void>) {
    if (busy) return; setBusy(name); setError(''); setNotice('');
    try { await action(); } catch (e: any) { setError(e.message); } finally { setBusy(''); }
  }
  function clearComposer() { setTitle(''); setCaption(''); setTargets([]); setMedia(null); setOverrides({}); setSettings(emptySettings()); setDraftId(''); setSchedule(false); setScheduledAt(''); requestId.current = crypto.randomUUID(); }
  function toggleAccount(account: Account) {
    setTargets(old => old.includes(account.id) ? old.filter(id => id !== account.id) : [...old.filter(id => account.platform !== 'tiktok' || accounts.find(a => a.id === id)?.platform !== 'tiktok'), account.id]);
  }
  const body = () => ({ title, caption, targets, mediaId: media?.id || '', overrides, settings, requestId: requestId.current });
  async function saveDraft() {
    const post = await creatorApi(draftId ? `/posts/${draftId}` : '/posts', draftId ? 'PATCH' : 'POST', body());
    setDraftId(post._id); return post;
  }
  async function editDraft(post: any) {
    setTitle(post.title || ''); setCaption(post.caption || ''); setTargets(post.targets || []); setOverrides(post.overrides || {}); setSettings({ ...emptySettings(), ...post.settings }); setDraftId(post._id); setSchedule(false); setScheduledAt('');
    setMedia(post.mediaId ? await creatorApi(`/media/${post.mediaId}`) : null); setTab('compose'); window.scrollTo({ top: 0, behavior: 'smooth' });
  }
  const validation = selectedPlatforms.flatMap(p => {
    const errors: string[] = [], text = overrides[p.id] || caption;
    if (Array.from(text).length > p.limit) errors.push(`${p.name}: caption is too long (${p.limit} max).`);
    if (!p.post.includes(media?.mime || 'text')) errors.push(`${p.name}: ${!media ? 'add a compatible photo or video' : 'this media type is not supported'}.`);
    if (!p.available) errors.push(`${p.name}: connection setup is pending.`);
    return errors;
  });
  if (youtubeSelected && (!title.trim() || settings.madeForKids === undefined)) validation.push('YouTube: add a title and choose whether this is made for children.');
  if (tiktokSelected && (!tiktokInfo || !settings.tiktok.privacy || !settings.tiktok.consent)) validation.push('TikTok: choose an audience and accept the posting terms.');
  if (tiktokSelected && schedule) validation.push('Publish TikTok now. Schedule other platforms in a separate post.');
  if (tiktokSelected && settings.tiktok.disclosure && !settings.tiktok.ownBrand && !settings.tiktok.branded) validation.push('TikTok: choose which brand this video promotes.');
  if (tiktokSelected && settings.tiktok.branded && settings.tiktok.privacy === 'SELF_ONLY') validation.push('TikTok: paid partnerships cannot have a private audience.');
  const canPublish = signedIn && targets.length > 0 && !validation.length && Boolean(caption.trim() || media) && (!schedule || Boolean(scheduledAt)) && !busy;
  const webview = Boolean((window as any).Telegram?.WebApp?.initData || (window as any).Capacitor?.isNativePlatform?.());
  return <div className="cs-root">
    <header className="cs-header"><Link to="/" className="cs-back" aria-label="Back to TonPlayGram"><ArrowLeft size={20} /></Link><div className="cs-wordmark"><span className="cs-monogram">TPG</span><div><h1>Creator Studio</h1><span>Create. Connect. Go live.</span></div></div><button className="cs-icon-button" aria-label="Studio help" onClick={() => setHelpOpen(!helpOpen)}><CircleHelp size={21} /></button></header>
    <div className="cs-intro"><span className="cs-eyebrow">YOUR CONTENT. EVERYWHERE.</span><h2>One studio.<br /><span>All your audiences.</span></h2><p>Post across your accounts and broadcast from your phone.</p></div>
    <nav className="cs-tabs" aria-label="Studio sections">{[{ id: 'compose', label: 'Create', Icon: Plus }, { id: 'live', label: 'Go live', Icon: Radio }, { id: 'accounts', label: 'Accounts', Icon: Link2 }, { id: 'activity', label: 'Activity', Icon: Clock3 }].map(({ id, label, Icon }) => <button key={id} aria-current={tab === id ? 'page' : undefined} onClick={() => { setTab(id); setError(''); }}><Icon size={19} /><span>{label}</span></button>)}</nav>
    {broadcastState !== 'idle' && tab !== 'live' && <div className="cs-broadcast-banner" role="status"><Radio size={20} /><span>{broadcastState === 'preparing' ? 'Preparing your broadcast…' : 'Your broadcast session is open.'}</span><button className="cs-secondary" onClick={() => setTab('live')}>Return to live studio</button></div>}
    {helpOpen && <aside className="cs-panel cs-help"><h2>Three steps to share</h2><ol><li>Tap Connect on a platform and approve access on its official page.</li><li>Choose your destinations and review your content.</li><li>Publish, schedule, or enable your camera to go live.</li></ol><p>Connections open the platform’s own approval screen. No passwords, access codes or stream keys to paste here.</p><p>Instagram needs a Business or Creator account; Facebook uses Pages. Live is supported on eligible YouTube and Facebook accounts. Your selected platforms may require approval before access is available.</p><p><Link to="/privacy">Privacy policy</Link> · <Link to="/terms">Terms</Link></p></aside>}
    {error && <div className="cs-message cs-error" role="alert"><span>{error}</span><button aria-label="Dismiss error" onClick={() => setError('')}><X size={18} /></button></div>}
    {notice && <div className="cs-message cs-success" role="status"><CheckCircle2 size={20} /><span>{notice}</span><button aria-label="Dismiss notice" onClick={() => setNotice('')}><X size={18} /></button></div>}
    {loading ? <div className="cs-panel cs-loading" role="status"><Loader2 className="cs-spin" /> Opening your studio…</div> : !signedIn && <section className="cs-panel cs-signin"><div className="cs-section-heading"><ShieldCheck size={24} /><span className="cs-tag">Private account connections</span></div><h2>Connect your first account</h2><p>Choose a platform below to sign in and connect in one step. Returning to your saved studio? Use the same sign-in method as before.</p><button className="cs-link-button" aria-expanded={returningSignIn} onClick={() => setReturningSignIn(value => !value)}>Use an existing Google or Telegram Studio</button>{returningSignIn && <div className="cs-auth-buttons">{(window as any).Telegram?.WebApp?.initData && <button className="cs-primary" disabled={Boolean(busy)} onClick={() => perform('telegram', async () => { const u = await creatorApi('/session/telegram', 'POST', { initData: (window as any).Telegram.WebApp.initData }); setUser(u); await refresh(); })}>Continue with Telegram</button>}{catalog.googleLogin ? catalog.googleLoginMethod === 'identity' ? <GoogleStudioSignIn onError={setError} onAuthenticated={async u => { sessionEpoch.current++; setUser(u); setError(''); setNotice('Signed in with Google. Choose which social accounts to connect.'); try { await refresh(); } catch { setError('Signed in, but your accounts could not load. Please refresh Studio.'); } }} /> : <button className="cs-secondary" disabled={Boolean(busy)} onClick={() => perform('login', async () => { const r = await creatorApi('/login/google', 'POST', { returnTo: creatorReturnPath(location.pathname) }); openCreatorAuthorization(r.url); })}>Continue with Google<ArrowUpRight size={17} /></button> : <p className="cs-notice" role="status">{catalog.googleLoginReason === 'secure_storage' ? 'Studio sign-in is temporarily unavailable. Please contact TonPlayGram support.' : 'Google sign-in has not been configured for TonPlayGram yet. This needs to be enabled by the app owner.'}</p>}</div>}{webview && <p className="cs-muted">If a platform asks for a browser, <a href={new URL(creatorReturnPath(location.pathname), window.location.origin).href} target="_blank" rel="noopener noreferrer">open Creator Studio in your browser</a> and connect there.</p>}</section>}
    <main>
      {tab === 'compose' && <div className="cs-compose-grid"><section className="cs-panel cs-composer"><div className="cs-section-heading"><h2>{draftId ? 'Edit your draft' : 'Create a post'}</h2><span className="cs-tag">{targets.length} selected</span></div><label className="cs-field-title">Share to</label><div className="cs-account-chips">{accounts.filter(a => a.status === 'connected' && platforms.find(p => p.id === a.platform)?.post.length).map(a => <button key={a.id} disabled={Boolean(busy)} aria-pressed={targets.includes(a.id)} title={a.name} onClick={() => toggleAccount(a)}><PlatformIcon platform={a.platform} color={platforms.find(p => p.id === a.platform)?.color} /><span>{a.name}</span>{targets.includes(a.id) && <Check size={15} />}</button>)}<button className="cs-add-account" onClick={() => setTab('accounts')}><Plus size={17} />{accounts.length ? 'Add' : 'Connect accounts'}</button></div>
        <label>Title <span className="cs-muted">{youtubeSelected ? 'Required for YouTube' : 'Optional'}</span><input maxLength={100} placeholder="Give your video a title" value={title} disabled={Boolean(busy)} onChange={e => setTitle(e.target.value)} /></label>
        <label>Caption<textarea rows={5} value={caption} disabled={Boolean(busy)} onChange={e => setCaption(e.target.value)} placeholder="What would you like to share? Add your story, links and hashtags…" /></label>
        <div className="cs-caption-footer"><button className="cs-link-button" aria-expanded={customize} onClick={() => setCustomize(!customize)}><Settings2 size={16} /> Customize for each platform</button><span>{Array.from(caption).length.toLocaleString()}</span></div>
        {customize && selectedPlatforms.map(p => <label key={p.id}>{p.name} caption <small>{p.limit.toLocaleString()} max</small><textarea rows={3} value={overrides[p.id] || ''} disabled={Boolean(busy)} placeholder="Use the shared caption" onChange={e => setOverrides(o => ({ ...o, [p.id]: e.target.value }))} /></label>)}
        <input ref={fileInput} type="file" className="cs-sr-only" accept="image/jpeg,image/png,video/mp4" onChange={e => { const file = e.target.files?.[0]; e.target.value = ''; if (file) void perform('upload', async () => { setUploadProgress(0); setMedia(await uploadMedia(file, setUploadProgress)); await refresh(); }); }} />
        {media ? <div className="cs-media-preview">{media.mime.startsWith('video/') ? <video src={media.url} controls playsInline preload="metadata" /> : <img src={media.url} alt={media.name} />}<div><span>{media.name}</span><button className="cs-icon-button" aria-label="Remove attachment from post" disabled={Boolean(busy)} onClick={() => setMedia(null)}><X size={18} /></button></div></div> : <button className="cs-upload" disabled={!signedIn || Boolean(busy)} onClick={() => fileInput.current?.click()}><ImagePlus size={26} /><strong>{busy === 'upload' ? `Uploading ${uploadProgress}%` : 'Add a photo or video'}</strong><span>JPG, PNG or MP4 · up to 250 MB</span>{busy === 'upload' && <progress value={uploadProgress} max="100" />}</button>}
        <button className="cs-link-button" disabled={!signedIn || Boolean(busy)} onClick={() => setLibraryOpen(true)}>Choose from your media</button>
        {youtubeSelected && <div className="cs-options"><h3>YouTube options</h3><label>Visibility<select value={settings.youtubePrivacy} onChange={e => setSettings(s => ({ ...s, youtubePrivacy: e.target.value }))}><option value="private">Private</option><option value="unlisted">Unlisted</option><option value="public">Public</option></select></label><label>Is this video made for children?<select value={settings.madeForKids === undefined ? '' : String(settings.madeForKids)} onChange={e => setSettings(s => ({ ...s, madeForKids: e.target.value === '' ? undefined : e.target.value === 'true' }))}><option value="">Choose audience</option><option value="false">No, not made for children</option><option value="true">Yes, made for children</option></select></label></div>}
        {tiktokSelected && <div className="cs-options"><h3>TikTok · {tiktokInfo?.creator_nickname || 'Loading account options…'}</h3><label>Who can see this video?<select value={settings.tiktok.privacy} disabled={!tiktokInfo} onChange={e => setSettings(s => ({ ...s, tiktok: { ...s.tiktok, privacy: e.target.value } }))}><option value="">Select an audience</option>{(tiktokInfo?.privacy_level_options || []).map((p: string) => <option key={p} value={p} disabled={p === 'SELF_ONLY' && settings.tiktok.branded}>{({ PUBLIC_TO_EVERYONE: 'Everyone', MUTUAL_FOLLOW_FRIENDS: 'Friends', FOLLOWER_OF_CREATOR: 'Followers', SELF_ONLY: 'Only me' } as any)[p] || p}</option>)}</select></label>{([{ key: 'comments', label: 'Allow comments', disabled: tiktokInfo?.comment_disabled }, { key: 'duet', label: 'Allow Duet', disabled: tiktokInfo?.duet_disabled }, { key: 'stitch', label: 'Allow Stitch', disabled: tiktokInfo?.stitch_disabled }, { key: 'aiGenerated', label: 'AI-generated content', disabled: false }, { key: 'disclosure', label: 'This video promotes a brand, product or service', disabled: false }] as const).map(item => <label className="cs-checkbox" key={item.key}><input type="checkbox" disabled={!tiktokInfo || item.disabled} checked={settings.tiktok[item.key]} onChange={e => setSettings(s => ({ ...s, tiktok: { ...s.tiktok, [item.key]: e.target.checked } }))} />{item.label}</label>)}{settings.tiktok.disclosure && <><label className="cs-checkbox"><input type="checkbox" checked={settings.tiktok.ownBrand} onChange={e => setSettings(s => ({ ...s, tiktok: { ...s.tiktok, ownBrand: e.target.checked } }))} />Your brand · labeled Promotional content</label><label className="cs-checkbox"><input type="checkbox" checked={settings.tiktok.branded} onChange={e => setSettings(s => ({ ...s, tiktok: { ...s.tiktok, branded: e.target.checked } }))} />Another brand · labeled Paid partnership</label></>}<label className="cs-checkbox"><input type="checkbox" checked={settings.tiktok.consent} onChange={e => setSettings(s => ({ ...s, tiktok: { ...s.tiktok, consent: e.target.checked } }))} /><span>I agree to TikTok’s <a target="_blank" rel="noopener noreferrer" href="https://www.tiktok.com/legal/page/global/music-usage-confirmation/en">Music Usage Confirmation</a>{settings.tiktok.branded && <> and <a href="https://www.tiktok.com/legal/page/global/bc-policy/en" target="_blank" rel="noopener noreferrer">Branded Content Policy</a></>}, and authorize this upload.</span></label><p className="cs-muted">Your video may take a few minutes to appear after processing.</p></div>}
        <div className="cs-publish-options"><label className="cs-checkbox"><input type="checkbox" checked={schedule} disabled={Boolean(busy)} onChange={e => setSchedule(e.target.checked)} /><CalendarClock size={18} /> Schedule for later</label>{schedule && <label>Publish time<input type="datetime-local" value={scheduledAt} onChange={e => setScheduledAt(e.target.value)} /><small>Your timezone: {Intl.DateTimeFormat().resolvedOptions().timeZone}</small></label>}</div>
        {validation.length > 0 && <div className="cs-validation" aria-live="polite">{validation.map(text => <p key={text}>{text}</p>)}</div>}
        <div className="cs-composer-actions"><button className="cs-secondary" disabled={!signedIn || Boolean(busy) || (!caption.trim() && !media && !title.trim())} onClick={() => perform('save', async () => { await saveDraft(); await refresh(); setNotice('Draft saved to your account.'); })}><FileText size={18} /> Save draft</button><button className="cs-primary" disabled={!canPublish} onClick={() => setConfirm({ title: schedule ? 'Schedule this post?' : 'Publish this post?', text: `${schedule ? 'Scheduled for ' + new Date(scheduledAt).toLocaleString() + ' on ' : 'This will be sent to '}${selectedAccounts.map(a => a.name).join(', ')}. Each platform processes content separately.`, action: async () => { const post = await saveDraft(); await creatorApi(`/posts/${post._id}/submit`, 'POST', { scheduledAt: schedule ? new Date(scheduledAt).toISOString() : undefined }); clearComposer(); await refresh(); setTab('activity'); setNotice(schedule ? 'Post scheduled.' : 'Post queued. You can follow each platform below.'); } })}>{schedule ? <CalendarClock size={18} /> : <Send size={18} />}{schedule ? 'Schedule' : 'Publish'}</button></div>
      </section><aside className="cs-compose-aside"><section className="cs-panel cs-preview-card"><div className="cs-section-heading"><h2>Post preview</h2><span className="cs-tag">Shared content</span></div><div className="cs-preview-author"><span className="cs-avatar">{(user?.name || 'Y').slice(0, 1)}</span><div><strong>{user?.name || 'Your account'}</strong><small>{selectedPlatforms.length ? selectedPlatforms.map(p => p.name).join(' · ') : 'Choose your destinations'}</small></div></div>{media && (media.mime.startsWith('video/') ? <video src={media.url} controls playsInline preload="metadata" /> : <img src={media.url} alt={media.name} />)}{title && <h3>{title}</h3>}<p className={caption ? 'cs-preview-caption' : 'cs-muted'}>{caption || 'Your caption and media will appear here.'}</p><p className="cs-muted">Final layout varies by platform. Platform captions are applied when publishing.</p></section><section className="cs-panel cs-tip"><ShieldCheck size={23} /><h3>Connect once. Stay in control.</h3><p>You choose every destination. Disconnect accounts whenever you need to.</p><button className="cs-link-button" onClick={() => setTab('accounts')}>Manage accounts <ChevronRight size={16} /></button></section></aside></div>}
      <div hidden={tab !== 'live'}><LiveStudio accounts={accounts} platforms={platforms} enabled={Boolean(catalog.liveEnabled)} signedIn={signedIn} onError={setError} visible={active && tab === 'live'} onBroadcastStateChange={setBroadcastState} /></div>
      {tab === 'accounts' && <section className="cs-accounts"><div className="cs-section-heading"><div><h2>Your connected world</h2><p className="cs-muted">Tap Connect and approve on the official platform. No codes or keys to paste here.</p></div><span className="cs-tag">{accounts.filter(a => a.status === 'connected').length} connected</span></div><div className="cs-platform-grid">{platforms.map(p => <article className="cs-panel cs-platform-card" key={p.id}><div className="cs-section-heading"><div className="cs-platform-name"><PlatformIcon platform={p.id} color={p.color} /><h3>{p.name}</h3></div><span className="cs-tag">{p.live && p.post.length ? 'Post + live' : p.live ? 'Live' : 'Post'}</span></div><p>{p.note}</p>{accounts.filter(a => a.platform === p.id).map(a => <div className="cs-connected-row" key={a.id}><div><strong>{a.name}</strong><small className={a.status === 'connected' ? 'cs-on-air' : ''}>{a.status === 'connected' ? 'Connected' : 'Reconnect needed'}</small></div><button className="cs-icon-button" aria-label={`Disconnect ${a.name}`} disabled={Boolean(busy)} onClick={() => setConfirm({ title: `Disconnect ${a.name}?`, text: 'Studio will remove its saved access and cancel pending posts for this account. Already published posts stay on the platform. You can also remove access in the platform’s settings.', action: async () => { await creatorApi(`/accounts/${a.id}`, 'DELETE'); setTargets(t => t.filter(id => id !== a.id)); await refresh(); setNotice('Account disconnected.'); } })}><X size={17} /></button></div>)}{!p.available && <small className="cs-connection-setup">Connection setup is incomplete. Tap Connect to check again.</small>}<ConnectAccountButton platform={p} reconnect={accounts.some(a => a.platform === p.id)} disabled={Boolean(busy) || broadcastState !== 'idle'} active={active} onBusyChange={value => setBusy(value ? `connect-${p.id}` : '')} /></article>)}</div>{signedIn && <div className="cs-session"><span>Signed in as <strong>{user.name}</strong>{user.method ? ` with ${({ google: 'Google', telegram: 'Telegram', facebook: 'Facebook', instagram: 'Instagram', tiktok: 'TikTok' } as Record<string, string>)[user.method] || user.method}` : ''}</span><button className="cs-link-button" disabled={Boolean(busy) || broadcastState !== 'idle'} onClick={() => perform('logout', async () => { await creatorApi('/session/logout', 'POST', {}); sessionEpoch.current++; setUser(null); setAccounts([]); setPosts([]); setMediaLibrary([]); clearComposer(); })}><LogOut size={16} /> Sign out</button></div>}</section>}
      {tab === 'activity' && <section className="cs-panel cs-activity"><div className="cs-section-heading"><h2>Your publishing activity</h2><button className="cs-secondary" disabled={!signedIn || Boolean(busy)} onClick={() => perform('refresh', refresh)}>Refresh</button></div>{!posts.length ? <div className="cs-empty"><CalendarClock size={36} /><h3>Your next post starts here</h3><p>Drafts, scheduled posts and results will appear here.</p><button className="cs-primary" onClick={() => setTab('compose')}><Plus size={18} /> Create a post</button></div> : posts.map(post => <article className="cs-post-item" key={post._id}><div className="cs-section-heading"><strong>{post.title || post.caption?.slice(0, 65) || 'Media post'}</strong><span className={`cs-tag cs-state-${post.status}`}>{labels[post.status]}</span></div><p>{post.caption?.slice(0, 200)}</p><small>{post.scheduledAt ? new Date(post.scheduledAt).toLocaleString() : `Saved ${new Date(post.createdAt).toLocaleString()}`}</small>{post.deliveries?.map((d: any) => <div className="cs-delivery" key={d._id}><PlatformIcon platform={d.platform} color={platforms.find(p => p.id === d.platform)?.color} /><div><strong>{d.name}</strong><span>{labels[d.status]}{d.message && d.message !== 'Published' ? ` · ${d.message}` : ''}</span></div>{d.url && /^https:\/\//.test(d.url) && <a href={d.url} target="_blank" rel="noopener noreferrer" aria-label={`Open post on ${d.platform}`}><ArrowUpRight size={19} /></a>}{['failed', 'attention'].includes(d.status) && <button className="cs-link-button" disabled={Boolean(busy)} onClick={() => setConfirm({ title: 'Have you checked this platform?', text: 'Retry only if the content is not already published. A lost connection can leave a published post without a confirmation.', action: async () => { await creatorApi(`/posts/${post._id}/retry/${d._id}`, 'POST', { checkedPlatform: true }); await refresh(); } })}>Retry</button>}</div>)}<div className="cs-post-actions">{post.status === 'draft' && <><button className="cs-secondary" disabled={Boolean(busy)} onClick={() => perform('edit', () => editDraft(post))}>Edit draft</button><button className="cs-icon-button" aria-label="Delete draft" disabled={Boolean(busy)} onClick={() => setConfirm({ title: 'Delete this draft?', text: 'This removes the draft from Creator Studio. Your uploaded media stays in your media library.', action: async () => { await creatorApi(`/posts/${post._id}`, 'DELETE'); if (draftId === post._id) clearComposer(); await refresh(); } })}><Trash2 size={17} /></button></>}{['queued', 'scheduled'].includes(post.status) && post.deliveries.every((d: any) => d.status === 'queued') && <button className="cs-secondary" disabled={Boolean(busy)} onClick={() => perform('cancel', async () => { const updated = await creatorApi(`/posts/${post._id}/cancel`, 'POST', {}); await refresh(); await editDraft(updated); })}>Return to draft</button>}</div></article>)}</section>}
    </main>
    <footer className="cs-footer"><span>TONPLAYGRAM CREATOR STUDIO</span><Link to="/social">Open social hub <ArrowUpRight size={15} /></Link></footer>
    <dialog ref={dialog} className="cs-dialog" onCancel={() => setConfirm(null)}><h2>{confirm?.title}</h2><p>{confirm?.text}</p><div className="cs-composer-actions"><button className="cs-secondary" onClick={() => setConfirm(null)}>Cancel</button><button className="cs-primary" onClick={() => { const action = confirm?.action; setConfirm(null); if (action) void perform('confirm', action); }}>Confirm</button></div></dialog>
    <dialog ref={libraryDialog} className="cs-dialog cs-library" onCancel={() => setLibraryOpen(false)}><div className="cs-section-heading"><h2>Your media</h2><button className="cs-icon-button" aria-label="Close media" onClick={() => setLibraryOpen(false)}><X /></button></div><p className="cs-muted">Choose an upload, or remove files you no longer need.</p>{!mediaLibrary.length && <p>No uploads yet.</p>}{mediaLibrary.map(m => <div className="cs-library-item" key={m.id}><button disabled={!m.ready || Boolean(busy)} onClick={() => { setMedia(m); setLibraryOpen(false); }}>{m.ready && m.mime.startsWith('image/') ? <img src={m.url} alt="" /> : <FileText size={25} />}<span><strong>{m.name}</strong><small>{(m.size / 1024 ** 2).toFixed(1)} MB{!m.ready ? ' · Incomplete: select this file again to resume' : ''}</small></span></button><button className="cs-icon-button" disabled={Boolean(busy)} aria-label={`Delete ${m.name}`} onClick={() => { setLibraryOpen(false); setConfirm({ title: 'Delete this upload?', text: m.name, action: async () => { await creatorApi(`/media/${m.id}`, 'DELETE'); if (media?.id === m.id) setMedia(null); await refresh(); } }); }}><Trash2 size={17} /></button></div>)}</dialog>
  </div>;
}
