export type PoliceUnit={id:string;name:string;description:string;character:string;vehicle:string;weapon:string;armor:number};
export type PoliceStage={kind:string;anchor:string;title:string;actor:string|null;seconds:number};
export type PoliceMission={id:string;unit:string;title:string;description:string;site:string;steps:PoliceStage[];reward:number;requires:string|null;time:number};
export type PoliceRun={id:string;stage:number;elapsed:number;hold:number;status:string;failure:string;channel:boolean;arrested:boolean;rescued:boolean;boarded:boolean;snapshot:unknown};
export type PoliceProfile={version:number;unit:string;completed:string[];merit:number;best:Record<string,number>;active:PoliceRun|null;lastResult:null|{id:string;success:boolean;detail:string}};
export const POLICE_SAVE_KEY:string;
export const POLICE_UNITS:readonly PoliceUnit[];
export const POLICE_MISSIONS:readonly PoliceMission[];
export function freshPoliceProfile():PoliceProfile;
export function normalizePoliceProfile(raw:unknown):PoliceProfile;
export function policeMissionAvailable(profile:PoliceProfile,id:string):boolean;
export function beginPoliceMission(profile:PoliceProfile,id:string):PoliceProfile|null;
export function settlePoliceMission(profile:PoliceProfile):PoliceProfile|null;
