import {
  POOL_ROYALE_BASE_VARIANTS,
  POOL_ROYALE_DEFAULT_LOADOUT,
  POOL_ROYALE_DEFAULT_UNLOCKS,
  POOL_ROYALE_HDRI_VARIANTS,
  POOL_ROYALE_OPTION_LABELS,
  POOL_ROYALE_STORE_ITEMS
} from './poolRoyaleInventoryConfig.js';

export const BILARDO_SHQIP_BASE_VARIANTS = POOL_ROYALE_BASE_VARIANTS;
export const BILARDO_SHQIP_DEFAULT_LOADOUT = POOL_ROYALE_DEFAULT_LOADOUT;
export const BILARDO_SHQIP_DEFAULT_UNLOCKS = POOL_ROYALE_DEFAULT_UNLOCKS;
export const BILARDO_SHQIP_HDRI_VARIANTS = POOL_ROYALE_HDRI_VARIANTS;
export const BILARDO_SHQIP_OPTION_LABELS = POOL_ROYALE_OPTION_LABELS;
export const BILARDO_SHQIP_STORE_ITEMS = POOL_ROYALE_STORE_ITEMS;
