import { khronosThumb } from './storeThumbnails.js';

export const MURLAN_CHARACTER_THEMES = Object.freeze([
  {
    id: 'rpm-current',
    label: 'Current Avatar',
    source: 'three.js examples',
    license: 'MIT examples bundle',
    price: 0,
    description: 'Ready Player Me seated avatar with full PBR texture maps.',
    url: 'https://threejs.org/examples/models/gltf/readyplayer.me.glb',
    modelUrls: ['https://threejs.org/examples/models/gltf/readyplayer.me.glb'],
    thumbnail: khronosThumb('ReadyPlayerMe'),
    scale: 1.0,
    seatOffsetY: -0.84,
    seatOffsetZ: -0.22,
    normalizedSeatOffsetY: -0.4,
    normalizedSeatOffsetZ: 0.52,
    seatPitch: 0,
    seatYaw: 0,
    handLift: 1.04
  },
  {
    id: 'rpm-67d411',
    label: 'RPM 67d411',
    source: 'Ready Player Me public GLB',
    license: 'Check Ready Player Me terms',
    price: 390,
    description: 'Ready Player Me public avatar seated with the same Ludo rig logic and motion set.',
    url: 'https://models.readyplayer.me/67d411b30787acbf58ce58ac.glb',
    modelUrls: [
      'https://models.readyplayer.me/67d411b30787acbf58ce58ac.glb',
      'https://api.readyplayer.me/v1/avatars/67d411b30787acbf58ce58ac.glb',
      'https://avatars.readyplayer.me/67d411b30787acbf58ce58ac.glb'
    ],
    thumbnail: khronosThumb('ReadyPlayerMe67d411'),
    scale: 1.0,
    seatOffsetY: -0.84,
    seatOffsetZ: -0.22,
    normalizedSeatOffsetY: -0.4,
    normalizedSeatOffsetZ: 0.52,
    seatPitch: 0,
    seatYaw: 0,
    handLift: 1.04
  },
  {
    id: 'rpm-67f433',
    label: 'RPM 67f433',
    source: 'Ready Player Me public GLB',
    license: 'Check Ready Player Me terms',
    price: 420,
    description: 'Ready Player Me public avatar aligned to default seated scale/orientation for Ludo.',
    url: 'https://models.readyplayer.me/67f433b69dc08cf26d2cf585.glb',
    modelUrls: [
      'https://models.readyplayer.me/67f433b69dc08cf26d2cf585.glb',
      'https://api.readyplayer.me/v1/avatars/67f433b69dc08cf26d2cf585.glb',
      'https://avatars.readyplayer.me/67f433b69dc08cf26d2cf585.glb'
    ],
    thumbnail: khronosThumb('ReadyPlayerMe67f433'),
    scale: 1.0,
    seatOffsetY: -0.84,
    seatOffsetZ: -0.22,
    normalizedSeatOffsetY: -0.4,
    normalizedSeatOffsetZ: 0.52,
    seatPitch: 0,
    seatYaw: 0,
    handLift: 1.04
  },
  {
    id: 'rpm-67e1b5',
    label: 'RPM 67e1b5',
    source: 'Ready Player Me public GLB',
    license: 'Check Ready Player Me terms',
    price: 450,
    description: 'Ready Player Me public avatar using the same seated helper offsets and animation logic.',
    url: 'https://models.readyplayer.me/67e1b51ae11c93725e4395c9.glb',
    modelUrls: [
      'https://models.readyplayer.me/67e1b51ae11c93725e4395c9.glb',
      'https://api.readyplayer.me/v1/avatars/67e1b51ae11c93725e4395c9.glb',
      'https://avatars.readyplayer.me/67e1b51ae11c93725e4395c9.glb'
    ],
    thumbnail: khronosThumb('ReadyPlayerMe67e1b5'),
    scale: 1.0,
    seatOffsetY: -0.84,
    seatOffsetZ: -0.22,
    normalizedSeatOffsetY: -0.4,
    normalizedSeatOffsetZ: 0.52,
    seatPitch: 0,
    seatYaw: 0,
    handLift: 1.04
  },
  {
    id: 'webgl-vietnam-human',
    label: 'Vietnam Human',
    source: 'hmthanh/3d-human-model GitHub',
    license: 'Check repository license',
    price: 480,
    description: 'Open WebGL GLB humanoid seated with the same Ludo scale/orientation/motion rig.',
    url: 'https://raw.githubusercontent.com/hmthanh/3d-human-model/main/TranThiNgocTham.glb',
    thumbnail: khronosThumb('VietnamHuman'),
    scale: 1.0,
    seatOffsetY: -0.84,
    seatOffsetZ: -0.22,
    normalizedSeatOffsetY: -0.4,
    normalizedSeatOffsetZ: 0.52,
    seatPitch: 0,
    seatYaw: 0,
    handLift: 1.04
  },
  {
    id: 'webgl-ai-teacher',
    label: 'AI Teacher',
    source: 'Surbh77/AI-teacher GitHub',
    license: 'Check repository license',
    price: 510,
    description: 'Open-source AI Teacher avatar adapted to the default seated pose pipeline.',
    url: 'https://raw.githubusercontent.com/Surbh77/AI-teacher/main/avatar.glb',
    thumbnail: khronosThumb('AiTeacher'),
    scale: 1.0,
    seatOffsetY: -0.84,
    seatOffsetZ: -0.22,
    normalizedSeatOffsetY: -0.4,
    normalizedSeatOffsetZ: 0.52,
    seatPitch: 0,
    seatYaw: 0,
    handLift: 1.04
  },
  {
    id: 'webgl-ai-teacher-1',
    label: 'AI Teacher 1',
    source: 'Surbh77/AI-teacher GitHub',
    license: 'Check repository license',
    price: 540,
    description: 'Second AI Teacher avatar using the same seated helpers and interaction logic.',
    url: 'https://raw.githubusercontent.com/Surbh77/AI-teacher/main/avatar1.glb',
    thumbnail: khronosThumb('AiTeacher1'),
    scale: 1.0,
    seatOffsetY: -0.84,
    seatOffsetZ: -0.22,
    normalizedSeatOffsetY: -0.4,
    normalizedSeatOffsetZ: 0.52,
    seatPitch: 0,
    seatYaw: 0,
    handLift: 1.04
  }
]);
