import {
  BATTLE_ROYALE_SHARED_CHAIR_THEME_OPTIONS,
  BATTLE_ROYALE_SHARED_TABLE_THEME_OPTIONS
} from './battleRoyaleSharedInventory.js';

export const TEXAS_CHAIR_THEME_OPTIONS = Object.freeze(BATTLE_ROYALE_SHARED_CHAIR_THEME_OPTIONS);
export const TEXAS_TABLE_THEME_OPTIONS = Object.freeze(BATTLE_ROYALE_SHARED_TABLE_THEME_OPTIONS);
export const TEXAS_CHAIR_COLOR_OPTIONS = TEXAS_CHAIR_THEME_OPTIONS;
