import { SHARED_ARENA_CHAIR_THEMES, SHARED_ARENA_TABLE_THEMES } from './sharedArenaAssetCatalog.js';

export const TEXAS_CHAIR_THEME_OPTIONS = Object.freeze(SHARED_ARENA_CHAIR_THEMES);
export const TEXAS_TABLE_THEME_OPTIONS = Object.freeze(SHARED_ARENA_TABLE_THEMES);
export const TEXAS_CHAIR_COLOR_OPTIONS = TEXAS_CHAIR_THEME_OPTIONS;
