import { MURLAN_STOOL_THEMES, MURLAN_TABLE_THEMES } from './murlanThemes.js';

export const TEXAS_CHAIR_THEME_OPTIONS = Object.freeze(MURLAN_STOOL_THEMES);
export const TEXAS_TABLE_THEME_OPTIONS = Object.freeze(MURLAN_TABLE_THEMES);
export const TEXAS_CHAIR_COLOR_OPTIONS = TEXAS_CHAIR_THEME_OPTIONS;
