/** Dated visual references, NOT measured facade surveys. Colors, bay spacing and
 * ornament depth are authored interpretations; source footprints are preserved. */
import { LANDMARK_PROFILES } from './landmarkCatalog.mjs';
import {NEIGHBOURHOOD_REFERENCE_PROFILES} from './neighbourhoodProfiles.mjs';
export const REFERENCE_BUILDINGS = Object.freeze({
  ...LANDMARK_PROFILES,
  ...NEIGHBOURHOOD_REFERENCE_PROFILES,
  '470567580': {name:'Ambasada e Zvicrës',style:'swiss',color:0xe2dfcd,trim:0xc6c4b7,
    floor:4.5,window:1.15,photo:null,date:'2015 filename; capture date unverified',
    source:'https://www.eda.admin.ch/countries/albania/en/home/representations/embassy-tirana.html',
    credit:'© EDA / Holger Tausch · reference only; image not redistributed',features:'Two levels, pale vertical ribbed cladding, tall windows with diagonal grilles; shallow roof edge.'},
  '562091538': {name:'Shkolla 9-vjeçare Kosova',style:'kosova',color:0xa96543,trim:0x3c4547,
    floor:3.2,window:1.35,height:9.6,photo:null,date:'2018-09-18 publication',
    source:'https://tirana.al/artikull/rilind-shkolla-kosova',
    credit:'Bashkia Tiranë · reference only; image not redistributed',features:'Red brick, dark frames, tall upper bays and smaller classroom windows. Three above-ground floors + basement per city; metric height estimated.'},
  '410277122': {name:'Universiteti i Arteve',style:'arts',color:0xdcd8cd,trim:0xebe7dc,
    floor:3.2,window:1.35,flagCountry:'AL',photo:'university-arts-2017.jpg',date:'2017-12-03',
    source:'https://commons.wikimedia.org/wiki/File:Akademia_e_arteve_Ergys_Veliu_Photography.jpg',
    credit:'Ergys Veliu · CC BY-SA 4.0',features:'Pale stone, green shutters, blank central upper wall, recessed portico with rectangular piers. Night photo affects color.'},
  '175108137': {name:'Bashkia Tiranë',style:'city-hall',color:0xe0b34e,trim:0xe8dfc2,
    floor:3.2,window:1.25,photo:'city-hall-2018.jpg',date:'2018-09-21',
    source:'https://commons.wikimedia.org/wiki/File:Tirana_-_Bashkia_e_Tiran%C3%ABs_(2018).jpg',
    credit:'Sebleouf · CC BY-SA 4.0',features:'Yellow wall panels, red brick divisions, cream cornices, green shutters.'},
  '236566880': {name:'Banka e Shqipërisë',style:'bank',color:0x9b6049,trim:0xdfddd0,
    floor:4.2,window:1.5,photo:'bank-albania-2017.jpg',date:'2017-12-02',
    source:'https://commons.wikimedia.org/wiki/File:Banka_e_Shqip%C3%ABris%C3%AB_2017_01.jpg',
    credit:'Liridon · CC BY-SA 4.0',features:'Curved brick frontage, four pale portico piers, metal grilles.'},
  '1249637844': {name:'Pallati i Kulturës',style:'culture',color:0xb29c8d,trim:0xe1dbca,
    floor:4.6,window:2.2,height:18,photo:'culture-palace-2014.jpg',date:'2014-04-17',
    source:'https://commons.wikimedia.org/wiki/File:Palacio_de_Cultura,_Tirana,_Albania,_2014-04-17,_DD_11.JPG',
    credit:'Diego Delso · CC BY-SA 3.0',features:'Pale continuous fascia and full-height square colonnade; recessed reddish panels.'},
  '236566876': {name:'Tirana International Hotel',style:'hotel',color:0xe1ded1,trim:0xf0ecdf,
    floor:3.1,window:1.8,photo:'tirana-international-2015.jpg',date:'2015-12-06',
    source:'https://commons.wikimedia.org/wiki/File:Tirana_International_Hotel_(front).JPG',
    credit:'Leeturtle / Andis Rado · CC0 1.0',features:'Cream horizontal spandrels, blue glazing, roof nameboard and entrance canopy.'},
  '249185545': {name:'Rogner Hotel Tirana',style:'rogner',color:0xe0d9c9,trim:0xede8dc,
    floor:3.2,window:1.35,photo:'rogner-2019.jpg',date:'2019-08-19',
    source:'https://commons.wikimedia.org/wiki/File:Rogner_Hotel,_Tirana_(49600188791).jpg',
    credit:'Andrew Milligan sumo · CC BY 2.0',features:'Curved frontage, repeated framed windows, narrow balcony rails. Color remains estimated (monochrome reference).'},
  '361451879': {name:'Drejtoria e Policisë Tiranë',style:'police',color:0x9ca9af,trim:0xeff0e9,
    floor:3.2,window:1.45,photo:null,date:'2019-03-12 (article; capture unknown)',
    source:'https://joq-albania.com/artikull/533518.html',
    credit:'Reference only; photograph not redistributed',features:'Gray walls, white quoins and cornices, blue police lettering. Connecting bridge is not surveyed.'},
  '236569963': {name:'Taivani · Regency Casino',style:'taivani',color:0xd8d9cf,trim:0xf1eee3,
    floor:3.2,window:2.1,photo:'taivani-2014.jpg',date:'2014-07-12',
    source:'https://commons.wikimedia.org/wiki/File:Taiwan_center_in_Tirana.JPG',
    credit:'Avi1111 / Dr. Avishai Teicher · CC BY-SA 4.0',features:'Low terraces, white curved ribbons, dark glazing and faceted glass cupola.'}
});
