import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { Bell, CalendarDays, ChevronLeft, ChevronRight, CircleUserRound, ClipboardCheck, Clock3, Download, FileText, Flag, HeartHandshake, Home, Info, LayoutDashboard, Map, MapPin, Megaphone, Menu, MessageCircle, Plus, Search, ShieldCheck, Siren, Users, X } from 'lucide-react';
import { documents, groups, locations, protests, tasks, updates } from './mock';
import { useFlamingoStore } from './store';
import type { LiveUpdate, Protest, Task } from './types';
import './flamingo.css';

const badgeClass = (value: string) => `fr-badge ${['LIVE','URGJENTE','Lartë'].includes(value) ? 'danger' : value === 'INFO' ? 'muted' : ''}`;

function TopBar({ title, back=false, action }: { title?:string; back?:boolean; action?:ReactNode }) {
  const navigate=useNavigate();
  return <header className="fr-top"><div className="fr-top-inner">{back ? <button className="fr-icon" onClick={()=>navigate(-1)} aria-label="Kthehu"><ChevronLeft/></button> : <Link to="/flamingo" className="fr-brand"><span className="fr-mark">F</span><span>{title || 'Flamingo Revolution'}</span></Link>} {back && <strong>{title}</strong>}<div className="fr-top-action">{action ?? <Link className="fr-icon" to="/flamingo/live" aria-label="Njoftimet live"><Bell/><i/></Link>}</div></div></header>
}
function BottomNavigation(){ const items=[['/flamingo',Home,'Kreu'],['/flamingo/protests',Megaphone,'Protestat'],['/flamingo/groups',Users,'Grupet'],['/flamingo/map',Map,'Harta'],['/flamingo/profile',CircleUserRound,'Profili']] as const; return <nav className="fr-nav" aria-label="Navigimi kryesor">{items.map(([to,Icon,label])=><NavLink key={to} to={to} end={to==='/flamingo'}><Icon/><span>{label}</span></NavLink>)}</nav> }
function Shell({children, title, back=false, noNav=false}:{children:ReactNode;title?:string;back?:boolean;noNav?:boolean}){return <div className="flamingo"><TopBar title={title} back={back}/><main className="fr-main">{children}</main>{!noNav&&<BottomNavigation/>}<ReportButton/><Toast/></div>}
function Toast(){const {toast,clearToast}=useFlamingoStore(); useEffect(()=>{if(!toast)return; const t=setTimeout(clearToast,2600);return()=>clearTimeout(t)},[toast,clearToast]); return toast?<div className="fr-toast"><ShieldCheck/>{toast}</div>:null}
function ReportButton(){return <Link to="/flamingo/report" className="fr-report"><Flag/>Raporto</Link>}
function SectionTitle({children,link}:{children:ReactNode;link?:string}){return <div className="fr-section-title"><h2>{children}</h2>{link&&<Link to={link}>Shiko të gjitha <ChevronRight/></Link>}</div>}
function StatusCard(){return <section className="fr-status"><div className="fr-eyebrow"><span>STATUSI TANI</span><span className="fr-live"><i/> LIVE</span></div><h1>Protesta në Tiranë</h1><div className="fr-place"><MapPin/>Sheshi Skënderbej</div><div className="fr-date"><CalendarDays/>Sot • 18:00</div><div className="fr-status-copy"><strong>Tubimi është duke vazhduar.</strong><p>Fjalimi kryesor fillon në 20:30.</p><small><Clock3/> Përditësuar 2 minuta më parë</small></div><div className="fr-actions"><Link className="fr-primary" to="/flamingo/live">Shiko Live</Link><Link className="fr-secondary" to="/flamingo/map">Shiko Hartën</Link></div></section>}
function UpdateCard({item}: {item:LiveUpdate}){return <article className={`fr-update ${item.type==='URGJENTE'?'urgent':''}`}><time>{item.time}</time><div><div className="fr-update-meta"><span className={badgeClass(item.type)}>{item.type}</span><span>{item.author}</span></div><p>{item.text}</p></div></article>}
function HomePage(){return <Shell><div className="fr-hero-note"><span><HeartHandshake/></span><div><strong>Koordinohemi. Informohemi. Veprojmë paqësisht.</strong><p>Platformë qytetare privacy-first për Shqipërinë.</p></div></div><StatusCard/><SectionTitle link="/flamingo/live">Njoftimet e fundit</SectionTitle><div className="fr-list">{updates.slice(0,3).map(x=><UpdateCard key={x.id} item={x}/>)}</div><section className="fr-safety"><ShieldCheck/><div><strong>Privatësia jote ka rëndësi</strong><p>Nuk publikojmë vendndodhje individuale apo lista pjesëmarrësish.</p></div></section></Shell>}
function EventCard({event}:{event:Protest}){return <Link to={`/flamingo/protests/${event.id}`} className="fr-card fr-event"><div className="fr-card-top"><span className={badgeClass(event.status)}>{event.status}</span><span className="fr-count"><Users/>{event.participants.toLocaleString('sq-AL')}</span></div><h3>{event.title}</h3><p><MapPin/>{event.city} • {event.place}</p><p><CalendarDays/>{event.date} • {event.time}</p><footer><span>{event.organizer}</span><ChevronRight/></footer></Link>}
function ProtestsPage(){return <Shell title="Protestat"><div className="fr-search"><Search/><input aria-label="Kërko protesta" placeholder="Kërko sipas qytetit..."/></div><SectionTitle>Aktive tani</SectionTitle>{protests.filter(x=>x.status==='LIVE').map(x=><EventCard key={x.id} event={x}/>)}<SectionTitle>Të ardhshme</SectionTitle><div className="fr-list">{protests.filter(x=>x.status==='E ARDHSHME').map(x=><EventCard key={x.id} event={x}/>)}</div><SectionTitle>Të përfunduara</SectionTitle>{protests.filter(x=>x.status==='PËRFUNDUAR').map(x=><EventCard key={x.id} event={x}/>)}</Shell>}
function ProtestDetail(){const {id}=useParams(); const event=protests.find(x=>x.id===id)||protests[0]; const [tab,setTab]=useState('Përmbledhje'); const {joined,joinProtest}=useFlamingoStore(); const tabs=['Përmbledhje','Programi','Njoftime','Grupet','Dokumente']; return <Shell title="Detajet e protestës" back><div className="fr-detail-head"><span className={badgeClass(event.status)}>{event.status}</span><h1>{event.title}</h1><p><CalendarDays/>{event.date} • {event.time}</p><p><MapPin/>{event.place}, {event.city}</p></div><div className="fr-tabs">{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==='Përmbledhje'&&<div className="fr-stack"><section className="fr-panel"><h2>Rreth tubimit</h2><p>{event.description}</p></section><section className="fr-panel"><h2>Qëllimet & kërkesat</h2><ul><li>Transparencë e plotë institucionale</li><li>Konsultim real me qytetarët</li><li>Llogaridhënie dhe zbatim i ligjit</li></ul></section><section className="fr-panel"><h2>Informacion praktik</h2><p>Ejani në këmbë ose me transport publik. Mbani ujë dhe ndiqni udhëzimet e koordinatorëve.</p></section></div>}{tab==='Programi'&&<div className="fr-panel fr-program"><p><time>18:00</time> Hapja e sheshit</p><p><time>20:30</time> Fjalimi kryesor</p><p><time>21:30</time> Mbyllja paqësore</p></div>}{tab==='Njoftime'&&updates.map(x=><UpdateCard key={x.id} item={x}/>)}{tab==='Grupet'&&groups.slice(0,3).map(x=><GroupCard key={x.id} group={x}/>)}{tab==='Dokumente'&&documents.map(x=><DocumentCard key={x.id} doc={x}/>)}<button className="fr-sticky-cta" disabled={joined.includes(event.id)} onClick={()=>joinProtest(event.id)}>{joined.includes(event.id)?'Je bashkuar ✓':'Bashkohu'}</button></Shell>}
function GroupCard({group}:{group:(typeof groups)[number]}){return <Link to={`/flamingo/groups/${group.id}`} className="fr-card fr-group"><div className="fr-group-icon"><Users/></div><div><h3>{group.name}</h3><p>{group.description}</p><small>{group.members} anëtarë • {group.tasks} detyra aktive</small></div><ChevronRight/></Link>}
function GroupsPage(){return <Shell title="Grupet"><p className="fr-lead">Gjej grupin ku mund të kontribuosh.</p><div className="fr-list">{groups.map(x=><GroupCard key={x.id} group={x}/>)}</div><Link className="fr-wide-link" to="/flamingo/tasks"><ClipboardCheck/>Shiko të gjitha detyrat<ChevronRight/></Link></Shell>}
function GroupDetail(){const {id}=useParams(); const group=groups.find(x=>x.id===id)||groups[0]; const [tab,setTab]=useState('Diskutim'); const {joinedGroups,joinGroup}=useFlamingoStore(); return <Shell title={group.name} back><div className="fr-detail-head"><div className="fr-group-icon"><Users/></div><h1>{group.name}</h1><p>{group.description}</p><small>Admin: {group.admin} • {group.members} anëtarë</small></div><div className="fr-tabs compact">{['Diskutim','Detyra','Anëtarë'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==='Diskutim'&&<div className="fr-channel"><div className="fr-pinned"><Megaphone/> <span><b>Mesazh i fiksuar</b> Takimi i ekipit është në 17:00 te pika e informacionit.</span></div><div className="fr-message"><b>Elira <em>ADMIN</em></b><time>16:24</time><p>Ju lutem konfirmoni detyrat para se të niseni për në shesh.</p></div><div className="fr-message"><b>Ardi</b><time>16:31</time><p>Materialet e pikës A janë gati.</p></div><div className="fr-compose"><Plus/><input placeholder="Shkruaj në kanal..."/><button aria-label="Dërgo"><ChevronRight/></button></div></div>}{tab==='Detyra'&&tasks.filter(x=>x.group.includes(group.name.split(' ')[0])).map(x=><TaskCard key={x.id} task={x}/>)}{tab==='Anëtarë'&&<div className="fr-panel"><h2>Anëtarësia është private</h2><p>Vetëm administratorët e grupit mund të shohin listën e plotë.</p></div>}<button className="fr-sticky-cta" disabled={joinedGroups.includes(group.id)} onClick={()=>joinGroup(group.id)}>{joinedGroups.includes(group.id)?'Anëtar i grupit ✓':'Bashkohu në grup'}</button></Shell>}
function TaskCard({task}:{task:Task}){const {acceptedTasks,acceptTask}=useFlamingoStore();return <article className="fr-card fr-task"><div className="fr-card-top"><span className={badgeClass(task.status)}>{task.status}</span><span>{task.priority}</span></div><h3>{task.title}</h3><p>{task.description}</p><div className="fr-task-meta"><span><Users/>{task.people} persona</span><span><Clock3/>{task.deadline}</span></div><button disabled={acceptedTasks.includes(task.id)} onClick={()=>acceptTask(task.id)}>{acceptedTasks.includes(task.id)?'E more detyrën ✓':'Marr këtë detyrë'}</button></article>}
function TasksPage(){return <Shell title="Detyrat" back><div className="fr-filter-row"><button className="active">Të gjitha</button><button>Hapur</button><button>Në proces</button></div><div className="fr-list">{tasks.map(x=><TaskCard key={x.id} task={x}/>)}</div></Shell>}
function MapPage(){const [filter,setFilter]=useState('Të gjitha');const [selected,setSelected]=useState<(typeof locations)[number]|null>(null);const shown=locations.filter(x=>filter==='Të gjitha'||x.type===filter);return <Shell title="Harta"><p className="fr-map-note"><ShieldCheck/>Harta shfaq vetëm pika publike organizative.</p><div className="fr-map-filters">{['Të gjitha','Takim','Ndihmë','Informacion','Transport'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="fr-map" role="img" aria-label="Hartë e pikave publike në Sheshin Skënderbej"><span className="road r1"/><span className="road r2"/><span className="plaza">SHESHI<br/>SKËNDERBEJ</span>{shown.map((x,i)=><button aria-label={x.name} className={`fr-pin pin-${i}`} style={{left:`${x.x}%`,top:`${x.y}%`}} onClick={()=>setSelected(x)} key={x.id}>{x.type==='Ndihmë'?<Siren/>:x.type==='Transport'?<Map/>:x.type==='Informacion'?<Info/>:<MapPin/>}</button>)}</div><div className="fr-map-legend"><span><i/>Pika aktive</span><span><i/>Zgjidh një marker</span></div>{selected&&<div className="fr-sheet"><div className="fr-sheet-handle"/><button className="fr-sheet-close" onClick={()=>setSelected(null)}><X/></button><span className="fr-badge">{selected.type}</span><h2>{selected.name}</h2><p>{selected.description}</p><div><strong>Statusi</strong><span>{selected.status}</span></div><div><strong>Orari</strong><span>{selected.hours}</span></div></div>}</Shell>}
function LivePage(){return <Shell title="Përditësime Live" back><div className="fr-live-head"><span className="fr-live"><i/> LIVE</span><h1>Tiranë</h1><p>Përditësime të verifikuara nga organizatorët.</p></div><div className="fr-timeline">{[...updates].sort(a=>a.type==='URGJENTE'?-1:1).map(x=><UpdateCard key={x.id} item={x}/>)}</div></Shell>}
function DocumentCard({doc}:{doc:(typeof documents)[number]}){return <article className="fr-card fr-doc"><div className="fr-doc-icon"><FileText/></div><div><span>{doc.category}</span><h3>{doc.title}</h3><small>{doc.date} • {doc.author}</small></div><button aria-label="Shkarko dokumentin"><Download/></button></article>}
function DocumentsPage(){return <Shell title="Dokumente & Informacion" back><div className="fr-list">{documents.map(x=><DocumentCard key={x.id} doc={x}/>)}</div></Shell>}
function ProfilePage(){return <Shell title="Profili"><div className="fr-profile"><div className="fr-avatar">AM</div><h1>Arta M.</h1><span className="fr-badge">VULLNETAR</span><p>Të dhënat e kontaktit nuk shfaqen publikisht.</p></div><div className="fr-menu">{[[Users,'Grupet e mia','2'],[ClipboardCheck,'Detyrat e mia','1'],[Megaphone,'Protestat ku jam bashkuar','1'],[Bell,'Njoftimet','3'],[FileText,'Dokumentet',''],[LayoutDashboard,'Paneli i organizatorit','']].map(([Icon,label,count],i)=><Link key={String(label)} to={i===4?'/flamingo/documents':i===5?'/flamingo/admin':'#'}><Icon/><span>{label as string}</span>{count&&<b>{count as string}</b>}<ChevronRight/></Link>)}</div><section className="fr-safety"><ShieldCheck/><div><strong>Privacy-first</strong><p>Vendndodhja, telefoni dhe email-i yt nuk publikohen.</p></div></section></Shell>}
function ReportPage(){const nav=useNavigate();const notify=useFlamingoStore(s=>s.notify);const [category,setCategory]=useState('Problem organizativ');function submit(e:FormEvent){e.preventDefault();notify('Raporti iu dërgua moderatorëve për shqyrtim.');nav('/flamingo')}return <Shell title="Raporto problem" back noNav><div className="fr-alert"><ShieldCheck/><p><strong>Raporti nuk publikohet automatikisht.</strong><br/>Moderatorët e shqyrtojnë para çdo veprimi.</p></div><form className="fr-form" onSubmit={submit}><label>Kategoria<select value={category} onChange={e=>setCategory(e.target.value)}>{['Nevojë mjekësore','Person i humbur','Problem organizativ','Objekt i humbur','Informacion i gabuar','Tjetër'].map(x=><option key={x}>{x}</option>)}</select></label><label>Përshkrimi<textarea required minLength={10} placeholder="Shpjego shkurt çfarë ka ndodhur..."/></label><label>Vendndodhja <small>(opsionale)</small><input placeholder="P.sh. hyrja veriore"/></label><label className="fr-upload">Foto <small>(opsionale)</small><input type="file" accept="image/*"/><span><Plus/>Shto foto</span></label><button className="fr-primary" type="submit">Dërgo për shqyrtim</button><p className="fr-rate">Për siguri, raportimet kanë kufizim të përkohshëm kundër abuzimit.</p></form></Shell>}
function AdminPage(){const notify=useFlamingoStore(s=>s.notify);return <Shell title="Paneli i organizatorit" back><div className="fr-admin-head"><span className="fr-badge">ORGANIZATOR</span><h1>Mirë se erdhe, Arta</h1><p>Menaxho aktivitetin dhe njoftimet zyrtare.</p></div><div className="fr-stats">{[['1','Protestë aktive'],['5','Grupe aktive'],['8','Detyra të hapura'],['3','Raporte në pritje']].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div><SectionTitle>Veprime të shpejta</SectionTitle><div className="fr-quick">{['Krijo protestë','Publiko njoftim','Krijo grup','Krijo detyrë','Shto pikë në hartë'].map(x=><button onClick={()=>notify(`${x}: formulari u hap në modalitet demonstrues.`)} key={x}><Plus/>{x}</button>)}</div><SectionTitle>Moderimi</SectionTitle><div className="fr-card fr-moderation"><div><span className="fr-badge muted">NË PRITJE</span><h3>Problem organizativ</h3><p>Sinjalistika te hyrja veriore nuk duket qartë.</p><small>Dërguar 8 minuta më parë • Vendndodhja e fshehur</small></div><div className="fr-actions"><button onClick={()=>notify('Raporti u shënua si i verifikuar.')}>Verifiko</button><button className="fr-secondary" onClick={()=>notify('Raporti u arkivua.')}>Arkivo</button></div></div></Shell>}

export default function FlamingoApp(){return <Routes><Route index element={<HomePage/>}/><Route path="protests" element={<ProtestsPage/>}/><Route path="protests/:id" element={<ProtestDetail/>}/><Route path="groups" element={<GroupsPage/>}/><Route path="groups/:id" element={<GroupDetail/>}/><Route path="tasks" element={<TasksPage/>}/><Route path="map" element={<MapPage/>}/><Route path="live" element={<LivePage/>}/><Route path="documents" element={<DocumentsPage/>}/><Route path="profile" element={<ProfilePage/>}/><Route path="report" element={<ReportPage/>}/><Route path="admin" element={<AdminPage/>}/></Routes>}
