import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AlbaniaCanvasRenderer, AlbaniaRenderer, type CameraMode } from './renderer';
import { TruckAudio } from './audio';
import { CITIES, ROADS, cityById, pathBetween } from './world';
import {
  acceptJob, advanceTruck, defaultState, jobsFrom, neutralControls,
  remainingDistance, serviceTruck, type Controls, type Job, type TruckState
} from './simulation';
import './explore-albania.css';

type View='home'|'jobs'|'drive'|'garage'|'map';
const STORAGE='tonplaygram.explore-albania.career.v1';
const safeLoad=():TruckState=>{try{const raw=localStorage.getItem(STORAGE);if(!raw)return defaultState();const value=JSON.parse(raw);return {...defaultState(),...value,activeJob:value.activeJob||null,paused:false};}catch{return defaultState();}};
const formatClock=(hours:number)=>`${String(Math.floor(hours)%24).padStart(2,'0')}:${String(Math.floor(hours*60)%60).padStart(2,'0')}`;
const money=(value:number)=>`Lek ${Math.round(value).toLocaleString()}`;

function MiniMap({state,big=false}:{state:TruckState;big?:boolean}){
  const all=[...CITIES.map(c=>({x:c.x,z:c.z})),...ROADS.flatMap(r=>r.points)],xs=all.map(p=>p.x),zs=all.map(p=>p.z),minX=Math.min(...xs)-18,maxX=Math.max(...xs)+18,minZ=Math.min(...zs)-18,maxZ=Math.max(...zs)+18;
  const p=(x:number,z:number)=>`${((x-minX)/(maxX-minX))*100},${100-((z-minZ)/(maxZ-minZ))*100}`;
  const active=state.activeJob?pathBetween(state.activeJob.from,state.activeJob.to):[];
  return <svg className={big?'ea-map ea-map-big':'ea-map'} viewBox="0 0 100 100" role="img" aria-label="Albania road map and truck position">
    {ROADS.map(r=><polyline key={r.id} points={r.points.map(q=>p(q.x,q.z)).join(' ')} />)}
    {active.length>1&&<polyline className="ea-route" points={active.map(q=>p(q.x,q.z)).join(' ')}/>}
    {CITIES.map(c=><g key={c.id}><circle cx={p(c.x,c.z).split(',')[0]} cy={p(c.x,c.z).split(',')[1]} r={big?1.4:1.7}/>{big&&<text x={Number(p(c.x,c.z).split(',')[0])+2} y={p(c.x,c.z).split(',')[1]}>{c.name}</text>}</g>)}
    <circle className="ea-truck-dot" cx={p(state.x,state.z).split(',')[0]} cy={p(state.x,state.z).split(',')[1]} r={big?2:3}/>
  </svg>;
}

export default function ExploreAlbania({onExit,inline=false}:{onExit?:()=>void;inline?:boolean}){
  const [view,setView]=useState<View>('home'),[state,setState]=useState<TruckState>(safeLoad),[camera,setCamera]=useState<CameraMode>('chase'),[muted,setMuted]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[compat,setCompat]=useState(false);
  const host=useRef<HTMLDivElement>(null),renderer=useRef<AlbaniaRenderer|AlbaniaCanvasRenderer|null>(null),audio=useRef(new TruckAudio()),stateRef=useRef(state),input=useRef<Controls>(neutralControls()),last=useRef(0),saveAt=useRef(0);
  stateRef.current=state;
  const jobs=useMemo(()=>jobsFrom(state.currentCity,Math.floor(state.time/24)+state.delivered),[state.currentCity,state.delivered]);
  useEffect(()=>{if(!host.current)return;try{renderer.current=new AlbaniaRenderer(host.current);setLoaded(true);}catch{try{renderer.current=new AlbaniaCanvasRenderer(host.current);setCompat(true);setLoaded(true);}catch(e){setError(`Graphics unavailable: ${(e as Error).message}`);}}return()=>renderer.current?.dispose();},[]);
  useEffect(()=>{const down=(e:KeyboardEvent)=>{const key=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown'].includes(key))e.preventDefault();if(e.repeat)return;if(key==='arrowleft'||key==='a')input.current.steer=-1;if(key==='arrowright'||key==='d')input.current.steer=1;if(key==='arrowup'||key==='w')input.current.throttle=1;if(key==='arrowdown'||key==='s')input.current.brake=1;},up=(e:KeyboardEvent)=>{const key=e.key.toLowerCase();if(['arrowleft','arrowright','a','d'].includes(key))input.current.steer=0;if(['arrowup','w'].includes(key))input.current.throttle=0;if(['arrowdown','s'].includes(key))input.current.brake=0;},reset=()=>{input.current=neutralControls();};addEventListener('keydown',down);addEventListener('keyup',up);addEventListener('blur',reset);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up);removeEventListener('blur',reset);};},[]);
  useEffect(()=>{let frame=0;const tick=(now:number)=>{const s=stateRef.current,dt=last.current?Math.min(.2,(now-last.current)/1000):0;last.current=now;if(view==='drive'&&!s.paused){for(let left=dt;left>0;left-=.05)advanceTruck(s,input.current,Math.min(.05,left));if(now-saveAt.current>3000){saveAt.current=now;try{localStorage.setItem(STORAGE,JSON.stringify(s));}catch{}}setState({...s});}renderer.current?.draw(s,camera);audio.current.update(s,view==='drive'&&!s.paused);frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[camera,view]);
  useEffect(()=>{const pause=()=>{if(document.hidden&&view==='drive'){stateRef.current.paused=true;setState({...stateRef.current});input.current=neutralControls();}};document.addEventListener('visibilitychange',pause);return()=>document.removeEventListener('visibilitychange',pause);},[view]);
  useEffect(()=>()=>audio.current.destroy(),[]);
  const press=(key:keyof Controls,value:number)=>({onPointerDown:(e:React.PointerEvent)=>{e.currentTarget.setPointerCapture(e.pointerId);input.current[key]=value;audio.current.unlock();},onPointerUp:()=>input.current[key]=0,onPointerCancel:()=>input.current[key]=0,onLostPointerCapture:()=>input.current[key]=0});
  const chooseJob=(job:Job)=>{const s=stateRef.current;if(acceptJob(s,job)){setState({...s});setView('drive');audio.current.unlock();audio.current.beep(660);}};
  const city=cityById(state.currentCity),destination=state.activeJob?cityById(state.activeJob.to):null,speed=Math.round(Math.abs(state.speed)*3.6),notice=state.notice&&state.noticeUntil>state.time;
  return <div className={`ea-game ${inline?'ea-inline':''}`}>
    <div ref={host} className="ea-scene"/><div className="ea-grade"/>
    <header className="ea-header"><button onClick={()=>view==='home'?onExit?.():setView('home')} className="ea-brand"><b>EXPLORE</b><span>ALBANIA</span></button><div className="ea-header-actions"><span>{money(state.money)}</span><button aria-label={muted?'Enable sound':'Mute sound'} onClick={()=>{audio.current.unlock();audio.current.setMuted(!muted);setMuted(!muted);}}>{muted?'MUTED':'SOUND'}</button></div></header>
    {view==='home'&&<main className="ea-home"><div className="ea-kicker">OPEN ROAD · ALBANIA</div><h1>Drive the<br/><em>whole country.</em></h1><p>Build a haulage career from Shkodër to Sarandë.</p><button className="ea-primary" disabled={!loaded} onClick={()=>{audio.current.unlock();setView(state.activeJob?'drive':'jobs');}}>{state.activeJob?'CONTINUE DELIVERY':'FIND A JOB'} <span>→</span></button><div className="ea-home-grid"><button onClick={()=>setView('map')}>Albania map<small>12 cities</small></button><button onClick={()=>setView('garage')}>Truck service<small>{Math.round(state.damage)}% damage</small></button></div><button className="ea-free" onClick={()=>{audio.current.unlock();setView('drive');}}>Free drive from {city.name}</button></main>}
    {view==='jobs'&&<section className="ea-panel"><button className="ea-back" onClick={()=>setView('home')}>← Garage</button><div className="ea-kicker">FREIGHT MARKET · {city.name.toUpperCase()}</div><h2>Choose your next haul</h2><div className="ea-job-list">{jobs.map(job=><button key={job.id} onClick={()=>chooseJob(job)}><span className="ea-cargo">{job.cargo}{job.fragile&&<i>FRAGILE</i>}</span><b>{cityById(job.from).name} → {cityById(job.to).name}</b><small>{job.tonnes} t · {job.distance} km</small><strong>{money(job.payout)}</strong></button>)}</div></section>}
    {view==='garage'&&<section className="ea-panel"><button className="ea-back" onClick={()=>setView('home')}>← Garage</button><div className="ea-kicker">SERVICE STATION · {city.name.toUpperCase()}</div><h2>Keep the rig earning</h2><div className="ea-service"><div><span>Fuel</span><b>{state.fuel.toFixed(0)}%</b></div><button onClick={()=>{serviceTruck(stateRef.current,'fuel');setState({...stateRef.current});}}>Fill tank</button><div><span>Damage</span><b>{state.damage.toFixed(0)}%</b></div><button onClick={()=>{serviceTruck(stateRef.current,'repair');setState({...stateRef.current});}}>Repair truck</button></div><div className="ea-stats"><span>Level <b>{state.level}</b></span><span>Deliveries <b>{state.delivered}</b></span><span>Distance <b>{state.odometer.toFixed(0)} km</b></span></div></section>}
    {view==='map'&&<section className="ea-panel ea-map-panel"><button className="ea-back" onClick={()=>setView('home')}>← Garage</button><div className="ea-kicker">ROAD NETWORK</div><h2>Explore Albania</h2><MiniMap state={state} big/><p>Major freight corridors and twelve Albanian cities. Geography © OpenStreetMap contributors.</p></section>}
    {view==='drive'&&<div className="ea-drive-ui"><div className="ea-drive-top"><div><span>{destination?'DELIVER TO':'FREE DRIVE'}</span><b>{destination?.name||city.name}</b><small>{state.activeJob?`${remainingDistance(state)} km · ${state.activeJob.cargo}`:'Explore the road network'}</small></div><button aria-label={`Change camera; current view is ${camera}`} onClick={()=>setCamera(camera==='chase'?'cab':camera==='cab'?'cinematic':'chase')}>{camera.toUpperCase()}</button><button aria-label="Pause driving" onClick={()=>{stateRef.current.paused=true;setState({...stateRef.current});}}>Ⅱ</button></div><div className="ea-mini"><MiniMap state={state}/></div>{notice&&<div className="ea-notice" role="status">{state.notice}</div>}<div className="ea-dash"><div className="ea-gauge"><b>{speed}</b><span>km/h</span></div><div className="ea-meter"><span>FUEL {state.fuel.toFixed(0)}%</span><i><u style={{width:`${state.fuel}%`}}/></i><span>DAMAGE {state.damage.toFixed(0)}%</span><i><u className="damage" style={{width:`${state.damage}%`}}/></i></div><div className="ea-clock"><b>{formatClock(state.time)}</b><span>{state.rpm.toFixed(0)} rpm</span></div></div><div className="ea-controls"><div className="ea-steer"><button aria-label="Steer left" {...press('steer',-1)}>↶</button><button aria-label="Steer right" {...press('steer',1)}>↷</button></div><div className="ea-pedals"><button className="brake" {...press('brake',1)}>BRAKE</button><button className="gas" {...press('throttle',1)}>GAS</button></div></div><small className="ea-keyhint">WASD / arrows · Stop inside a destination depot to deliver</small></div>}
    {state.paused&&view==='drive'&&<div className="ea-modal"><section><div className="ea-kicker">ENGINE IDLING</div><h2>Route paused</h2><button className="ea-primary" onClick={()=>{stateRef.current.paused=false;setState({...stateRef.current});last.current=performance.now();}}>KEEP DRIVING <span>→</span></button><button className="ea-secondary" onClick={()=>{stateRef.current.paused=false;setState({...stateRef.current});setView('home');}}>Return to garage</button></section></div>}
    {error&&<div className="ea-error" role="alert">{error}</div>}
    {compat&&view==='home'&&<div className="ea-compat">Compatibility graphics active</div>}
  </div>;
}
