#!/usr/bin/env python3
"""Compile inspected OSM extracts. No invented footprints or filled campus bounds.
Usage: python scripts/import-tirana-landmarks.py REFERENCE_DIRECTORY
Inputs: landmark-geometry.json, campus-buildings.json, ../tirana-central.osm.
OSM data © OpenStreetMap contributors, ODbL 1.0.
"""
import hashlib
import json
import math
from pathlib import Path
import sys
import xml.etree.ElementTree as ET


def inside(point, ring):
    x, y = point
    result = False
    for a, b in zip(ring, ring[1:] + ring[:1]):
        if (a[1] > y) != (b[1] > y) and x < (b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0]:
            result = not result
    return result


def compile_landmarks(root):
    paths = [root/'landmark-geometry.json', root/'campus-buildings.json', root.parent/'tirana-central.osm']
    source = {}
    xml = ET.parse(paths[2]).getroot()
    nodes = {n.attrib['id']: {'lat': float(n.attrib['lat']), 'lon': float(n.attrib['lon'])} for n in xml.findall('node')}
    for w in xml.findall('way'):
        refs = [n.attrib['ref'] for n in w.findall('nd')]
        if any(n not in nodes for n in refs):
            continue
        source[int(w.attrib['id'])] = {'id': int(w.attrib['id']), 'type': 'way', 'geometry': [nodes[n] for n in refs],
            'tags': {t.attrib['k']: t.attrib['v'] for t in w.findall('tag')}}
    for path in paths[:2]:
        source.update({e['id']: e for e in json.loads(path.read_text())['elements'] if e['type'] == 'way'})
    def geo(id):
        e = source[id]
        p = [[v['lon'], v['lat']] for v in e['geometry']]
        if len(p) < 4 or p[0] != p[-1]:
            raise ValueError(f'Unclosed footprint {id}')
        return p[:-1]
    def projected(p):
        return [[round((lon-19.8188)*111320*math.cos(math.radians(41.3275)), 3), round((41.3275-lat)*111320, 3)] for lon, lat in p]
    ids = {
        'delijorgji': [659792494,659792495,659792496,659792497,659792498,659792499,659792500,1184315630,1184315631],
        'grand': [548100908], 'mangalem': list(range(1512253120,1512253126)),
        'studenti': [], 'air-albania': [795642504], 'teg': [293898197], 'qtu': [268022192],
        'ring': [449527787], 'toptani': [177186612], 'sky': [465295338],
        'sheraton': [248344798], 'rogner': [249185545], 'taivani': [236569963],
        'plaza': [469424840], 'congress': [248344804]
    }
    campus = geo(234270352)
    for id, b in source.items():
        if b.get('tags', {}).get('building') != 'dormitory':
            continue
        ring = geo(id)
        centre = [sum(p[i] for p in ring)/len(ring) for i in [0,1]]
        if inside(centre, campus):
            ids['studenti'].append(id)
    defaults = {'mangalem':21, 'delijorgji':28.8, 'teg':14, 'qtu':10, 'ring':35.2, 'sheraton':25.6, 'congress':14.4}
    buildings = []
    for site, group in ids.items():
        for id in sorted(group):
            e = source[id]
            tags = e.get('tags', {})
            if 'building' not in tags:
                raise ValueError(f'{id} is not a building')
            h = float(tags.get('height', float(tags.get('building:levels',defaults.get(site,16)/3.2))*3.2))
            buildings.append({'id':str(id), 'site':site, 'p':projected(geo(id)), 'h':round(h,2), 'tags':tags,
                'heightBasis':'OSM height' if 'height' in tags else 'OSM levels × 3.2 m estimate' if 'building:levels' in tags else 'authored estimate'})
    buildings.append({'id':'relation/10311002','site':'air-albania','p':projected(geo(746635211)),
        'holes':[projected(geo(746635210))], 'h':35, 'heightBasis':'OSM height',
        'tags':{'building':'stadium','name':'Air Albania Stadium'}, 'replaces':['746635211','746635210']})
    fountain = {'id':'way/233519336','p':projected(geo(233519336)), 'jets':[
        {'id':'node/'+id,'p':projected([[nodes[id]['lon'],nodes[id]['lat']]])[0]} for id in ['13137827486','13137853256','13137854829']]}
    return {'origin':[41.3275,19.8188], 'acquired':'2026-09-10', 'license':'ODbL-1.0',
        'attribution':'© OpenStreetMap contributors', 'sources':[
            {'file':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in paths],
        'buildings':buildings, 'fountain':fountain,
        'campuses':{'mangalem':projected(geo(1512253126)),'studenti':projected(campus)}}


if __name__ == '__main__':
    data = compile_landmarks(Path(sys.argv[1]))
    target = Path(__file__).resolve().parents[1]/'src/games/tirana-city-source/landmarkData.mjs'
    target.write_text('// Generated by import-tirana-landmarks.py; OSM ODbL 1.0. See DATA-LICENSE.md.\nexport const LANDMARK_DATA = '+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n')
    print(f'{len(data["buildings"])} building footprints; fountain with {len(data["fountain"]["jets"])} mapped jets')
