#!/usr/bin/env python3
"""Compile closed building ways and multipolygon holes from an OSM XML extract.
Usage: python scripts/import-tirana-public-buildings.py tirana-central.osm [polytechnic-geometry.json]
No campus boundaries are extruded. Source: OpenStreetMap contributors, ODbL 1.0.
"""
import hashlib,json,math,sys
from pathlib import Path
import xml.etree.ElementTree as ET

SITES={
 'polytechnic':[387444374,410277109,410277110,410277119,410277120,470298324],
 'orthodox':[469978008,469978009], 'st-paul':[459085861], 'namazgja':[461375120],
 'prime-minister':[384505310], 'presidency':[249185540], 'parliament':[256162012],
 'gallery':[228337575], 'hotel-dajti':[236570684], 'children-theatre':[236566862],
 'house-leaves':[418943098], 'archaeology':[410328914], 'rectorate':[410328915],
 'interior':[236566859], 'health':[405763975], 'infrastructure':[462244352],
 'education':[356918582], 'agriculture':[460696070], 'finance':[460695437,460695962],
 'jordan-misja':[568915589,854883380], 'xheko':[400647876], 'monarc':[382410981],
 'twin-towers':[295492165,470567604], 'aba':[449894244], 'etc':[535208028]
}
RELATIONS={469978008:7753718,469978009:7753718,459085861:6786176,384505310:6785985}
DEFAULTS={'orthodox':32.2,'st-paul':22,'namazgja':35,'prime-minister':16,'presidency':15,'parliament':12,
 'house-leaves':8,'education':12,'health':18,'xheko':29,'sacred-heart':17}

def compile_buildings(path):
 xml=ET.parse(path).getroot()
 nodes={int(e.get('id')):[float(e.get('lon')),float(e.get('lat'))] for e in xml.findall('node')}
 ways={int(e.get('id')):e for e in xml.findall('way')}
 extra=Path(sys.argv[2]) if len(sys.argv)>2 else None
 if extra:
  for e in json.loads(extra.read_text())['elements']:
   if e['type']!='way':continue
   w=ET.Element('way',id=str(e['id']))
   for i,v in enumerate(e['geometry']):
    nid=-e['id']*10000+i;nodes[nid]=[v['lon'],v['lat']];ET.SubElement(w,'nd',ref=str(nid))
   for k,v in e.get('tags',{}).items():ET.SubElement(w,'tag',k=k,v=v)
   ways[e['id']]=w
 relations={int(e.get('id')):e for e in xml.findall('relation')}
 tags=lambda e:{t.get('k'):t.get('v') for t in e.findall('tag')}
 def ring(id):
  p=[nodes[int(n.get('ref'))] for n in ways[id].findall('nd')]
  if len(p)<4 or p[0]!=p[-1]:raise ValueError(f'Unclosed way {id}')
  return [[round((lon-19.8188)*111320*math.cos(math.radians(41.3275)),3),round((41.3275-lat)*111320,3)] for lon,lat in p[:-1]]
 buildings=[]
 for site,ids in SITES.items():
  for id in ids:
   t=tags(ways[id]); holes=[];replaces=[]; relation=RELATIONS.get(id)
   if relation:
    r=relations[relation];t={**tags(r),**t}
    inner=[int(m.get('ref')) for m in r.findall('member') if m.get('role')=='inner']
    holes=[ring(i) for i in inner];replaces=[str(i) for i in inner]
   if 'building' not in t:raise ValueError(f'{id} is not a building')
   h=float(t.get('height',float(t.get('building:levels',DEFAULTS.get(site,12)/3.2))*3.2))
   b={'id':str(id),'site':site,'p':ring(id),'h':round(h,2),'tags':t,'heightBasis':'OSM height' if 'height' in t else 'OSM levels × 3.2 m estimate' if 'building:levels' in t else 'authored estimate'}
   if holes:b.update(holes=holes,replaces=replaces)
   if relation:b['sourceRelation']=str(relation)
   if site=='polytechnic':b['variant']='polytechnic-tower' if id==410277110 else 'polytechnic-wing'
   if id==469978009:b.update(variant='orthodox-annex',h=12,heightBasis='annex height estimated separately from dome')
   if id==854883380:b['variant']='concert-hall'
   buildings.append(b)
 return {'acquired':'2026-09-10','origin':[41.3275,19.8188],'license':'ODbL-1.0','attribution':'© OpenStreetMap contributors','sources':[{'file':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in [path]+([extra] if extra else [])],'buildings':buildings}

if __name__=='__main__':
 data=compile_buildings(Path(sys.argv[1]));target=Path(__file__).resolve().parents[1]/'src/games/tirana-city-source/cityBuildingData.mjs'
 target.write_text('// Generated by import-tirana-public-buildings.py; ODbL 1.0.\nexport const CITY_BUILDING_DATA = '+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n')
 print(len(data['buildings']),'buildings at',len(SITES),'sites')
