"""Rebuild visual watercourses from the checksum-verified, committed OSM receipt.

No live map service is needed; heights/width defaults are art direction, not DEM.
"""
import gzip
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'assets-source/tirana-urban'
receipt = json.loads((SOURCE / 'source.osm.json.gz.parts.json').read_text())
parts = []
for part in receipt['parts']:
    data = (SOURCE / part['file']).read_bytes()
    assert hashlib.sha256(data).hexdigest() == part['sha256'], part['file']
    parts.append(data)
archive = b''.join(parts)
assert hashlib.sha256(archive).hexdigest() == receipt['sha256']
source = json.loads(gzip.decompress(archive))
nodes = {e['id']: e for e in source['elements'] if e['type'] == 'node'}

def project(node):
    return [round((node['lon'] - 19.8188) * 111320 * math.cos(math.radians(41.3275)), 2),
            round((41.3275 - node['lat']) * 111320, 2)]

paths = []
for way in source['elements']:
    tags = way.get('tags', {})
    if way['type'] != 'way' or tags.get('waterway') not in ('river', 'stream'):
        continue
    if tags.get('tunnel', 'no') != 'no' or tags.get('covered') == 'yes':
        continue
    # Preserve source connectivity. Never connect waterways via nearby bridges.
    line = [project(nodes[n]) for n in way.get('nodes', []) if n in nodes]
    line = [p for i, p in enumerate(line) if i == 0 or p != line[i - 1]]
    if len(line) < 2:
        continue
    lana = tags.get('name', '').lower() in ('lana', 'lanë', 'lumi i lanës')
    width = 8 if tags['waterway'] == 'river' else 3
    try:
        width = max(1, min(35, float(tags['width'])))
    except (KeyError, ValueError):
        pass
    paths.append({'id': str(way['id']), 'name': tags.get('name', ''), 'line': line,
                  'width': width, 'lana': lana, 'widthMeasured': 'width' in tags})
result = {'sourceSha256': receipt['sha256'], 'origin': [41.3275, 19.8188],
          'attribution': '© OpenStreetMap contributors · ODbL-1.0',
          'verticalDatum': 'Authored visual recess below the existing road datum; not a surveyed elevation',
          'paths': paths}
target = ROOT / 'webapp/src/games/tirana-environment/hydrography.mjs'
target.write_text('// Generated by scripts/import-tirana-hydrography.py. OSM / ODbL-1.0.\n'
                  'export const HYDROGRAPHY=' + json.dumps(result, separators=(',', ':')) + ';\n')
print(json.dumps({'paths': len(paths), 'lanaWays': [p['id'] for p in paths if p['lana']], 'bytes': target.stat().st_size}))
