#!/usr/bin/env python3
"""Extract mapped business identities, stops and fuel footprints; never invent POIs.
Usage: python webapp/scripts/import-tirana-street-life.py tirana-central.osm [advertising.json]
OpenStreetMap contributors, ODbL 1.0. Geometry uses the unchanged city metre frame.
"""
import hashlib,json,math,sys
from pathlib import Path
import xml.etree.ElementTree as ET

def compile_source(path,advertising=None):
 xml=ET.parse(path).getroot();nodes={n.get('id'):n for n in xml.findall('node')}
 def point(e):return [round((float(e.get('lon'))-19.8188)*111320*math.cos(math.radians(41.3275)),3),round((41.3275-float(e.get('lat')))*111320,3)]
 places=[];stops=[];fuel=[];ads=[]
 for e in xml:
  tags={t.get('k'):t.get('v') for t in e.findall('tag')}
  category=tags.get('amenity') if tags.get('amenity') in ['cafe','restaurant','fast_food','bar','pub','fuel'] else 'shop' if tags.get('shop') not in [None,'no','vacant','mall'] else 'bus_stop' if tags.get('highway')=='bus_stop' else None
  if not category or e.tag not in ['node','way']:continue
  ring=None
  if e.tag=='node':p=point(e)
  else:
   ids=[n.get('ref') for n in e.findall('nd')]
   if len(ids)<4 or ids[0]!=ids[-1] or any(i not in nodes for i in ids):raise ValueError('Incomplete selected OSM way '+e.get('id'))
   ring=[point(nodes[i]) for i in ids[:-1]];p=[round(sum(v[k] for v in ring)/len(ring),3) for k in [0,1]]
  if not(-805<=p[0]<=660 and -380<=p[1]<=1150):continue
  keep=['name','brand','shop','amenity','building','level','layer','location','indoor','addr:street','addr:housenumber','cuisine','outdoor_seating','shelter','bench','bus','public_transport','direction','ref','operator','website','check_date','disused','disused:amenity','access']
  t={k:v for k,v in tags.items() if k in keep}
  row={'id':e.tag+'/'+e.get('id'),'p':p,'category':category,'tags':t,'version':int(e.get('version','0')),'editedAt':e.get('timestamp')}
  if ring:row['ring']=ring
  if category=='bus_stop':stops.append(row)
  elif category=='fuel':fuel.append(row)
  elif tags.get('name') or tags.get('brand'):places.append(row)
 if advertising:
  for e in json.loads(advertising.read_text())['elements']:
   t=e.get('tags',{});g=e.get('geometry');c=e.get('center')
   if e['type']=='node':p=point(ET.Element('node',lat=str(e['lat']),lon=str(e['lon'])))
   elif g:p=[round(sum((v['lon']-19.8188)*111320*math.cos(math.radians(41.3275)) for v in g)/len(g),3),round(sum((41.3275-v['lat'])*111320 for v in g)/len(g),3)]
   else:continue
   if -805<=p[0]<=660 and -380<=p[1]<=1150:ads.append({'id':e['type']+'/'+str(e['id']),'p':p,'tags':t})
 return {'acquired':'2026-09-10','origin':[41.3275,19.8188],'attribution':'© OpenStreetMap contributors','license':'ODbL-1.0','sources':[{'file':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in [path]+([advertising] if advertising else [])],'places':places,'stops':stops,'fuel':fuel,'advertising':ads}
if __name__=='__main__':
 data=compile_source(Path(sys.argv[1]),Path(sys.argv[2]) if len(sys.argv)>2 else None)
 p=Path(__file__).resolve().parents[1]/'src/games/tirana-street-life/streetSourceData.mjs';p.write_text('// Generated by import-tirana-street-life.py; OSM ODbL 1.0.\nexport const STREET_SOURCE = '+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n')
 print({k:len(data[k]) for k in ['places','stops','fuel','advertising']})
