// Generated by scripts/buildTableTennisEngine.mjs; edit the TypeScript source.
export const TOUR = [
    {
        name: 'Club Qualifier',
        place: 'Split',
        arena: 'dancingHall',
        opponents: ['Mika Vale', 'Luca Marin', 'Sofia Reyes'],
        difficulty: 0,
        prize: 3
    },
    {
        name: 'Continental Cup',
        place: 'Barcelona',
        arena: 'colorfulStudio',
        opponents: ['Enzo Costa', 'Nadia Silva', 'Rafael Sol'],
        difficulty: 1,
        prize: 4
    },
    {
        name: 'European Open',
        place: 'London',
        arena: 'neonPhotostudio',
        opponents: ['Alex Reed', 'Freya Lane', 'Oliver West'],
        difficulty: 1,
        prize: 5
    },
    {
        name: 'Pacific Masters',
        place: 'Tokyo',
        arena: 'dancingHall',
        opponents: ['Ren Sato', 'Yuna Mori', 'Kai Tanaka'],
        difficulty: 2,
        prize: 6
    },
    {
        name: 'Royal Finals',
        place: 'Melbourne',
        arena: 'dancingHall',
        opponents: ['Ava Brooks', 'Noah Ellis', 'The Champion'],
        difficulty: 2,
        prize: 8
    }
];
export const freshCareer = () => ({
    tour: 0,
    round: 0,
    wins: 0,
    losses: 0,
    credits: 0,
    upgrades: [0, 0, 0],
    bestRally: 0,
    completed: false
});
export function careerResult(c, won, rally) {
    const n = {
        ...c,
        upgrades: [...c.upgrades],
        bestRally: Math.max(c.bestRally, rally)
    };
    if (n.completed)
        return n;
    if (won) {
        n.wins++;
        n.credits += 2;
        n.round++;
        if (n.round === 3) {
            n.credits += TOUR[n.tour].prize;
            n.round = 0;
            n.tour++;
            if (n.tour === TOUR.length) {
                n.tour = TOUR.length - 1;
                n.completed = true;
                n.round = 3;
            }
        }
    }
    else
        n.losses++;
    return n;
}
export function previewServices() {
    let c = freshCareer(), active = '';
    const offline = async () => {
        throw Error('Open the full game to play online.');
    };
    return {
        online: false,
        career: async () => c,
        startCareer: async () => {
            active = 'preview-' + Date.now();
            return { id: active, career: c };
        },
        finishCareer: async (id, won, rally) => {
            if (id === active) {
                c = careerResult(c, won, rally);
                active = '';
            }
            return c;
        },
        upgrade: async (stat) => {
            if (c.credits < 2 || c.upgrades[stat] >= 3)
                throw Error('Earn two skill points from a match first.');
            c = {
                ...c,
                credits: c.credits - 2,
                upgrades: c.upgrades.map((v, i) => (i === stat ? v + 1 : v))
            };
            return c;
        },
        createRoom: offline,
        joinRoom: offline,
        syncRoom: offline,
        leaveRoom: async () => { }
    };
}
