// Generated by scripts/buildTableTennisEngine.mjs; edit the TypeScript source.
export const TOUR = [
    {
        name: 'Club Qualifier',
        place: 'Split',
        arena: 'dancingHall',
        opponents: ['Mika Vale', 'Luca Marin', 'Sofia Reyes'],
        difficulty: 0,
        prize: 3
    },
    {
        name: 'Continental Cup',
        place: 'Barcelona',
        arena: 'colorfulStudio',
        opponents: ['Enzo Costa', 'Nadia Silva', 'Rafael Sol'],
        difficulty: 1,
        prize: 4
    },
    {
        name: 'European Open',
        place: 'London',
        arena: 'neonPhotostudio',
        opponents: ['Alex Reed', 'Freya Lane', 'Oliver West'],
        difficulty: 1,
        prize: 5
    },
    {
        name: 'Pacific Masters',
        place: 'Tokyo',
        arena: 'dancingHall',
        opponents: ['Ren Sato', 'Yuna Mori', 'Kai Tanaka'],
        difficulty: 2,
        prize: 6
    },
    {
        name: 'Royal Finals',
        place: 'Melbourne',
        arena: 'dancingHall',
        opponents: ['Ava Brooks', 'Noah Ellis', 'The Champion'],
        difficulty: 2,
        prize: 8
    }
];
export const freshCareer = () => ({
    tour: 0,
    round: 0,
    wins: 0,
    losses: 0,
    credits: 0,
    upgrades: [0, 0, 0],
    bestRally: 0,
    completed: false,
    medals: []
});
export function normalizeCareer(value) {
    const base = freshCareer();
    const number = (candidate, fallback = 0) => Number.isFinite(Number(candidate))
        ? Math.max(0, Math.floor(Number(candidate)))
        : fallback;
    const completed = Boolean(value?.completed);
    const tour = Math.min(number(value?.tour), TOUR.length - 1);
    const round = completed ? 3 : Math.min(number(value?.round), 2);
    const upgrades = Array.from({ length: 3 }, (_, index) => Math.min(3, number(value?.upgrades?.[index])));
    return {
        ...base,
        ...value,
        tour,
        round,
        wins: number(value?.wins),
        losses: number(value?.losses),
        credits: number(value?.credits),
        upgrades,
        bestRally: number(value?.bestRally),
        completed,
        medals: Array.isArray(value?.medals)
            ? [
                ...new Set(value.medals.filter((m) => typeof m === 'string' && /^rally-[0-4]$/.test(m)))
            ]
            : []
    };
}
export function careerResult(c, won, rally) {
    const current = normalizeCareer(c);
    const n = {
        ...current,
        upgrades: [...current.upgrades],
        bestRally: Math.max(current.bestRally, rally)
    };
    if (n.completed)
        return n;
    const medal = `rally-${n.tour}`;
    if (rally >= rallyGoal(n.tour) && !n.medals.includes(medal)) {
        n.medals = [...n.medals, medal];
        n.credits += 1;
    }
    if (won) {
        n.wins++;
        n.credits += 2;
        n.round++;
        if (n.round === 3) {
            n.credits += TOUR[n.tour].prize;
            n.round = 0;
            n.tour++;
            if (n.tour === TOUR.length) {
                n.tour = TOUR.length - 1;
                n.completed = true;
                n.round = 3;
            }
        }
    }
    else
        n.losses++;
    return n;
}
export function previewServices() {
    let c = freshCareer(), active = '';
    const offline = async () => {
        throw Error('Open the full game to play online.');
    };
    return {
        online: false,
        career: async () => c,
        startCareer: async () => {
            active = 'preview-' + Date.now();
            return { id: active, career: c };
        },
        finishCareer: async (id, won, rally) => {
            if (id === active) {
                c = careerResult(c, won, rally);
                active = '';
            }
            return c;
        },
        upgrade: async (stat) => {
            if (c.credits < 2 || c.upgrades[stat] >= 3)
                throw Error('Earn two skill points from a match first.');
            c = {
                ...c,
                credits: c.credits - 2,
                upgrades: c.upgrades.map((v, i) => (i === stat ? v + 1 : v))
            };
            return c;
        },
        createRoom: offline,
        joinRoom: offline,
        syncRoom: offline,
        leaveRoom: async () => { }
    };
}
/** Existing saves retain all five events and their current round. */
export const ROUND_FORMATS = [
    {
        name: 'Sprint',
        detail: 'Start at 6–6. First to 11, win by two.',
        points: [6, 6],
        gamesToWin: 1
    },
    {
        name: 'Comeback',
        detail: 'Recover from 4–8. First to 11, win by two.',
        points: [4, 8],
        gamesToWin: 1
    },
    {
        name: 'Championship',
        detail: 'Best of three games. Each game to 11.',
        points: [0, 0],
        gamesToWin: 2
    }
];
export const rallyGoal = (tour) => 4 + Math.min(4, Math.max(0, tour)) * 2;
export function careerRound(c) {
    return ROUND_FORMATS[Math.min(2, Math.max(0, c.round))];
}
