// Generated by scripts/buildTableTennisEngine.mjs; edit the TypeScript source.
export const HALF_WIDTH = 0.7625, HALF_LENGTH = 1.37, TABLE_HEIGHT = 0.76;
export const NET_HEIGHT = 0.1525, NET_POST_OUTSIDE = 0.1525, BALL_RADIUS = 0.02, GRAVITY = 9.81;
export const TABLE_RESTITUTION = Math.sqrt(23 / 30), TABLE_GRIP = 0.94;
export const opponent = (seat) => (seat === 0 ? 1 : 0);
export const initialScore = (firstServer = 0) => ({
    points: [0, 0],
    games: [0, 0],
    history: [],
    server: firstServer,
    firstServer,
    totalPoints: 0,
    endsSwapped: false,
    decidingEndChanged: false,
    expedite: false,
    expediteServer: firstServer,
    expediteBase: 0
});
export function awardPoint(s, winner, gamesToWin = 2) {
    s.points[winner]++;
    s.totalPoints++;
    const p = s.points;
    if (p[winner] >= 11 && p[winner] - p[1 - winner] >= 2) {
        s.history.push([...p]);
        s.games[winner]++;
        if (s.games[winner] >= gamesToWin)
            return true;
        s.points = [0, 0];
        s.firstServer = opponent(s.firstServer);
        s.server = s.firstServer;
        s.endsSwapped = !s.endsSwapped;
        s.decidingEndChanged = false;
        s.expediteBase = 0;
        s.expediteServer = s.firstServer;
    }
    else {
        const total = p[0] + p[1];
        const base = s.expedite ? s.expediteServer : s.firstServer;
        const turn = s.expedite
            ? total - s.expediteBase
            : p[0] >= 10 && p[1] >= 10
                ? total - 20
                : Math.floor(total / 2);
        s.server = turn % 2 ? opponent(base) : base;
        if (!s.decidingEndChanged &&
            s.games[0] + s.games[1] === 2 * (gamesToWin - 1) &&
            Math.max(...p) >= 5) {
            s.endsSwapped = !s.endsSwapped;
            s.decidingEndChanged = true;
        }
    }
    return false;
}
