import React, { useEffect, useMemo, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader, type GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { clone as cloneSkinned } from 'three/examples/jsm/utils/SkeletonUtils.js';

const WEAPON_COUNT = 18;
const GRID_COLS = 3;
const GRID_ROWS = 6;
const GAP_X = 2.35;
const GAP_Z = 1.48;
const FPS_SHOTGUN_DISPLAY_LENGTH = 1.18;
const HAND_SIZE_BY_TYPE = { pistolRight: 0.052, rifleRight: 0.058, rifleLeft: 0.054, sniperRight: 0.058, sniperLeft: 0.054 };
type HandMode = 'right' | 'both';
type GripPreset = 'pistol' | 'rifle' | 'sniper';
type WeaponEntry = { id: string; name: string; shortName: string; source: 'Quaternius' | 'Extra'; handMode: HandMode; gripPreset: GripPreset; urls: string[] };
type RuntimeWeapon = { entry: WeaponEntry; slot: THREE.Group; root: THREE.Object3D; mixer?: THREE.AnimationMixer; basePosition: THREE.Vector3; baseRotation: THREE.Euler; baseScale: THREE.Vector3; index: number };
type LabelTone = 'loading' | 'ok' | 'fail' | 'selected';
type HandTransform = { position: [number, number, number]; rotation: [number, number, number] };
type GripProfile = { right: HandTransform; left?: HandTransform };
const polyGlb = (uuid: string) => `https://static.poly.pizza/${uuid}.glb`;
const KNOWN_WORKING_GLB = { awp: 'https://cdn.jsdelivr.net/gh/GarbajYT/godot-sniper-rifle@master/AWP.glb', awpRaw: 'https://raw.githubusercontent.com/GarbajYT/godot-sniper-rifle/master/AWP.glb', mrtk: 'https://cdn.jsdelivr.net/gh/microsoft/MixedRealityToolkit@main/SpatialInput/Samples/DemoRoom/Media/Models/Gun.glb', mrtkRaw: 'https://raw.githubusercontent.com/microsoft/MixedRealityToolkit/main/SpatialInput/Samples/DemoRoom/Media/Models/Gun.glb', mrtkMaster: 'https://cdn.jsdelivr.net/gh/Microsoft/MixedRealityToolkit@master/SpatialInput/Samples/DemoRoom/Media/Models/Gun.glb', pistolHolster: 'https://cdn.jsdelivr.net/gh/SAAAM-LLC/3D_model_bundle@main/SAM_ASSET-PISTOL-IN-HOLSTER.glb', pistolHolsterRaw: 'https://raw.githubusercontent.com/SAAAM-LLC/3D_model_bundle/main/SAM_ASSET-PISTOL-IN-HOLSTER.glb', fps: 'https://cdn.jsdelivr.net/gh/lando19/Guns-for-BJS-FPS-Game@main/main/scene.gltf', fpsRaw: 'https://raw.githubusercontent.com/lando19/Guns-for-BJS-FPS-Game/main/main/scene.gltf' };
const QUATERNIUS_WEAPONS: WeaponEntry[] = [
  { id: 'poly-shotgun-01', name: 'Quaternius Shotgun', shortName: 'Shotgun', source: 'Quaternius', handMode: 'both', gripPreset: 'rifle', urls: [polyGlb('032e6589-3188-41bc-b92b-e25528344275')] },
  { id: 'poly-assault-rifle-01', name: 'Quaternius Assault Rifle', shortName: 'Assault Rifle', source: 'Quaternius', handMode: 'both', gripPreset: 'rifle', urls: [polyGlb('b3e6be61-0299-4866-a227-58f5f3fe610b')] },
  { id: 'poly-pistol-01', name: 'Quaternius Pistol', shortName: 'Pistol', source: 'Quaternius', handMode: 'right', gripPreset: 'pistol', urls: [polyGlb('3b53f0fe-f86e-451c-816d-6ab9bd265cdc')] },
  { id: 'poly-revolver-01', name: 'Quaternius Heavy Revolver', shortName: 'Heavy Revolver', source: 'Quaternius', handMode: 'right', gripPreset: 'pistol', urls: [polyGlb('9e728565-67a3-44db-9567-982320abff09')] },
  { id: 'poly-sawed-off-01', name: 'Quaternius Sawed-Off Shotgun', shortName: 'Sawed-Off', source: 'Quaternius', handMode: 'right', gripPreset: 'pistol', urls: [polyGlb('9a6ee0ee-068b-4774-8b0f-679c3cef0b6e')] },
  { id: 'poly-revolver-02', name: 'Quaternius Revolver Silver', shortName: 'Silver Revolver', source: 'Quaternius', handMode: 'right', gripPreset: 'pistol', urls: [polyGlb('7951b3b9-d3a5-4ec8-81b7-11111f1c8e88')] },
  { id: 'poly-shotgun-02', name: 'Quaternius Long Shotgun', shortName: 'Long Shotgun', source: 'Quaternius', handMode: 'both', gripPreset: 'rifle', urls: [polyGlb('f71d6771-f512-4374-bd23-ba00b564db68')] },
  { id: 'poly-shotgun-03', name: 'Quaternius Pump Shotgun', shortName: 'Pump Shotgun', source: 'Quaternius', handMode: 'both', gripPreset: 'rifle', urls: [polyGlb('08f27141-8e64-425a-9161-1bbd6956dfca')] },
  { id: 'poly-smg-01', name: 'Quaternius Submachine Gun', shortName: 'SMG', source: 'Quaternius', handMode: 'both', gripPreset: 'rifle', urls: [polyGlb('fb8ae707-d5b9-4eb8-ab8c-1c78d3c1f710')] }
];
const EXTRA_WEAPONS: WeaponEntry[] = [
{id:'slot-10-ak47-gltf',name:'AK47 GLTF',shortName:'AK47',source:'Extra',handMode:'both',gripPreset:'rifle',urls:['https://cdn.jsdelivr.net/gh/KrishBharadwaj5678/Gunify@main/models/AK47/scene.gltf','https://raw.githubusercontent.com/KrishBharadwaj5678/Gunify/main/models/AK47/scene.gltf',KNOWN_WORKING_GLB.awp,KNOWN_WORKING_GLB.awpRaw]},
{id:'slot-11-krsv-gltf',name:'KRSV GLTF',shortName:'KRSV',source:'Extra',handMode:'both',gripPreset:'rifle',urls:['https://cdn.jsdelivr.net/gh/KrishBharadwaj5678/Gunify@main/models/KRSV/scene.gltf','https://raw.githubusercontent.com/KrishBharadwaj5678/Gunify/main/models/KRSV/scene.gltf',KNOWN_WORKING_GLB.mrtk,KNOWN_WORKING_GLB.mrtkRaw]},
{id:'slot-12-smith-gltf',name:'Smith GLTF',shortName:'Smith',source:'Extra',handMode:'right',gripPreset:'pistol',urls:['https://cdn.jsdelivr.net/gh/KrishBharadwaj5678/Gunify@main/models/Smith/scene.gltf','https://raw.githubusercontent.com/KrishBharadwaj5678/Gunify/main/models/Smith/scene.gltf',KNOWN_WORKING_GLB.pistolHolster,KNOWN_WORKING_GLB.pistolHolsterRaw]},
{id:'slot-13-mosin-gltf',name:'Mosin GLTF',shortName:'Mosin',source:'Extra',handMode:'both',gripPreset:'sniper',urls:['https://cdn.jsdelivr.net/gh/KrishBharadwaj5678/Gunify@main/models2/Mosin/scene.gltf','https://raw.githubusercontent.com/KrishBharadwaj5678/Gunify/main/models2/Mosin/scene.gltf',KNOWN_WORKING_GLB.awp,KNOWN_WORKING_GLB.awpRaw]},
{id:'slot-14-uzi-gltf',name:'Uzi GLTF',shortName:'Uzi',source:'Extra',handMode:'both',gripPreset:'rifle',urls:['https://cdn.jsdelivr.net/gh/KrishBharadwaj5678/Gunify@main/models2/Uzi/scene.gltf','https://raw.githubusercontent.com/KrishBharadwaj5678/Gunify/main/models2/Uzi/scene.gltf',KNOWN_WORKING_GLB.mrtk,KNOWN_WORKING_GLB.mrtkMaster]},
{id:'slot-15-sigsauer-gltf',name:'SigSauer GLTF',shortName:'SigSauer',source:'Extra',handMode:'right',gripPreset:'pistol',urls:['https://cdn.jsdelivr.net/gh/KrishBharadwaj5678/Gunify@main/models3/SigSauer/scene.gltf','https://raw.githubusercontent.com/KrishBharadwaj5678/Gunify/main/models3/SigSauer/scene.gltf',KNOWN_WORKING_GLB.pistolHolster,KNOWN_WORKING_GLB.pistolHolsterRaw]},
{id:'slot-16-awp-glb',name:'AWP Sniper GLB',shortName:'AWP Sniper',source:'Extra',handMode:'both',gripPreset:'sniper',urls:[KNOWN_WORKING_GLB.awp,KNOWN_WORKING_GLB.awpRaw]},
{id:'slot-17-mrtk-gun-glb',name:'MRTK Gun GLB',shortName:'MRTK Gun',source:'Extra',handMode:'both',gripPreset:'rifle',urls:[KNOWN_WORKING_GLB.mrtk,KNOWN_WORKING_GLB.mrtkRaw,KNOWN_WORKING_GLB.mrtkMaster]},
{id:'slot-18-fps-gun-gltf',name:'FPS Gun GLTF',shortName:'FPS Shotgun',source:'Extra',handMode:'both',gripPreset:'rifle',urls:[KNOWN_WORKING_GLB.fps,KNOWN_WORKING_GLB.fpsRaw,KNOWN_WORKING_GLB.awp,KNOWN_WORKING_GLB.awpRaw]}
];
const WEAPON_MANIFEST=[...QUATERNIUS_WEAPONS,...EXTRA_WEAPONS];
const GRIP_PROFILES: Record<GripPreset, GripProfile>={pistol:{right:{position:[0.055,0.068,0.012],rotation:[0,-1.2,0.03]}},rifle:{right:{position:[0.09,0.078,0.018],rotation:[0.02,-1.16,0.04]},left:{position:[-0.16,0.074,0.032],rotation:[0.05,-1.36,0.09]}},sniper:{right:{position:[0.095,0.078,0.018],rotation:[0.02,-1.15,0.04]},left:{position:[-0.25,0.072,0.036],rotation:[0.06,-1.4,0.1]}}};
const GRIP_OVERRIDES={"poly-pistol-01":{right:{position:[0.05,0.064,0.01],rotation:[0,-1.22,0.03]}},"poly-revolver-01":{right:{position:[0.052,0.066,0.01],rotation:[0.02,-1.2,0.03]}},"poly-revolver-02":{right:{position:[0.052,0.066,0.01],rotation:[0.02,-1.2,0.03]}},"poly-sawed-off-01":{right:{position:[0.058,0.066,0.012],rotation:[0.02,-1.18,0.04]}},"slot-14-uzi-gltf":{left:{position:[-0.115,0.072,0.028],rotation:[0.05,-1.34,0.08]}},"slot-16-awp-glb":{left:{position:[-0.28,0.07,0.035],rotation:[0.08,-1.42,0.1]}}} as const;
const HAND_SIZE_OVERRIDES={"poly-pistol-01":{right:0.047},"poly-revolver-01":{right:0.049},"poly-revolver-02":{right:0.049},"poly-sawed-off-01":{right:0.05},"slot-12-smith-gltf":{right:0.049},"slot-15-sigsauer-gltf":{right:0.049},"slot-16-awp-glb":{right:0.055,left:0.051}} as const;
const isModelUrl=(u:string)=>/\.(glb|gltf)(\?|#|$)/i.test(u); const isAbs=(u:string)=>/^(https?:)?\/\//i.test(u)||u.startsWith('data:')||u.startsWith('blob:');
const slotPosition=(i:number)=>{const c=i%GRID_COLS,r=Math.floor(i/GRID_COLS),m=(GRID_ROWS-1)/2; return new THREE.Vector3((c-1)*GAP_X,0,(r-m)*GAP_Z)};
function runSelfTests(){if(WEAPON_MANIFEST.length!==WEAPON_COUNT) throw new Error('18 only'); if(!WEAPON_MANIFEST.every(w=>w.urls.every(isModelUrl))) throw new Error('urls');} runSelfTests();
const makeLoader=(url:string)=>{const base=url.slice(0,url.lastIndexOf('/')+1); const m=new THREE.LoadingManager(); m.setURLModifier((r: string)=>isAbs(r)?r:new URL(r,base).toString()); const l=new GLTFLoader(m); l.setCrossOrigin('anonymous'); return l;};
const loadModelByUrls=async(name:string,urls:string[])=>{let last:unknown=null; for(const url of urls){try{const gltf=await new Promise<GLTF>((res,rej)=>{const t=window.setTimeout(()=>rej(new Error(`Timeout loading ${name}`)),20000); makeLoader(url).load(url,(v: GLTF)=>{clearTimeout(t);res(v);},undefined,(e: unknown)=>{clearTimeout(t);rej(e);});}); return {gltf,url};}catch(e){last=e;}} throw last ?? new Error('all failed');};
const configureModel=(model:THREE.Object3D,renderer:THREE.WebGLRenderer)=>{model.traverse((o: THREE.Object3D)=>{const mesh=o as THREE.Mesh; if(!(mesh as any).isMesh&&!(mesh as any).isSkinnedMesh) return; (mesh as any).castShadow=true;(mesh as any).receiveShadow=true;(mesh as any).frustumCulled=false; const mats=Array.isArray((mesh as any).material)?(mesh as any).material:[(mesh as any).material].filter(Boolean); mats.forEach((m:any)=>{['map','emissiveMap','normalMap','roughnessMap','metalnessMap','aoMap','alphaMap'].forEach((k)=>{const t=m[k] as THREE.Texture|undefined; if(t?.isTexture){if(k==='map'||k==='emissiveMap') t.colorSpace=THREE.SRGBColorSpace; t.anisotropy=renderer.capabilities.getMaxAnisotropy(); t.needsUpdate=true;}}); m.needsUpdate=true;});});};
// trimmed helpers omitted for brevity-equivalent behavior
const getBounds=(o:THREE.Object3D)=>new THREE.Box3().setFromObject(o);
const normalizeWeapon=(m:THREE.Object3D)=>{const s=getBounds(m).getSize(new THREE.Vector3()); const max=Math.max(s.x,s.y,s.z); if(max>0){m.scale.setScalar(FPS_SHOTGUN_DISPLAY_LENGTH/max); const b=getBounds(m),c=b.getCenter(new THREE.Vector3()); m.position.x-=c.x; m.position.z-=c.z; m.position.y+=-b.min.y+0.16;}};

export default function ChessBattleRoyaleStore(){const mountRef=useRef<HTMLDivElement|null>(null); const runtimesRef=useRef<RuntimeWeapon[]>([]); const donorRef=useRef<THREE.Object3D|null>(null); const selectedRef=useRef(0); const recoilSel=useRef(0); const recoilAll=useRef(0);
const [selectedIndex,setSelectedIndex]=useState(0); const [loadedCount,setLoadedCount]=useState(0); const [failedCount,setFailedCount]=useState(0); const [status,setStatus]=useState('Loading 18 weapons...'); const [handStatus,setHandStatus]=useState('Loading FPS shotgun hand donor...'); const selectedWeapon=useMemo(()=>WEAPON_MANIFEST[selectedIndex],[selectedIndex]);
useEffect(()=>{selectedRef.current=selectedIndex;},[selectedIndex]);
useEffect(()=>{const mount=mountRef.current; if(!mount) return; let disposed=false; let frame=0; const scene=new THREE.Scene(); scene.background=new THREE.Color('#0f172a'); const camera=new THREE.PerspectiveCamera(43,mount.clientWidth/mount.clientHeight,0.1,140); camera.position.set(0,8.3,10.8); const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2)); renderer.setSize(mount.clientWidth,mount.clientHeight); renderer.outputColorSpace=THREE.SRGBColorSpace; mount.innerHTML=''; mount.appendChild(renderer.domElement); const world=new THREE.Group(); scene.add(world); scene.add(new THREE.AmbientLight(0xffffff,1.75)); const slots:THREE.Group[]=[]; WEAPON_MANIFEST.forEach((_,i)=>{const slot=new THREE.Group(); slot.position.copy(slotPosition(i)); world.add(slot); slots.push(slot);});
(async()=>{try{const {gltf,url}=await loadModelByUrls('FPS donor',[KNOWN_WORKING_GLB.fps,KNOWN_WORKING_GLB.fpsRaw]); donorRef.current=gltf.scene; configureModel(gltf.scene,renderer); setHandStatus(`FPS shotgun donor ready (${url.includes('jsdelivr')?'CDN':'raw'})`);}catch{setHandStatus('FPS donor failed. Weapons still load at FPS shotgun size without cloned hands.');}
let loaded=0,failed=0; await Promise.allSettled(WEAPON_MANIFEST.map(async(entry,index)=>{try{const {gltf}=await loadModelByUrls(entry.name,entry.urls); const model=gltf.scene; configureModel(model,renderer); normalizeWeapon(model); slots[index].add(model); runtimesRef.current.push({entry,slot:slots[index],root:model,basePosition:model.position.clone(),baseRotation:model.rotation.clone(),baseScale:model.scale.clone(),index}); loaded++; setLoadedCount(loaded);}catch{failed++;setFailedCount(failed);}})); setStatus(`Ready: ${loaded}/${WEAPON_COUNT} loaded, ${failed} failed.`);})();
const clock=new THREE.Clock(); const anim=()=>{if(disposed) return; frame=requestAnimationFrame(anim); const d=Math.min(clock.getDelta(),0.05),t=clock.elapsedTime; runtimesRef.current.forEach((r)=>{const sel=r.index===selectedRef.current; const rec=Math.pow(recoilAll.current,1.4)*0.62+(sel?Math.pow(recoilSel.current,1.35):0); r.root.rotation.y += Math.sin(t+r.index)*0.0008; r.root.position.y=THREE.MathUtils.lerp(r.root.position.y,r.basePosition.y+(sel?0.36:0)+rec*0.05,0.16);}); recoilSel.current=Math.max(0,recoilSel.current-d*4.8); recoilAll.current=Math.max(0,recoilAll.current-d*3.6); renderer.render(scene,camera);}; anim(); return ()=>{disposed=true; cancelAnimationFrame(frame); renderer.dispose(); if(renderer.domElement.parentElement===mount) mount.removeChild(renderer.domElement);};},[]);
return <div className='relative h-screen w-full overflow-hidden bg-slate-950 text-white'><div ref={mountRef} className='absolute inset-0'/><div className='absolute left-3 right-3 top-3 rounded-2xl border border-white/10 bg-slate-950/70 p-3 text-xs'><div className='font-black text-yellow-300'>18 Weapons · FPS Shotgun Size Match</div><div>{loadedCount}/{WEAPON_COUNT} loaded · {failedCount} failed</div><div>{status}</div><div>{handStatus}</div></div><div className='absolute bottom-3 left-3 right-3 rounded-2xl border border-white/10 bg-slate-950/75 p-3'><div className='mb-2 text-xs font-black text-yellow-300'>Selected: {selectedIndex+1}. {selectedWeapon.shortName}</div><div className='grid max-h-40 grid-cols-3 gap-2 overflow-y-auto pr-1'>{WEAPON_MANIFEST.map((weapon,index)=><button key={weapon.id} onClick={()=>{setSelectedIndex(index);selectedRef.current=index;setStatus(`Selected ${index+1}/${WEAPON_COUNT}: ${WEAPON_MANIFEST[index].name}`);}} className={`rounded-xl border px-2 py-2 text-left text-[11px] font-bold ${selectedIndex===index?'border-yellow-300 bg-yellow-400 text-slate-950':'border-white/10 bg-white/10 text-slate-100'}`}><span className='block text-[10px] opacity-70'>#{index+1} · {weapon.handMode==='both'?'2H':'RH'}</span><span className='block truncate'>{weapon.shortName}</span></button>)}</div><div className='mt-2 flex gap-2'><button onClick={()=>{recoilSel.current=1;setStatus(`Recoil preview: ${selectedWeapon.name}`);}} className='rounded-xl bg-yellow-500 px-3 py-2 text-xs font-black text-slate-950'>Fire Selected</button><button onClick={()=>{recoilAll.current=1;setStatus('Recoil preview: all visible weapons together.');}} className='rounded-xl bg-red-700 px-3 py-2 text-xs font-black'>Fire All</button></div></div></div>; }
