import ts from 'typescript';
import { readFileSync, writeFileSync } from 'node:fs';
for (const name of ['engine', 'career']) {
  const path = new URL(`../shared/tabletennis/${name}`, import.meta.url);
  const source = readFileSync(`${path.pathname}.ts`, 'utf8');
  const output = ts.transpileModule(source, {
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ES2022
    }
  }).outputText;
  writeFileSync(
    `${path.pathname}.js`,
    '// Generated by scripts/buildTableTennisEngine.mjs; edit the TypeScript source.\n' +
      output
  );
}
