import ts from 'typescript';
import { readFileSync, writeFileSync } from 'node:fs';
for (const name of ['scoring', 'engine']) {
  const path = new URL(`../shared/bowling/${name}`, import.meta.url).pathname;
  const output = ts.transpileModule(readFileSync(`${path}.ts`, 'utf8'), {
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ES2022
    }
  }).outputText;
  writeFileSync(
    `${path}.js`,
    '// Generated by scripts/buildBowlingEngine.mjs; edit the TypeScript source.\n' +
      output
  );
}
