"""Original CC0 cue equipment. Run with Blender 4.2 --background --python.

The evaluated bevelled meshes are exported directly to compact indexed data for
synchronous Three.js loading. No model request is needed when a player shoots.
"""
import bpy
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'assets-source/cue-reach'
OUTPUT = ROOT / 'webapp/src/pages/Games/shared/cueReachMeshes.ts'
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)


def lathe(name, profile, sides=32, knurl=False):
    verts, faces = [], []
    for radius, height in profile:
        for n in range(sides):
            angle = n * math.tau / sides
            r = radius * (0.965 if knurl and n % 2 else 1)
            verts.append((r * math.cos(angle), r * math.sin(angle), height))
    for ring in range(len(profile)-1):
        for n in range(sides):
            a, b = ring*sides+n, ring*sides+(n+1)%sides
            faces.append((a, b, b+sides, a+sides))
    faces += [tuple(reversed(range(sides))), tuple(range((len(profile)-1)*sides, len(verts)))]
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(verts, [], faces)
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    for poly in mesh.polygons:
        poly.use_smooth = len(poly.vertices) == 4
    return obj


# These parts are normalized along their length only. At runtime the collars
# keep fixed dimensions and the two nested tubes change their overlap.
parts = {}
parts['tube'] = lathe('Telescopic sleeve', [(.91,-.5),(1,-.49),(1,.475),(.94,.5)])
parts['inner'] = lathe('Inner telescopic tube', [(.95,-.5),(1,-.485),(1,.485),(.94,.5)])
parts['collar'] = lathe('Machined brass coupling', [(.86,-.5),(.98,-.44),(1,-.34),
    (1,-.19),(.945,-.16),(.945,-.08),(1,-.05),(1,.28),(.965,.34),(.965,.44),(.86,.5)], 40)
parts['lock'] = lathe('Fluted twist lock', [(.84,-.5),(1,-.34),(1,.34),(.84,.5)], 64, True)
parts['cap'] = lathe('Recessed rubber bumper', [(.84,-.5),(1,-.2),(1,.2),(.9,.44),(.72,.5)])
parts['handle'] = lathe('Tapered ash rest handle', [(1,-.5),(1,-.495),(.74,.47),(.72,.5)])
parts['foot'] = lathe('Cloth-safe rubber foot', [(.9,-.5),(1,-.2),(1,.32),(.86,.5)], 24)

# Cross head: four lobes, a round cue cradle, two lower feet, and a bevelled
# cast-brass silhouette. Coordinates are metres, with the cloth at z=-.046.
outline = [(-.068,-.04),(-.062,-.046),(-.044,-.046),(-.013,-.014),
    (0,-.008),(.013,-.014),(.044,-.046),(.062,-.046),(.068,-.04),
    (.032,0),(.062,.035),(.064,.047),(.057,.055),(.044,.055),
    (.010,.024),(.006,.020),(0,.018),(-.006,.020),(-.010,.024),
    (-.044,.055),(-.057,.055),(-.064,.047),(-.062,.035),(-.032,0)]
verts = [(x, depth, z) for depth in [-.008,.008] for x,z in outline]
n = len(outline)
faces = [tuple(reversed(range(n))),tuple(range(n,2*n))]
faces += [(i,(i+1)%n,(i+1)%n+n,i+n) for i in range(n)]
mesh = bpy.data.meshes.new('Cross rest head')
mesh.from_pydata(verts, [], faces)
mesh.update()
obj = bpy.data.objects.new('Cast brass cross rest',mesh)
bpy.context.collection.objects.link(obj)
bpy.context.view_layer.objects.active = obj
obj.select_set(True)
bevel = obj.modifiers.new('Rounded casting edges','BEVEL')
bevel.width = .002
bevel.segments = 3
bevel.affect = 'EDGES'
normal = obj.modifiers.new('Weighted machined normals','WEIGHTED_NORMAL')
normal.keep_sharp = True
parts['head'] = obj

result = {'license':'CC0-1.0','generator':'Blender 4.2 / scripts/build-cue-reach-equipment.py',
    'head': {'footY':-.046,'cradleY':.018,'socketY':-.002}, 'meshes':{}}
deps = bpy.context.evaluated_depsgraph_get()
for name,obj in parts.items():
    evaluated = obj.evaluated_get(deps)
    mesh = evaluated.to_mesh()
    mesh.calc_loop_triangles()
    positions, normals, indices, unique = [], [], [], {}
    for tri in mesh.loop_triangles:
        for loop in tri.loops:
            co = mesh.vertices[mesh.loops[loop].vertex_index].co
            no = mesh.corner_normals[loop].vector
            # Blender Z up to Three Y up, retaining right-handed winding.
            values = tuple(round(v,6) for v in (co.x,co.z,-co.y,no.x,no.z,-no.y))
            if values not in unique:
                unique[values] = len(positions)//3
                positions.extend(values[:3]); normals.extend(values[3:])
            indices.append(unique[values])
    result['meshes'][name] = {'position':positions,'normal':normals,'index':indices}
    evaluated.to_mesh_clear()

# Keep the editable objects laid out separately in the source file.
for index,obj in enumerate(parts.values()):
    obj.location.x = index * 2.6
SOURCE.mkdir(parents=True, exist_ok=True)
bpy.ops.wm.save_as_mainfile(filepath=str(SOURCE/'cue-extension-rest.blend'), compress=True)
OUTPUT.write_text('// Generated by Blender; rebuild with scripts/build-cue-reach-equipment.py.\nexport default '+json.dumps(result,separators=(',',':'))+';\n')
print('Exported', sum(len(m['index'])//3 for m in result['meshes'].values()),
    'triangles in', OUTPUT.stat().st_size, 'bytes')
