import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, rename, rmdir, stat, statfs, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { extractModuleDependencySpecifiers } from './source-inventory.mjs';

const NETWORK_URL = /^https?:\/\//i;
const DEPENDENCY_SCHEMA_VERSION = 3;
const mapScript = (mapping) => `/* Generated by vendor-external-assets.mjs; source checksums are in manifest.json. */\nself.__TONPLAYGRAM_EXTERNAL_ASSETS__ = ${JSON.stringify(mapping)};\n`;
export const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

export function normalizeSourceUrl(value, base) {
  const url = new URL(value, base);
  if (!/^https?:$/.test(url.protocol)) throw new Error(`Unsupported asset protocol: ${url.protocol}`);
  url.hash = '';
  return url.href;
}

/** A source URL has a stable, readable location; query variants never overwrite each other. */
export function localAssetUrl(value, publicPrefix = '/assets/external') {
  const url = new URL(value);
  const parts = url.pathname.split('/').filter(Boolean).map((part) => {
    const decoded = decodeURIComponent(part);
    return decoded.replace(/[^a-zA-Z0-9._-]/g, (char) => `_${Buffer.from(char).toString('hex')}`).replace(/^\.+$/, '_');
  });
  if (!parts.length || url.pathname.endsWith('/')) parts.push('index');
  let filename = parts.pop();
  // Static hosts infer MIME from filenames. These provider endpoints serve
  // executable resources without conventional filename extensions.
  if (url.hostname === 'fonts.googleapis.com' && /^\/css2?$/.test(url.pathname)) filename += '.css';
  if (['esm.sh', 'cdn.skypack.dev'].includes(url.hostname) && !/\.(?:m?js|css|json|wasm|png|jpe?g|webp|woff2?|ttf|svg)$/i.test(filename)) filename += '.js';
  if (url.search) {
    const extension = path.posix.extname(filename);
    filename = `${filename.slice(0, extension ? -extension.length : undefined)}--${sha256(url.search).slice(0, 16)}${extension}`;
  }
  return `${publicPrefix.replace(/\/$/, '')}/${url.host.replace(/:/g, '_')}/${[...parts, filename].join('/')}`;
}

async function atomicWrite(filename, bytes) {
  await mkdir(path.dirname(filename), { recursive: true });
  const temporary = `${filename}.${process.pid}.tmp`;
  await writeFile(temporary, bytes);
  await rename(temporary, filename);
}

function sourceType(sourceUrl, contentType = '') {
  const pathname = new URL(sourceUrl).pathname.toLowerCase();
  if (pathname.endsWith('.gltf')) return 'gltf';
  if (pathname.endsWith('.glb')) return 'glb';
  if (/\.css$/.test(pathname) || /text\/css/i.test(contentType)) return 'css';
  if (/\.(?:m?js|cjs)$/.test(pathname) || /javascript|ecmascript/i.test(contentType)) return 'javascript';
  if (/\.json$/.test(pathname) || /application\/json/i.test(contentType)) return 'json';
  return 'binary';
}

export function parseGlb(bytes) {
  if (bytes.length < 20 || bytes.toString('ascii', 0, 4) !== 'glTF' || bytes.readUInt32LE(4) !== 2 || bytes.readUInt32LE(8) !== bytes.length) throw new Error('Invalid GLB header or length');
  const chunks = [];
  for (let offset = 12; offset < bytes.length;) {
    if (offset + 8 > bytes.length) throw new Error('Truncated GLB chunk header');
    const length = bytes.readUInt32LE(offset);
    const type = bytes.readUInt32LE(offset + 4);
    if (length % 4 || offset + 8 + length > bytes.length) throw new Error('Invalid GLB chunk length');
    chunks.push({ type, bytes: bytes.subarray(offset + 8, offset + 8 + length) });
    offset += 8 + length;
  }
  if (chunks[0]?.type !== 0x4e4f534a) throw new Error('GLB is missing its JSON chunk');
  return { chunks, document: JSON.parse(chunks[0].bytes.toString('utf8').trim()) };
}

export function rewriteGlb(bytes, transform) {
  const { document, chunks } = parseGlb(bytes);
  const before = JSON.stringify(document);
  const after = JSON.stringify(transform(document));
  if (after === before) return bytes;
  const json = Buffer.from(after);
  chunks[0] = { type: 0x4e4f534a, bytes: Buffer.concat([json, Buffer.alloc((4 - json.length % 4) % 4, 0x20)]) };
  const header = Buffer.alloc(12);
  header.write('glTF'); header.writeUInt32LE(2, 4);
  header.writeUInt32LE(12 + chunks.reduce((sum, chunk) => sum + 8 + chunk.bytes.length, 0), 8);
  return Buffer.concat([header, ...chunks.flatMap(chunk => {
    const head = Buffer.alloc(8); head.writeUInt32LE(chunk.bytes.length); head.writeUInt32LE(chunk.type, 4);
    return [head, chunk.bytes];
  })]);
}

function isExternalReference(reference) {
  return reference && !/^(?:data:|blob:|#|javascript:)/i.test(reference);
}

function compatibleDecoder(sourceUrl, aliasUrl) {
  const extension = (url) => path.posix.extname(new URL(url).pathname).toLowerCase();
  const source = extension(sourceUrl);
  const alias = extension(aliasUrl);
  // Encodings are distinct original resources. In particular, PNG can carry
  // alpha absent from JPEG, and HDR/EXR require different Three.js decoders.
  const originalEncodings = new Set(['.hdr', '.exr', '.png', '.jpg', '.jpeg', '.webp', '.avif', '.gif', '.gltf', '.glb']);
  return !(originalEncodings.has(source) || originalEncodings.has(alias)) || source === alias;
}

/** Discover dependencies before rewriting so cycles are safe and every file can be verified. */
export function findDependencies(bytes, sourceUrl, contentType, resolvedUrl = sourceUrl) {
  const type = sourceType(sourceUrl, contentType);
  if (!['gltf', 'glb', 'css', 'javascript'].includes(type)) return [];
  const text = type === 'glb' ? '' : bytes.toString('utf8');
  const references = new Set();
  if (type === 'gltf' || type === 'glb') {
    const gltf = type === 'glb' ? parseGlb(bytes).document : JSON.parse(text);
    for (const entry of [...(gltf.buffers || []), ...(gltf.images || [])]) {
      if (entry.uri && isExternalReference(entry.uri)) references.add(entry.uri);
    }
  } else if (type === 'css') {
    for (const match of text.matchAll(/url\(\s*(['"]?)([^'"\s)]+)\1\s*\)|@import\s+(['"])([^'"]+)\3/g)) {
      const reference = match[2] || match[4];
      if (isExternalReference(reference)) references.add(reference);
    }
  } else {
    // Parse modules structurally, including multiline import/export clauses.
    // Bare package imports continue to use the page's import map.
    for (const reference of extractModuleDependencySpecifiers(text, sourceUrl)) {
      if (isExternalReference(reference) && /^(?:https?:|\/|\.)/.test(reference)) references.add(reference);
    }
    // Worker/resource URL constructors also accept bare relative filenames;
    // unlike ESM package identifiers, those resolve against this module URL.
    for (const match of text.matchAll(/\bnew\s+URL\s*\(\s*['"]([^'"]+)['"]\s*,\s*import\.meta\.url\s*\)/g)) {
      if (isExternalReference(match[1])) references.add(match[1]);
    }
    for (const call of text.matchAll(/\bimportScripts\s*\(([^)]*)\)/g)) {
      for (const argument of call[1].matchAll(/(?:^|,)\s*(['"])([^'"]+)\1\s*(?=,|$)/g)) {
        if (isExternalReference(argument[2])) references.add(argument[2]);
      }
    }
  }
  return [...references].map((reference) => ({ reference, url: normalizeSourceUrl(reference, resolvedUrl) }));
}

/** Preserve exact binary payloads. Only URI-bearing text formats are changed. */
export function rewriteDependencies(bytes, sourceUrl, contentType, urlMap, dependencies = []) {
  const type = sourceType(sourceUrl, contentType);
  if (!['gltf', 'glb', 'json', 'css', 'javascript'].includes(type)) return bytes;
  let text = type === 'glb' ? '' : bytes.toString('utf8');
  if (type === 'gltf' || type === 'glb' || type === 'json') {
    const dependencyUrls = new Map(dependencies.map((entry) => [entry.reference, entry.url]));
    const transform = (value, key) => {
      if (typeof value === 'string') {
        let resolved;
        try { resolved = dependencyUrls.get(value) || normalizeSourceUrl(value, sourceUrl); } catch { return value; }
        if ((['gltf', 'glb'].includes(type) && key === 'uri') || NETWORK_URL.test(value)) return urlMap[resolved] ? `${urlMap[resolved]}${new URL(value, sourceUrl).hash}` : value;
        return value;
      }
      if (Array.isArray(value)) return value.map((entry) => transform(entry));
      if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, transform(v, k)]));
      return value;
    };
    if (type === 'glb') return rewriteGlb(bytes, transform);
    return Buffer.from(`${JSON.stringify(transform(JSON.parse(text)), null, 2)}\n`);
  }
  for (const { reference, url } of [...dependencies].sort((a, b) => b.reference.length - a.reference.length)) {
    const local = urlMap[url] ? `${urlMap[url]}${new URL(reference, sourceUrl).hash}` : null;
    if (!local) continue;
    // Dependencies were extracted from quoted literals or CSS URL tokens; constrain replacements.
    const escaped = reference.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    text = text.replace(new RegExp(`([\"'\\(\\s])${escaped}(?=[\"'\\)\\s])`, 'g'), `$1${local}`);
  }
  return Buffer.from(text);
}

function dependencyReferenceErrors(bytes, record, urlMap, allowOriginal = false) {
  if (!record.dependencies?.length) return [];
  const references = new Set(findDependencies(bytes, record.sourceUrl, record.contentType, record.resolvedUrl).map((dependency) => dependency.reference.split('#')[0]));
  const errors = [];
  for (const dependency of record.dependencies) {
    const target = urlMap[dependency.url];
    if (target && !references.has(target) && !(allowOriginal && references.has(dependency.reference.split('#')[0]))) {
      errors.push(`Dependency URI does not point to ${target} in ${record.sourceUrl}`);
    }
  }
  return errors;
}

export function validatePayload(bytes, sourceUrl, contentType = '') {
  if (!bytes.length) throw new Error('Empty response');
  const preview = bytes.subarray(0, 512).toString('utf8').trimStart();
  if (/text\/html/i.test(contentType) || /^<!doctype\s+html|^<html(?:\s|>)/i.test(preview)) {
    throw new Error('Received HTML instead of an asset');
  }
  const pathname = new URL(sourceUrl).pathname.toLowerCase();
  if (/\.glb$/.test(pathname)) parseGlb(bytes);
  if (/\.png$/.test(pathname) && !bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) throw new Error('Invalid PNG signature');
  if (/\.jpe?g$/.test(pathname) && !(bytes[0] === 255 && bytes[1] === 216)) throw new Error('Invalid JPEG signature');
  if (/\.webp$/.test(pathname) && !(bytes.subarray(0, 4).toString() === 'RIFF' && bytes.subarray(8, 12).toString() === 'WEBP')) throw new Error('Invalid WebP signature');
  if (/\.mp3$/.test(pathname) && !(bytes.length >= 10 && bytes.subarray(0, 3).toString() === 'ID3') && !(bytes.length >= 4 && bytes[0] === 255 && (bytes[1] & 224) === 224)) throw new Error('Invalid MP3 signature; source may be an unresolved symlink');
  if (/\.ogg$/.test(pathname) && !(bytes.length >= 27 && bytes.subarray(0, 4).toString() === 'OggS')) throw new Error('Invalid Ogg signature');
  if (/\.wav$/.test(pathname) && !(bytes.length >= 12 && ['RIFF', 'RF64'].includes(bytes.subarray(0, 4).toString()) && bytes.subarray(8, 12).toString() === 'WAVE')) throw new Error('Invalid WAV signature');
  if (/\.(?:gltf|json)$/.test(pathname) || /application\/json/i.test(contentType)) JSON.parse(bytes.toString('utf8'));
}

function lfsMediaUrl(sourceUrl) {
  const url = new URL(sourceUrl);
  if (url.hostname === 'raw.githubusercontent.com') return `https://media.githubusercontent.com/media${url.pathname}`;
  if (['cdn.jsdelivr.net', 'fastly.jsdelivr.net'].includes(url.hostname)) {
    const match = url.pathname.match(/^\/gh\/([^/]+)\/([^/@]+)@([^/]+)\/(.+)$/);
    if (match) return `https://media.githubusercontent.com/media/${match[1]}/${match[2]}/${match[3]}/${match[4]}`;
  }
  return null;
}

export async function fetchAsset(sourceUrl, options = {}) {
  const { timeoutMs = 90_000, retries = 2, fetchImpl = fetch, expectedSha256, updateLock = false } = options;
  let lastError;
  for (let attempt = 0; attempt <= retries; attempt += 1) {
    try {
      const response = await fetchImpl(sourceUrl, { signal: AbortSignal.timeout(timeoutMs), headers: { 'User-Agent': 'TonPlayGram-Asset-Vendor/1.0', Accept: '*/*' } });
      if (!response.ok) throw new Error(`HTTP ${response.status} ${response.statusText}`);
      let bytes;
      if (options.consumeBytes && response.body) {
        const chunks = [];
        for await (const chunk of response.body) {
          options.consumeBytes(chunk.byteLength);
          chunks.push(Buffer.from(chunk));
        }
        bytes = Buffer.concat(chunks);
      } else bytes = Buffer.from(await response.arrayBuffer());
      let contentType = response.headers.get('content-type') || '';
      let resolvedUrl = response.url || sourceUrl;
      if (bytes.subarray(0, 80).toString().startsWith('version https://git-lfs.github.com/spec/v1')) {
        const pointer = bytes.toString();
        const oid = pointer.match(/^oid sha256:([a-f0-9]{64})$/m)?.[1];
        const expectedSize = Number(pointer.match(/^size (\d+)$/m)?.[1]);
        const mediaUrl = lfsMediaUrl(sourceUrl);
        if (!mediaUrl || !oid || !expectedSize) throw new Error('Unresolvable Git LFS pointer');
        const media = await fetchAsset(mediaUrl, { ...options, retries: 0, expectedSha256: oid, updateLock: false });
        if (media.bytes.length !== expectedSize) throw new Error('Git LFS size mismatch');
        ({ bytes, contentType, resolvedUrl } = media);
      }
      validatePayload(bytes, sourceUrl, contentType);
      const digest = sha256(bytes);
      if (expectedSha256 && digest !== expectedSha256 && !updateLock) throw new Error(`Source checksum changed (${digest}); review and use --update-lock to accept it`);
      return { bytes, contentType, resolvedUrl, sourceSha256: digest };
    } catch (error) {
      lastError = error;
      if (/^HTTP (?:400|401|403|404|410)\b/.test(error.message) || /checksum changed|signature|HTML|Git LFS size|Unresolvable|download budget|free disk reserve/i.test(error.message) || attempt === retries) break;
      await sleep(250 * 2 ** attempt);
    }
  }
  throw new Error(`${sourceUrl}: ${lastError.message}`);
}

async function parallelMap(values, concurrency, callback) {
  let cursor = 0;
  return Promise.all(Array.from({ length: Math.min(values.length, concurrency) }, async () => {
    while (cursor < values.length) await callback(values[cursor++]);
  }));
}

export async function readManifest(outputDir) {
  try { return JSON.parse(await readFile(path.join(outputDir, 'manifest.json'), 'utf8')); }
  catch (error) { if (error.code === 'ENOENT') return { schemaVersion: 1, assets: [], failures: [], groups: [] }; throw error; }
}

function localPath(outputDir, publicPrefix, localUrl, publicRoot = path.resolve(outputDir, '../..')) {
  if (!localUrl.startsWith(`${publicPrefix}/`)) {
    if (!localUrl.startsWith('/assets/')) throw new Error(`Unexpected local asset URL: ${localUrl}`);
    const existing = path.resolve(publicRoot, localUrl.slice(1));
    if (!existing.startsWith(`${path.resolve(publicRoot)}${path.sep}`)) throw new Error('Existing asset path escaped public directory');
    return existing;
  }
  const destination = path.resolve(outputDir, localUrl.slice(publicPrefix.length + 1));
  if (!destination.startsWith(`${path.resolve(outputDir)}${path.sep}`)) throw new Error('Asset path escaped output directory');
  return destination;
}

export async function verifyManifest(outputDir, { publicPrefix = '/assets/external', publicRoot, inventory, sourcePins } = {}) {
  const manifest = await readManifest(outputDir);
  const errors = manifest.failures.filter((failure) => failure.essential !== false).map((failure) => `Unresolved ${failure.id || failure.sourceUrl}: ${failure.error}`);
  if (!manifest.assets.length) errors.push('No downloaded assets');
  if (manifest.complete !== true) errors.push('Asset import is incomplete');
  const mapping = manifest.urlMap || Object.fromEntries(manifest.assets.flatMap((entry) => [entry.sourceUrl, ...(entry.aliases || [])].map((url) => [url, entry.url])));
  const sortedMapping = Object.fromEntries(Object.entries(mapping).sort(([a], [b]) => a.localeCompare(b)));
  try {
    const runtimeMap = JSON.parse(await readFile(path.join(outputDir, 'url-map.json'), 'utf8'));
    if (JSON.stringify(Object.fromEntries(Object.entries(runtimeMap).sort(([a], [b]) => a.localeCompare(b)))) !== JSON.stringify(sortedMapping)) errors.push('Runtime JSON mapping differs from manifest');
    if (await readFile(path.join(outputDir, 'url-map.js'), 'utf8') !== mapScript(sortedMapping)) errors.push('Runtime JavaScript mapping differs from manifest');
  } catch (error) { errors.push(`Runtime mapping unavailable: ${error.message}`); }
  await parallelMap(manifest.assets, 4, async (entry) => {
    try {
      const bytes = await readFile(localPath(outputDir, publicPrefix, entry.url, publicRoot));
      if (/\.(?:mp3|ogg|wav)(?:\?|$)/i.test(entry.sourceUrl)) validatePayload(bytes, entry.sourceUrl, entry.contentType);
      if (bytes.length !== entry.size || sha256(bytes) !== entry.sha256) errors.push(`Checksum/size mismatch: ${entry.url}`);
      if (sourcePins?.[entry.sourceUrl] && entry.sourceSha256 !== sourcePins[entry.sourceUrl]) errors.push(`Source lock mismatch: ${entry.sourceUrl}`);
      if (mapping[entry.sourceUrl] !== entry.url) errors.push(`Source mapping mismatch: ${entry.sourceUrl}`);
      for (const dependency of entry.dependencies || []) if (!mapping[dependency.url]) errors.push(`Missing dependency ${dependency.url} from ${entry.sourceUrl}`);
      errors.push(...dependencyReferenceErrors(bytes, entry, mapping));
    } catch (error) { errors.push(`${entry.url}: ${error.message}`); }
  });
  for (const group of inventory?.groups || []) {
    if (group.essential === false) continue;
    if (![...(group.candidates || []), ...(group.aliases || [])].some((url) => mapping[typeof url === 'string' ? url : url.url])) errors.push(`Inventory group missing: ${group.id}`);
  }
  for (const request of inventory?.metadataRequests || []) if (!mapping[request.url]) errors.push(`Metadata request missing: ${request.url}`);
  return { ok: !errors.length, errors, assetCount: manifest.assets.length, totalBytes: manifest.assets.reduce((sum, entry) => sum + entry.size, 0) };
}

/** Only call after verification, on the dedicated generated output directory. */
export async function pruneUnreferencedGeneratedFiles(outputDir, manifest, publicPrefix = '/assets/external') {
  if (manifest.schemaVersion !== 1 || manifest.complete !== true) throw new Error('Cannot prune an incomplete or unknown asset manifest');
  const root = path.resolve(outputDir);
  const retained = new Set(['manifest.json', 'url-map.json', 'url-map.js'].map((name) => path.join(root, name)));
  for (const url of [...manifest.assets.map((asset) => asset.url), ...Object.values(manifest.urlMap)]) {
    if (url.startsWith(`${publicPrefix}/`)) retained.add(localPath(root, publicPrefix, url));
  }
  let removedFiles = 0;
  let removedBytes = 0;
  async function visit(directory) {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const filename = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        await visit(filename);
        try { await rmdir(filename); } catch (error) { if (error.code !== 'ENOTEMPTY') throw error; }
      } else if (entry.isFile() && !retained.has(filename)) {
        const details = await stat(filename);
        await unlink(filename);
        removedFiles += 1;
        removedBytes += details.size;
      }
    }
  }
  await visit(root);
  return { removedFiles, removedBytes };
}

/** Download roots and the complete dependency graph, then atomically publish checksum-pinned mappings. */
export async function vendorInventory(inventory, options) {
  const { outputDir, publicPrefix = '/assets/external', concurrency = 3, onProgress = () => {}, updateLock = false } = options;
  await mkdir(outputDir, { recursive: true });
  const previous = await readManifest(outputDir);
  const pinned = new Map(previous.assets.flatMap((entry) => [entry.sourceUrl, ...(entry.aliases || [])].map((url) => [url, entry])));
  const sourcePins = { ...(previous.sourcePins || {}), ...(options.sourcePins || {}) };
  for (const entry of previous.assets) for (const url of [entry.sourceUrl, ...(entry.aliases || [])]) sourcePins[url] ||= entry.sourceSha256;
  const records = new Map();
  const verifiedLocals = new Map((inventory.localAssets || []).flatMap((asset) => [asset.sourceUrl, ...(asset.aliases || [])].map((url) => [url, asset])));
  const promises = new Map();
  const failures = [...(inventory.failures || [])];
  const selections = [];
  const urlMap = {};
  let checkpointQueue = Promise.resolve();
  let downloadsSinceCheckpoint = 0;
  let downloadedBytes = 0;
  let reservedWriteBytes = 0;
  let resourceFailure;
  const maxDownloadBytes = options.maxDownloadBytes ?? 10 * 1024 ** 3;
  const minFreeBytes = options.minFreeBytes ?? 2 * 1024 ** 3;
  function consumeBytes(size) {
    if (resourceFailure) throw resourceFailure;
    downloadedBytes += size;
    if (downloadedBytes > maxDownloadBytes) {
      resourceFailure = new Error(`Download budget exceeded: limit ${maxDownloadBytes} bytes; import checkpoint retained`);
      throw resourceFailure;
    }
  }
  async function ensureFreeSpace() {
    if (resourceFailure) throw resourceFailure;
    const filesystem = await statfs(outputDir);
    const free = filesystem.bavail * filesystem.bsize;
    if (free - reservedWriteBytes < minFreeBytes) {
      resourceFailure = new Error(`Free disk reserve would be violated: ${free} bytes free, ${reservedWriteBytes} pending writes, ${minFreeBytes} bytes reserved`);
      throw resourceFailure;
    }
  }
  const fetchOptions = { timeoutMs: options.timeoutMs, retries: options.retries, fetchImpl: options.fetchImpl, updateLock, consumeBytes };

  async function acquire(sourceUrl, suppliedBody) {
    sourceUrl = normalizeSourceUrl(sourceUrl);
    if (promises.has(sourceUrl)) return promises.get(sourceUrl);
    const task = (async () => {
      if (resourceFailure) throw resourceFailure;
      if (options.frozenLockfile && suppliedBody === undefined && !options.sourcePins?.[sourceUrl]) throw new Error(`Source is not in the frozen lockfile: ${sourceUrl}`);
      const old = pinned.get(sourceUrl);
      const local = verifiedLocals.get(sourceUrl);
      const url = local?.url || localAssetUrl(sourceUrl, publicPrefix);
      const destination = localPath(outputDir, publicPrefix, url, options.publicRoot);
      if (old?.sourceUrl === sourceUrl && !updateLock && suppliedBody === undefined) {
        if (sourcePins[sourceUrl] && old.sourceSha256 !== sourcePins[sourceUrl]) throw new Error(`Cached source differs from source lock: ${sourceUrl}`);
        try {
          const bytes = await readFile(destination);
          if (bytes.length === old.size && sha256(bytes) === old.sha256) {
            if (/\.(?:mp3|ogg|wav)(?:\?|$)/i.test(sourceUrl)) validatePayload(bytes, sourceUrl, old.contentType);
            const dependencies = new Map((old.dependencies || []).map((dependency) => [dependency.reference, { ...dependency, url: normalizeSourceUrl(dependency.reference, old.resolvedUrl || sourceUrl) }]));
            if (old.dependencySchemaVersion !== DEPENDENCY_SCHEMA_VERSION) {
              const knownLocalUrls = new Set(Object.values(previous.urlMap || {}));
              for (const dependency of findDependencies(bytes, sourceUrl, old.contentType, old.resolvedUrl || sourceUrl)) {
                if (!knownLocalUrls.has(dependency.reference.split('#')[0])) dependencies.set(dependency.reference, dependency);
              }
            }
            // Aliases are rebuilt from the current inventory. Retired or corrected
            // mappings must not survive merely because their payload was cached.
            const record = { ...old, aliases: [],
              dependencies: [...dependencies.values()], dependencySchemaVersion: DEPENDENCY_SCHEMA_VERSION, resumed: true };
            records.set(sourceUrl, record);
            urlMap[sourceUrl] = url;
            for (const alias of record.aliases) urlMap[alias] = url;
            onProgress({ status: 'cached', sourceUrl, size: bytes.length });
            return record;
          }
        } catch (error) { if (error.code !== 'ENOENT') throw error; }
      }
      let downloaded;
      if (suppliedBody !== undefined) downloaded = { bytes: Buffer.from(`${JSON.stringify(suppliedBody, null, 2)}\n`), contentType: 'application/json', sourceSha256: undefined, resolvedUrl: sourceUrl };
      else if (local) {
        const bytes = await readFile(local.filename);
        if (sha256(bytes) !== local.sha256 || bytes.length !== local.size) throw new Error(`Verified local original changed: ${local.filename}`);
        const expected = sourcePins[sourceUrl] || old?.sourceSha256;
        if (expected && expected !== local.sha256 && !updateLock) throw new Error(`Local original checksum differs from source pin: ${sourceUrl}`);
        downloaded = { bytes, contentType: '', sourceSha256: local.sha256, resolvedUrl: sourceUrl };
      } else {
        await ensureFreeSpace();
        downloaded = await fetchAsset(sourceUrl, { ...fetchOptions, expectedSha256: sourcePins[sourceUrl] || old?.sourceSha256 });
      }
      const record = {
        sourceUrl, url, size: downloaded.bytes.length, sha256: sha256(downloaded.bytes),
        sourceSha256: downloaded.sourceSha256 || sha256(downloaded.bytes),
        contentType: downloaded.contentType, resolvedUrl: downloaded.resolvedUrl,
        aliases: [], dependencies: findDependencies(downloaded.bytes, sourceUrl, downloaded.contentType, downloaded.resolvedUrl),
        dependencySchemaVersion: DEPENDENCY_SCHEMA_VERSION,
        ...(local ? { providedLocal: true, provenance: local.provenance } : {})
      };
      records.set(sourceUrl, record);
      urlMap[sourceUrl] = url;
      sourcePins[sourceUrl] = record.sourceSha256;
      onProgress({ status: 'downloaded', sourceUrl, size: record.size });
      // Save raw payload promptly so interrupted large batches can resume via the checkpoint manifest.
      if (!local) {
        reservedWriteBytes += downloaded.bytes.length;
        try { await ensureFreeSpace(); await atomicWrite(destination, downloaded.bytes); }
        finally { reservedWriteBytes -= downloaded.bytes.length; }
      }
      downloadsSinceCheckpoint += 1;
      if (downloadsSinceCheckpoint >= 10) {
        downloadsSinceCheckpoint = 0;
        checkpointQueue = checkpointQueue.then(() => checkpoint());
        await checkpointQueue;
      }
      return record;
    })();
    promises.set(sourceUrl, task);
    try { return await task; } catch (error) { promises.delete(sourceUrl); throw error; }
  }

  function snapshot(final = false) {
    const complete = final && failures.every((failure) => failure.essential === false);
    // An interrupted pass may not have visited a previously downloaded root yet.
    // Retain its checksum record for resumption, without reviving old aliases.
    // Successful publication always contains only the current inventory graph.
    const retained = complete ? [] : previous.assets.filter((entry) => !records.has(entry.sourceUrl)).map((entry) => ({ ...entry, aliases: [] }));
    const assets = [...retained, ...records.values()].map(({ resumed, ...entry }) => entry).sort((a, b) => a.sourceUrl.localeCompare(b.sourceUrl));
    const checkpointMap = { ...Object.fromEntries(retained.map((entry) => [entry.sourceUrl, entry.url])), ...urlMap };
    return { schemaVersion: 1, generatedAt: new Date().toISOString(), complete,
      assets, groups: selections, failures, urlMap: checkpointMap, sourcePins,
      resources: { downloadedBytes, maxDownloadBytes, minFreeBytes } };
  }

  async function checkpoint(final = false) {
    const manifest = snapshot(final);
    await atomicWrite(path.join(outputDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
    if (options.lockPath && !options.frozenLockfile) await atomicWrite(options.lockPath, `${JSON.stringify({ schemaVersion: 1, sourcePins: Object.fromEntries(Object.entries(sourcePins).sort(([a], [b]) => a.localeCompare(b))) }, null, 2)}\n`);
    return manifest;
  }

  const groups = [...(inventory.groups || [])];
  await parallelMap(groups, Math.max(1, Math.min(concurrency, 4)), async (group) => {
    if (resourceFailure) return;
    const candidates = (group.candidates || (group.url ? [group.url] : [])).map((candidate) => typeof candidate === 'string' ? candidate : candidate.url);
    const previousSelection = previous.groups?.find((entry) => entry.id === group.id)?.sourceUrl;
    if (previousSelection && candidates.includes(previousSelection)) candidates.sort((a, b) => Number(b === previousSelection) - Number(a === previousSelection));
    const errors = [];
    for (const candidate of candidates) {
      try {
        const record = await acquire(candidate);
        // An inventory explicitly declares equivalence. Never alias unrelated fallback models.
        const aliases = [...new Set([...(record.aliases || []), ...candidates, ...(group.aliases || [])].map((url) => normalizeSourceUrl(url)))].filter((url) => url !== record.sourceUrl && compatibleDecoder(record.sourceUrl, url));
        record.aliases = aliases;
        record.sources = [...new Set([...(record.sources || []), ...(group.sources || group.referrers || [])])];
        for (const alias of aliases) { urlMap[alias] = record.url; sourcePins[alias] = record.sourceSha256; }
        selections.push({ id: group.id, sourceUrl: record.sourceUrl, essential: group.essential !== false });
        return;
      } catch (error) { errors.push(error.message); if (resourceFailure) break; }
    }
    failures.push({ id: group.id, candidates, essential: group.essential !== false, error: errors.join('; ') || 'No candidate URLs' });
    onProgress({ status: 'failed', id: group.id, error: errors.at(-1) || 'No candidate URLs' });
  });
  await checkpointQueue;
  await checkpoint();

  const examined = new Set();
  while (true) {
    if (resourceFailure) break;
    const pending = new Set();
    for (const record of records.values()) {
      if (examined.has(record.sourceUrl)) continue;
      examined.add(record.sourceUrl);
      for (const dependency of record.dependencies || []) if (!urlMap[dependency.url]) pending.add(dependency.url);
    }
    if (!pending.size) break;
    await parallelMap([...pending], Math.max(1, Math.min(concurrency, 4)), async (sourceUrl) => {
      if (resourceFailure) return;
      try { await acquire(sourceUrl); }
      catch (error) { failures.push({ sourceUrl, essential: true, error: error.message }); onProgress({ status: 'failed', sourceUrl, error: error.message }); }
    });
    await checkpoint();
  }

  for (const request of inventory.metadataRequests || []) {
    if (resourceFailure) break;
    if (request.body === undefined) {
      failures.push({ sourceUrl: request.url, error: 'Metadata was not resolved by its inventory provider', essential: true });
      continue;
    }
    const metadataBody = inventory.filterMetadata ? inventory.filterMetadata(request.body, new Set(Object.keys(urlMap))) : request.body;
    const record = await acquire(request.url, metadataBody);
    record.aliases = [...new Set(request.aliases || [])];
    for (const alias of record.aliases) urlMap[normalizeSourceUrl(alias)] = record.url;
    const unresolved = new Set();
    const inspect = (value) => {
      if (typeof value === 'string' && NETWORK_URL.test(value) && !urlMap[normalizeSourceUrl(value)]) unresolved.add(value);
      else if (Array.isArray(value)) value.forEach(inspect);
      else if (value && typeof value === 'object') Object.values(value).forEach(inspect);
    };
    inspect(metadataBody);
    if (unresolved.size) failures.push({ sourceUrl: request.url, error: `Metadata refers to unbundled URLs: ${[...unresolved].join(', ')}`, essential: true });
  }

  for (const record of records.values()) {
    if (resourceFailure) break;
    if (!record.providedLocal && ['gltf', 'glb', 'json', 'css', 'javascript'].includes(sourceType(record.sourceUrl, record.contentType))) {
      let original = await readFile(localPath(outputDir, publicPrefix, record.url));
      // A cached document may contain a formerly selected local target. Restore
      // its exact pinned source rather than guessing which collapsed alias the
      // old local URI represented, then rewrite against the current graph.
      if (dependencyReferenceErrors(original, record, urlMap, true).length) {
        await ensureFreeSpace();
        const refreshed = await fetchAsset(record.sourceUrl, { ...fetchOptions, expectedSha256: record.sourceSha256, updateLock: false });
        original = refreshed.bytes;
      }
      const bytes = rewriteDependencies(original, record.sourceUrl, record.contentType, urlMap, record.dependencies);
      const referenceErrors = dependencyReferenceErrors(bytes, record, urlMap);
      if (referenceErrors.length) throw new Error(referenceErrors.join('; '));
      reservedWriteBytes += bytes.length;
      try {
        await ensureFreeSpace();
        await atomicWrite(localPath(outputDir, publicPrefix, record.url), bytes);
        record.sha256 = sha256(bytes);
        record.size = bytes.length;
      } catch (error) { if (!resourceFailure) throw error; }
      finally { reservedWriteBytes -= bytes.length; }
    }
  }
  if (resourceFailure) failures.push({ id: 'resource-budget', essential: true, error: resourceFailure.message });
  const sortedMap = Object.fromEntries(Object.entries(snapshot(true).urlMap).sort(([a], [b]) => a.localeCompare(b)));
  await atomicWrite(path.join(outputDir, 'url-map.json'), `${JSON.stringify(sortedMap, null, 2)}\n`);
  await atomicWrite(path.join(outputDir, 'url-map.js'), mapScript(sortedMap));
  return checkpoint(true);
}
