export type PlayerSide = "near" | "far";
export type ServeCourtSide = "deuce" | "ad";
export type ShotType = "flat" | "topspin" | "slice" | "lob" | "drop" | "block";

const WORLD_SCALE = 1.2;

export const gameConfig = {
  worldScale: WORLD_SCALE,
  fixedTimeStep: 1 / 120,
  maxSubSteps: 5,
  courtW: 7.45 * WORLD_SCALE,
  doublesW: 8.9 * WORLD_SCALE,
  courtL: 19.8 * WORLD_SCALE,
  serviceLineZ: 3.65 * WORLD_SCALE,
  netH: 0.78 * WORLD_SCALE,
  ballR: 0.1 * WORLD_SCALE,
  gravity: 9.8,
  airDrag: 0.09,
  bounceRestitution: 0.72,
  groundFriction: 0.84,
  courtFriction: 0.84,
  minBallSpeed: 0.12 * WORLD_SCALE,
  playerHeight: 2.2 * WORLD_SCALE,
  playerSpeed: 7.1 * WORLD_SCALE,
  aiSpeed: 10.2 * WORLD_SCALE,
  reach: 1.45 * WORLD_SCALE,
  swingDuration: 0.38,
  serveDuration: 0.86,
  hitWindowStart: 0.42,
  hitWindowEnd: 0.72,
  timingWindow: 0.18,
  serveContactT: 0.72,
  playerVisualYawFix: Math.PI,
  serveNearBaselineZ: 8.2 * WORLD_SCALE,
  serviceBuffer: 0.18 * WORLD_SCALE,
  racketHitRadius: 0.44 * WORLD_SCALE,
  contactAngleTolerance: 0.16,
  minContactHeight: 0.32 * WORLD_SCALE,
  maxContactHeight: 1.95 * WORLD_SCALE,
  maxReachDistance: 1.58 * WORLD_SCALE,
  servePower: 1.0,
  shotPower: 1.0,
  spinAmount: 0.75,
  cameraDamping: 5.5,
  playerBounds: {
    nearMinZ: 0.72 * WORLD_SCALE,
    nearMaxZ: 8.85 * WORLD_SCALE,
    farMinZ: -8.85 * WORLD_SCALE,
    farMaxZ: -0.72 * WORLD_SCALE,
    sideInset: 0.32 * WORLD_SCALE,
  },
  aiDifficulty: {
    reactionTime: 0.2,
    movementSpeed: 10.2 * WORLD_SCALE,
    reachRadius: 1.38 * WORLD_SCALE,
    accuracy: 0.78,
    power: 0.82,
    spin: 0.48,
    mistakeChance: 0.12,
    serveQuality: 0.72,
  },
  scoring: { gamesEnabled: false },
} as const;
