import { BOWLING_DEFAULT_LOADOUT, BOWLING_DEFAULT_UNLOCKS, BOWLING_OPTION_LABELS } from '../config/bowlingInventoryConfig.js';
const STORAGE_KEY = 'bowlingInventoryByAccount';
const copyDefaults = () => Object.fromEntries(Object.entries(BOWLING_DEFAULT_UNLOCKS).map(([k,v]) => [k,[...v]]));
const resolveAccountId = (accountId) => accountId || (typeof window !== 'undefined' && window.localStorage.getItem('accountId')) || 'guest';
const read = () => { try { return JSON.parse(window.localStorage.getItem(STORAGE_KEY) || '{}'); } catch { return {}; } };
const write = (db) => window.localStorage.setItem(STORAGE_KEY, JSON.stringify(db));
const normalize = (inv) => { const b = copyDefaults(); Object.entries(inv||{}).forEach(([k,v]) => { if (Array.isArray(v)) b[k] = Array.from(new Set([...(b[k]||[]), ...v])); }); return b; };
export const getBowlingInventory = (accountId) => { if (typeof window === 'undefined') return copyDefaults(); const id=resolveAccountId(accountId); const db=read(); const n=normalize(db[id]); write({...db,[id]:n}); return n; };
export const isBowlingOptionUnlocked = (type, optionId, invOrId) => { const inv = typeof invOrId === 'string' || !invOrId ? getBowlingInventory(invOrId) : invOrId; return Array.isArray(inv?.[type]) && inv[type].includes(optionId); };
export const addBowlingUnlock = (type, optionId, accountId) => { const id=resolveAccountId(accountId); const db=read(); const cur=normalize(db[id]); cur[type] = Array.from(new Set([...(cur[type]||[]), optionId])); write({...db,[id]:cur}); window.dispatchEvent(new CustomEvent('bowlingInventoryUpdate',{detail:{accountId:id, inventory:cur}})); return cur; };
export const listOwnedBowlingOptions = (accountId) => Object.entries(getBowlingInventory(accountId)).flatMap(([type, values]) => (values||[]).map((optionId)=>({type,optionId,label:BOWLING_OPTION_LABELS[type]?.[optionId]||optionId})));
export const getDefaultBowlingLoadout = () => [...BOWLING_DEFAULT_LOADOUT];
export const bowlingAccountId = resolveAccountId;
