export const LEADER_AVATARS = [
  '/assets/icons/AlbaniaLeader.jpg',
  '/assets/icons/UkraineLeader.jpg',
  '/assets/icons/CanadaLeader.jpg',
  '/assets/icons/GermanyLeader.jpg',
  '/assets/icons/JapanLeader.jpg',
  '/assets/icons/UnitedKingdomLeader .jpg',
  '/assets/icons/FranceLeader.jpg',
  '/assets/icons/IndiaLeader.jpg',
  '/assets/icons/ChinaLeader.jpg',
  '/assets/icons/RussiaLeader.jpg',
  '/assets/icons/UsaLeader.webp',
  '/assets/icons/ItalyLeader.jpg',
  '/assets/icons/GreeceLeader.jpg',
  '/assets/icons/TurkeyLeader.jpg',
  '/assets/icons/VenezuelaLeader.jpg',
  '/assets/icons/BukinaFasoLeader.jpg',
  '/assets/icons/DubaiLeader.jpg',
  '/assets/icons/SudArabiaLeader.jpg',
  '/assets/icons/IsraelLeader.jpg',
  '/assets/icons/JordanLeader.jpg',
  '/assets/icons/EgyptLeader.jpg',
  '/assets/icons/IranLeader.jpg',
  '/assets/icons/SerbiaLeader.jpg',
  '/assets/icons/HungaryLeader.jpg',
  '/assets/icons/BelarusLeader.jpg',
  '/assets/icons/NorthKoreaLeader.jpg'
];
