// Shared Ludo Battle Royal IDs. Values are fictional arcade balance.
export const WEAPONS = Object.freeze([
  {
    "id": "fpsGunAttack",
    "label": "FPS Gun",
    "category": "shotgun",
    "model": "shotgun",
    "magazine": 6,
    "damage": 48,
    "interval": 0.82,
    "range": 19,
    "reload": 2.5,
    "price": 270,
    "radius": 0
  },
  {
    "id": "glockSidearmAttack",
    "label": "Glock Sidearm",
    "category": "sidearm",
    "model": "sigsauer",
    "magazine": 16,
    "damage": 24,
    "interval": 0.32,
    "range": 24,
    "reload": 1.4,
    "price": 80,
    "radius": 0
  },
  {
    "id": "assaultRifleAttack",
    "label": "Assault Rifle",
    "category": "rifle",
    "model": "ak47",
    "magazine": 30,
    "damage": 19,
    "interval": 0.13,
    "range": 48,
    "reload": 2.1,
    "price": 305,
    "radius": 0
  },
  {
    "id": "uziSprayAttack",
    "label": "Uzi Spray",
    "category": "smg",
    "model": "uzi",
    "magazine": 28,
    "damage": 13,
    "interval": 0.085,
    "range": 28,
    "reload": 1.8,
    "price": 240,
    "radius": 0
  },
  {
    "id": "ak47VolleyAttack",
    "label": "AK-47 Volley",
    "category": "rifle",
    "model": "ak47",
    "magazine": 30,
    "damage": 19,
    "interval": 0.13,
    "range": 48,
    "reload": 2.1,
    "price": 280,
    "radius": 0
  },
  {
    "id": "krsvBurstAttack",
    "label": "KRSV Burst",
    "category": "rifle",
    "model": "krsv",
    "magazine": 30,
    "damage": 19,
    "interval": 0.13,
    "range": 48,
    "reload": 2.1,
    "price": 305,
    "radius": 0
  },
  {
    "id": "smithSidearmAttack",
    "label": "Smith Sidearm",
    "category": "sidearm",
    "model": "smith",
    "magazine": 16,
    "damage": 24,
    "interval": 0.32,
    "range": 24,
    "reload": 1.4,
    "price": 130,
    "radius": 0
  },
  {
    "id": "mosinMarksmanAttack",
    "label": "Mosin Marksman",
    "category": "marksman",
    "model": "mosin",
    "magazine": 5,
    "damage": 62,
    "interval": 1.1,
    "range": 82,
    "reload": 2.7,
    "price": 380,
    "radius": 0
  },
  {
    "id": "sigsauerTacticalAttack",
    "label": "SigSauer Tactical",
    "category": "sidearm",
    "model": "sigsauer",
    "magazine": 16,
    "damage": 24,
    "interval": 0.32,
    "range": 24,
    "reload": 1.4,
    "price": 105,
    "radius": 0
  },
  {
    "id": "grenadeBlastAttack",
    "label": "Grenade Blast",
    "category": "launcher",
    "model": "polyHandGrenade01Attack",
    "magazine": 1,
    "damage": 85,
    "interval": 1.8,
    "range": 48,
    "reload": 3.2,
    "price": 610,
    "radius": 6
  },
  {
    "id": "shotgunBlastAttack",
    "label": "Shotgun Blast",
    "category": "shotgun",
    "model": "shotgun",
    "magazine": 6,
    "damage": 48,
    "interval": 0.82,
    "range": 19,
    "reload": 2.5,
    "price": 220,
    "radius": 0
  },
  {
    "id": "sniperShotAttack",
    "label": "Sniper Shot",
    "category": "marksman",
    "model": "mosin",
    "magazine": 5,
    "damage": 62,
    "interval": 1.1,
    "range": 82,
    "reload": 2.7,
    "price": 405,
    "radius": 0
  },
  {
    "id": "smgBurstAttack",
    "label": "SMG Burst",
    "category": "smg",
    "model": "uzi",
    "magazine": 28,
    "damage": 13,
    "interval": 0.085,
    "range": 28,
    "reload": 1.8,
    "price": 240,
    "radius": 0
  },
  {
    "id": "compactCarbineAttack",
    "label": "Compact Carbine",
    "category": "rifle",
    "model": "ak47",
    "magazine": 30,
    "damage": 19,
    "interval": 0.13,
    "range": 48,
    "reload": 2.1,
    "price": 280,
    "radius": 0
  },
  {
    "id": "marksmanDmrAttack",
    "label": "Marksman DMR",
    "category": "marksman",
    "model": "mosin",
    "magazine": 5,
    "damage": 62,
    "interval": 1.1,
    "range": 82,
    "reload": 2.7,
    "price": 405,
    "radius": 0
  },
  {
    "id": "polyShotgun01Attack",
    "label": "Quaternius Shotgun",
    "category": "shotgun",
    "model": "polyShotgun01Attack",
    "magazine": 6,
    "damage": 48,
    "interval": 0.82,
    "range": 19,
    "reload": 2.5,
    "price": 270,
    "radius": 0
  },
  {
    "id": "polyAssaultRifle01Attack",
    "label": "Quaternius Assault Rifle",
    "category": "rifle",
    "model": "polyAssaultRifle01Attack",
    "magazine": 30,
    "damage": 19,
    "interval": 0.13,
    "range": 48,
    "reload": 2.1,
    "price": 280,
    "radius": 0
  },
  {
    "id": "polyPistol01Attack",
    "label": "Quaternius Pistol",
    "category": "sidearm",
    "model": "polyPistol01Attack",
    "magazine": 16,
    "damage": 24,
    "interval": 0.32,
    "range": 24,
    "reload": 1.4,
    "price": 105,
    "radius": 0
  },
  {
    "id": "polyRevolver01Attack",
    "label": "Quaternius Heavy Revolver",
    "category": "sidearm",
    "model": "polyRevolver01Attack",
    "magazine": 16,
    "damage": 24,
    "interval": 0.32,
    "range": 24,
    "reload": 1.4,
    "price": 130,
    "radius": 0
  },
  {
    "id": "polySawedOff01Attack",
    "label": "Quaternius Sawed-Off Shotgun",
    "category": "shotgun",
    "model": "polySawedOff01Attack",
    "magazine": 6,
    "damage": 48,
    "interval": 0.82,
    "range": 19,
    "reload": 2.5,
    "price": 220,
    "radius": 0
  },
  {
    "id": "polyRevolver02Attack",
    "label": "Quaternius Revolver Silver",
    "category": "sidearm",
    "model": "polyRevolver02Attack",
    "magazine": 16,
    "damage": 24,
    "interval": 0.32,
    "range": 24,
    "reload": 1.4,
    "price": 105,
    "radius": 0
  },
  {
    "id": "polyShotgun02Attack",
    "label": "Quaternius Long Shotgun",
    "category": "shotgun",
    "model": "polyShotgun02Attack",
    "magazine": 6,
    "damage": 48,
    "interval": 0.82,
    "range": 19,
    "reload": 2.5,
    "price": 270,
    "radius": 0
  },
  {
    "id": "polyShotgun03Attack",
    "label": "Quaternius Pump Shotgun",
    "category": "shotgun",
    "model": "polyShotgun03Attack",
    "magazine": 6,
    "damage": 48,
    "interval": 0.82,
    "range": 19,
    "reload": 2.5,
    "price": 220,
    "radius": 0
  },
  {
    "id": "polySmg01Attack",
    "label": "Quaternius Submachine Gun",
    "category": "smg",
    "model": "polySmg01Attack",
    "magazine": 28,
    "damage": 13,
    "interval": 0.085,
    "range": 28,
    "reload": 1.8,
    "price": 215,
    "radius": 0
  },
  {
    "id": "polyRobotLargeGunAttack",
    "label": "Quaternius Robot Large Gun",
    "category": "rifle",
    "model": "polyRobotLargeGunAttack",
    "magazine": 30,
    "damage": 19,
    "interval": 0.13,
    "range": 48,
    "reload": 2.1,
    "price": 330,
    "radius": 0
  },
  {
    "id": "polyRobotFlyingGunAttack",
    "label": "Quaternius Robot Flying Gun",
    "category": "smg",
    "model": "polyRobotFlyingGunAttack",
    "magazine": 28,
    "damage": 13,
    "interval": 0.085,
    "range": 28,
    "reload": 1.8,
    "price": 190,
    "radius": 0
  },
  {
    "id": "polyBazooka01Attack",
    "label": "CreativeTrio Bazooka",
    "category": "launcher",
    "model": "polyBazooka01Attack",
    "magazine": 1,
    "damage": 85,
    "interval": 1.8,
    "range": 48,
    "reload": 3.2,
    "price": 585,
    "radius": 6
  },
  {
    "id": "polyGrenadeLauncher01Attack",
    "label": "CreativeTrio Grenade Launcher",
    "category": "launcher",
    "model": "polyGrenadeLauncher01Attack",
    "magazine": 1,
    "damage": 85,
    "interval": 1.8,
    "range": 48,
    "reload": 3.2,
    "price": 610,
    "radius": 6
  },
  {
    "id": "polyDynamiteBomb01Attack",
    "label": "CreativeTrio Dynamite Bomb",
    "category": "launcher",
    "model": "polyDynamiteBomb01Attack",
    "magazine": 1,
    "damage": 85,
    "interval": 1.8,
    "range": 48,
    "reload": 3.2,
    "price": 560,
    "radius": 6
  },
  {
    "id": "polyMolotov01Attack",
    "label": "CreativeTrio Molotov",
    "category": "launcher",
    "model": "polyMolotov01Attack",
    "magazine": 1,
    "damage": 85,
    "interval": 1.8,
    "range": 48,
    "reload": 3.2,
    "price": 585,
    "radius": 6
  },
  {
    "id": "polyGasTank01Attack",
    "label": "Quaternius Gas Tank",
    "category": "launcher",
    "model": "polyGasTank01Attack",
    "magazine": 1,
    "damage": 85,
    "interval": 1.8,
    "range": 48,
    "reload": 3.2,
    "price": 610,
    "radius": 6
  },
  {
    "id": "polyHandGrenade01Attack",
    "label": "CreativeTrio Hand Grenade",
    "category": "launcher",
    "model": "polyHandGrenade01Attack",
    "magazine": 1,
    "damage": 85,
    "interval": 1.8,
    "range": 48,
    "reload": 3.2,
    "price": 560,
    "radius": 6
  },
  {
    "id": "pistolSidearmAttack",
    "label": "Pistol Sidearm",
    "category": "sidearm",
    "model": "smith",
    "magazine": 16,
    "damage": 24,
    "interval": 0.32,
    "range": 24,
    "reload": 1.4,
    "price": 130,
    "radius": 0
  }
].map(Object.freeze));
export const WEAPON_BY_ID = new Map(WEAPONS.map(w => [w.id, w]));
export const STARTER_WEAPON = "polyPistol01Attack";
export const DIFFICULTIES = Object.freeze({ easy: {label:"Explorer", damage:0.55, time:1.35, rival:0.8, reward:0.8}, normal: {label:"Street", damage:1, time:1, rival:1, reward:1}, hard: {label:"Veteran", damage:1.45, time:0.85, rival:1.14, reward:1.25} });
export const difficultyOf = id => DIFFICULTIES[id] || DIFFICULTIES.normal;
