import fs from 'node:fs';
import path from 'node:path';
import {gzipSync} from 'node:zlib';

/** Strings avoid millions of AST nodes in Vite; gzip reduces shipped map bytes.
 * Bounded modules also keep individual generated Git objects reviewable. */
export function writeCompressedSource(payload,root){
 const folder=path.join(root,'data-parts');
 fs.mkdirSync(folder,{recursive:true});
 for(const name of fs.readdirSync(folder))if(/^part-\d+\.mjs$/.test(name))fs.unlinkSync(path.join(folder,name));
 const encoded=gzipSync(JSON.stringify(payload),{level:9,mtime:0}).toString('base64');
 const imports=[],names=[];
 for(let offset=0;offset<encoded.length;offset+=393216){
  const name='part-'+String(names.length).padStart(3,'0')+'.mjs',binding='p'+names.length;
  fs.writeFileSync(path.join(folder,name),'// © OpenStreetMap contributors, ODbL-1.0. Generated gzip/base64.\nexport default '+JSON.stringify(encoded.slice(offset,offset+393216))+';\n');
  imports.push(`import ${binding} from './data-parts/${name}';`);names.push(binding);
 }
 fs.writeFileSync(path.join(root,'data.mjs'),`// © OpenStreetMap contributors, ODbL-1.0. Generated by build-tirana-neighbourhood.mjs.
import {decodeSource} from './decodeSource.mjs';
import {unpackRecords} from './unpackSource.mjs';
${imports.join('\n')}
const payload=decodeSource([${names.join(',')}]);
const roadWays=Object.fromEntries(unpackRecords(payload.roadWays).map(r=>[r.way,r]));
const points=payload.points;
export const NEIGHBOURHOOD=payload.neighbourhood;
NEIGHBOURHOOD.roads=payload.segments.map(([way,segment,a,b])=>({...roadWays[way],id:way+':'+segment,way,a:points[a].slice(1),b:points[b].slice(1),nodeA:points[a][0],nodeB:points[b][0]}));
for(const key of ['buildings','places','storefronts'])NEIGHBOURHOOD[key]=unpackRecords(NEIGHBOURHOOD[key]);
`);
 return {parts:names.length,base64Bytes:encoded.length};
}
