import { TABLE_MODEL_OPENSOURCE_GLB_URL } from './snookerTableModel.js';

export const SNOOKER_ROYAL_SHARED_TABLE_GLB_URL = TABLE_MODEL_OPENSOURCE_GLB_URL;
export const SNOOKER_ROYAL_SHARED_TABLE_FALLBACK_GLB_URL = TABLE_MODEL_OPENSOURCE_GLB_URL;
export const SNOOKER_ROYAL_SHARED_LOBBY_ART_SLUG = 'snookerroyale';
export const SNOOKER_ROYAL_SHARED_STORAGE_PREFIX = 'snookerChampion:';
export const SNOOKER_ROYAL_SHARED_DEFAULT_CAMERA_MODE = 'tv-broadcast';
export const SNOOKER_ROYAL_SHARED_DEFAULT_BROADCAST_SYSTEM = 'pocket-cuts';
export const SNOOKER_ROYAL_SHARED_SHOT_POWER_BOOST = 0.455;
export const SNOOKER_ROYAL_SHARED_SHOT_SPIN_SCALE = 0.25;

export const SNOOKER_ROYAL_SHARED_GAMEPLAY_PRESET = Object.freeze({
  tableGlbUrl: SNOOKER_ROYAL_SHARED_TABLE_GLB_URL,
  fallbackTableGlbUrl: SNOOKER_ROYAL_SHARED_TABLE_FALLBACK_GLB_URL,
  lobbyArtSlug: SNOOKER_ROYAL_SHARED_LOBBY_ART_SLUG,
  storagePrefix: SNOOKER_ROYAL_SHARED_STORAGE_PREFIX,
  defaultCameraMode: SNOOKER_ROYAL_SHARED_DEFAULT_CAMERA_MODE,
  defaultBroadcastSystem: SNOOKER_ROYAL_SHARED_DEFAULT_BROADCAST_SYSTEM,
  shotPowerBoost: SNOOKER_ROYAL_SHARED_SHOT_POWER_BOOST,
  shotSpinScale: SNOOKER_ROYAL_SHARED_SHOT_SPIN_SCALE
});
