import React, {act} from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter} from 'react-router-dom';
import {afterEach,expect,it,vi} from 'vitest';
import TiranaStreetsLobby from './TiranaStreetsLobby.jsx';
vi.mock('../../games/tiranastreets/PlayerPicker',()=>({PlayerPicker:({onStart})=><button onClick={onStart}>Choose player</button>}));
vi.mock('./BlackwaterLobby.jsx',()=>({default:()=> <div>Online room setup</div>}));
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
let root,host;
afterEach(async()=>{await act(async()=>root?.unmount());host?.remove();});
it('offers one saved city campaign after choosing a player, with online rooms in a separate disclosure',async()=>{
  host=document.createElement('div');document.body.append(host);root=createRoot(host);
  await act(async()=>root.render(<MemoryRouter><TiranaStreetsLobby/></MemoryRouter>));
  expect(host.querySelector('.tsl-launch')).toBeNull();
  await act(async()=>host.querySelector('button').click());
  expect(host.querySelectorAll('.tsl-launch')).toHaveLength(1);
  expect(host.querySelector('.tsl-launch').getAttribute('href')).toContain('activity=street-career');
  expect(host.textContent).not.toMatch(/Choose Battlefield|Career mode|POLICIA/);
  expect(host.querySelector('details').open).toBe(false);
  expect(host.querySelector('summary').textContent).toContain('Play with friends');
  await act(async()=>[...host.querySelectorAll('button')].find(b=>b.textContent==='Change player').click());
  expect(host.querySelector('.tsl-launch')).toBeNull();
});
