name: Node.js CI

on:
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            bot/node_modules
            webapp/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Setup system dependencies
        run: bash scripts/setup-tests.sh

      - name: Install Node dependencies
        run: |
          npm ci
          npm ci --prefix bot
          npm ci --prefix webapp

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test
